import type { Metadata } from 'next'
import Link from 'next/link'
import BackLink from '@/components/BackLink'
import FloridaRules from '@/components/FloridaRules'
import OpenAACrossLinks from '@/components/OpenAACrossLinks'
import { getStateQuestionCount } from '@/lib/state-question-bank'

export const metadata: Metadata = { title:'2026 佛州 Class E 驾照笔试指南｜50题模拟考试', description:'Florida Class E Knowledge Exam 中文学习指南：50题考试、Learner License、50小时监督驾驶、校车、限速和交通标志。', alternates:{ canonical:'/florida/guide' } }
export default function FloridaGuidePage(){ const count=getStateQuestionCount('florida'); const steps=['先阅读 Florida Driver License Handbook，建立 Class E 规则框架。','用中文题库理解 Florida 专属规则，再切换 English / 中英对照熟悉考试词汇。','重点掌握 school zone 20 mph、标准限速、school bus、Learner 时间限制、50小时监督驾驶和 DUI。','完成 50 题模拟考试，并把错题集中到错题本反复练习。','正式考试前再次核对 FLHSMV 当前考试、材料和预约说明。']; return <><section className="bg-white py-12"><div className="page-shell"><BackLink href="/florida" label="返回佛州 Class E"/><div className="grid gap-8 lg:grid-cols-[1fr_0.75fr]"><article><p className="text-sm font-bold text-teal-700">Florida Class E Driver Guide</p><h1 className="mt-2 text-4xl font-black">2026 佛州 Class E 驾照笔试指南</h1><p className="mt-5 text-base leading-8 text-slate-700">Florida Class E Knowledge Exam 共 50 道选择题，覆盖交通法规、安全驾驶和交通控制识别。授权第三方在线考试要求 60 分钟时限。</p><p className="mt-4 text-base leading-8 text-slate-700">本站当前提供 {count} 道 Florida 专属与公共核心练习题，支持中文、English 和中英对照。</p><div className="mt-8 grid gap-3">{steps.map((item,index)=><div key={item} className="card p-4"><p className="text-sm font-black text-blue-700">步骤 {index+1}</p><p className="mt-2 text-sm leading-6 text-slate-700">{item}</p></div>)}</div></article><aside className="grid content-start gap-4"><div className="card p-5"><h2 className="text-xl font-black">学习入口</h2><div className="mt-4 grid gap-2"><Link href="/florida/questions" className="rounded-md bg-slate-100 px-3 py-2 text-sm font-bold">题库（{count}题）</Link><Link href="/florida/practice" className="rounded-md bg-slate-100 px-3 py-2 text-sm font-bold">顺序/随机练习</Link><Link href="/florida/mock-test" className="rounded-md bg-slate-100 px-3 py-2 text-sm font-bold">50题模拟考试</Link><Link href="/florida/wrong-questions" className="rounded-md bg-slate-100 px-3 py-2 text-sm font-bold">错题本</Link></div></div></aside></div></div></section><FloridaRules/><OpenAACrossLinks/></> }
