import type { Metadata } from 'next'
import Link from 'next/link'
import BackLink from '@/components/BackLink'
import FloridaRules from '@/components/FloridaRules'
import OpenAACrossLinks from '@/components/OpenAACrossLinks'
import { getStateQuestions } from '@/lib/state-question-bank'

export const metadata: Metadata = { title:'2026 佛州 DMV 中文题库｜Florida Class E 50题模拟考试', description:'Florida Class E Knowledge Exam 中文、English 和中英对照学习入口，包含50题模拟考试、Learner规则、交通标志和错题复习。', alternates:{ canonical:'/florida' } }

export default function FloridaPage(){ const questions=getStateQuestions('florida'); return <><div className="bg-white pt-6"><div className="page-shell"><BackLink href="/" label="返回美国 DMV 首页" /></div></div><section className="bg-slate-950 text-white"><div className="page-shell py-12"><p className="text-sm font-bold text-cyan-100">Florida · FL</p><h1 className="mt-3 text-4xl font-black md:text-5xl">佛罗里达州 Class E 中文题库</h1><p className="mt-4 max-w-3xl text-base leading-7 text-slate-200">面向准备 FLHSMV Class E Knowledge Exam 的用户，提供中文、English 和中英对照题库、50题模拟考试、交通标志和错题复习。</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/florida/mock-test" className="rounded-md bg-cyan-400 px-4 py-2.5 text-sm font-black text-slate-950">开始50题模拟考试</Link><Link href="/florida/questions" className="rounded-md border border-white/20 px-4 py-2.5 text-sm font-bold">先刷题库</Link></div><div className="mt-6 rounded-lg border border-white/15 bg-white/10 p-4"><p className="font-black text-cyan-100">考试提醒</p><p className="mt-2 text-sm leading-6 text-slate-200">Class E Knowledge Exam 共 50 道选择题。授权第三方在线考试按 60 分钟时限执行。</p></div></div></section><FloridaRules/><section className="bg-[#f4f7fb] py-10"><div className="page-shell grid gap-4 md:grid-cols-3"><div className="card p-5"><p className="text-sm font-bold text-teal-700">当前题库</p><p className="mt-2 text-3xl font-black">{questions.length} 题</p><p className="mt-2 text-sm text-slate-600">Florida 专属题 + 去重公共核心题。</p></div><div className="card p-5"><p className="text-sm font-bold text-teal-700">模拟考试</p><p className="mt-2 text-3xl font-black">50 题</p><p className="mt-2 text-sm text-slate-600">按 Class E 正式题量组卷。</p></div><div className="card p-5"><p className="text-sm font-bold text-teal-700">学习语言</p><p className="mt-2 text-xl font-black">中文 / English / 中英对照</p></div></div></section><section className="bg-white py-10"><div className="page-shell"><div className="card p-5"><h2 className="text-2xl font-black">学习入口</h2><div className="mt-4 flex flex-wrap gap-3"><Link href="/florida/questions" className="rounded-md bg-blue-700 px-4 py-2 text-sm font-black text-white">全部题目</Link><Link href="/florida/practice" className="rounded-md border border-slate-300 px-4 py-2 text-sm font-bold">顺序/随机练习</Link><Link href="/florida/signs" className="rounded-md border border-slate-300 px-4 py-2 text-sm font-bold">交通标志</Link><Link href="/florida/wrong-questions" className="rounded-md border border-slate-300 px-4 py-2 text-sm font-bold">错题本</Link><Link href="/florida/guide" className="rounded-md border border-slate-300 px-4 py-2 text-sm font-bold">考试指南</Link></div></div></div></section><OpenAACrossLinks/></> }
