import type { Metadata } from 'next'
import Link from 'next/link'
import BackLink from '@/components/BackLink'
import FloridaRules from '@/components/FloridaRules'
import OpenAACrossLinks from '@/components/OpenAACrossLinks'
import ToolGrid from '@/components/ToolGrid'
import { getStateBySlug } from '@/lib/dmv-data'
import { getStateQuestions } from '@/lib/state-question-bank'

export const metadata: Metadata = { title:'2026 佛州 DMV 驾照题库｜Florida Class E 50题模拟考试', description:'Florida Class E Knowledge Exam 中文、English 和中英对照学习入口，包含完整题库、顺序练习、50题模拟考试、交通标志、错题本和考试指南。', alternates:{ canonical:'/florida' } }

export default function FloridaPage(){ const state=getStateBySlug('florida')!; const questions=getStateQuestions('florida'); return <><div className="bg-white pt-6"><div className="page-shell"><BackLink href="/" label="返回美国 DMV 首页" /></div></div><section className="bg-slate-950 text-white"><div className="page-shell py-12"><p className="text-sm font-bold text-cyan-100">Florida · FLHSMV</p><h1 className="mt-3 text-4xl font-black md:text-5xl">佛罗里达州 Class E 驾照题库</h1><p className="mt-4 max-w-3xl text-base leading-7 text-slate-200">覆盖 Florida 道路规则、交通标志、安全驾驶和常见考试知识点，支持中文、English 和中英对照学习；模拟考试每次随机抽取 50 题。</p><div className="mt-6 flex flex-wrap gap-3"><Link href="/florida/mock-test" className="rounded-md bg-cyan-400 px-4 py-2.5 text-sm font-black text-slate-950">开始50题模拟考试</Link><Link href="/florida/questions" className="rounded-md border border-white/20 px-4 py-2.5 text-sm font-bold">查看完整题库</Link><Link href="/florida/practice" className="rounded-md border border-white/20 px-4 py-2.5 text-sm font-bold">顺序 / 随机练习</Link></div><div className="mt-6 rounded-lg border border-white/15 bg-white/10 p-4"><p className="font-black text-cyan-100">考试提醒</p><p className="mt-2 text-sm leading-6 text-slate-200">Class E Knowledge Exam 共 50 道选择题；FLHSMV 授权第三方在线考试按 60 分钟时限执行。</p></div></div></section><section className="bg-amber-50 py-5"><div className="page-shell"><div className="rounded-lg border-2 border-amber-300 bg-white p-4"><p className="font-black text-amber-900">正式考试语言提醒</p><p className="mt-1 text-sm leading-6 text-amber-900">目前本站尚未确认 FLHSMV Class E 正式 Knowledge Exam 支持中文。中文可用于本站题库和普通练习；为避免误导，50题模拟考试只提供 English / 中英对照，并默认 English。</p></div></div></section><ToolGrid state={state}/><FloridaRules/><section className="bg-[#f4f7fb] py-10"><div className="page-shell grid gap-4 md:grid-cols-3"><div className="card p-5"><p className="text-sm font-bold text-teal-700">当前完整题库</p><p className="mt-2 text-3xl font-black">{questions.length} 题</p><p className="mt-2 text-sm text-slate-600">覆盖 Florida 道路规则、交通标志、安全驾驶和高频考试知识点。</p></div><div className="card p-5"><p className="text-sm font-bold text-teal-700">模拟考试</p><p className="mt-2 text-3xl font-black">每次 50 题</p><p className="mt-2 text-sm text-slate-600">从完整题库随机组卷，不代表全站只有50题。</p></div><div className="card p-5"><p className="text-sm font-bold text-teal-700">学习语言</p><p className="mt-2 text-xl font-black">中文 / English / 中英对照</p><p className="mt-2 text-sm text-slate-600">模拟考试仅 English / 中英对照。</p></div></div></section><OpenAACrossLinks/></> }
