export const californiaQualityEnglishById: Record<string, { question: string; choices: string[]; explanation: string }> = {
  'ca2-rules-001': { question: 'You are approaching an uncontrolled crosswalk and see a pedestrian ready to enter it. What is the best action?', choices: ['Maintain speed as long as the pedestrian has not stepped into the lane', 'Slow down and be prepared to stop and yield until the pedestrian crosses safely', 'Tap the horn to warn the pedestrian and continue'], explanation: 'Approach crosswalks carefully and give pedestrians enough space to cross safely, stopping when necessary.' },
  'ca2-rules-006': { question: 'You approach an intersection with a flashing red signal. What should you do?', choices: ['Slow down and continue through after looking', 'Come to a complete stop as at a STOP sign, then proceed when safe and you have the right-of-way', 'If no other vehicles are present, only pause briefly'], explanation: 'A flashing red signal is treated like a STOP sign: stop completely, then proceed only when safe.' },
  'ca2-rules-007': { question: 'How should you proceed at a flashing yellow traffic signal?', choices: ['Come to a complete stop and wait for the signal to change', 'Maintain speed and watch only cross traffic', 'Slow down, observe the intersection, and proceed cautiously'], explanation: 'A flashing yellow signal means slow down and proceed with caution; a complete stop is not required unless conditions demand it.' },
  'ca2-rules-011': { question: 'You just missed your freeway exit. What is the safest response?', choices: ['Continue forward, take the next exit, and reroute', 'Turn on your hazard lights and back up on the shoulder', 'Cross a solid line back toward the exit if no vehicle is behind you'], explanation: 'If you miss an exit, continue to the next one. Never back up or make a sudden unsafe lane movement.' },
  'ca2-rules-013': { question: 'What is the main goal when using a freeway acceleration lane?', choices: ['Merge as early as possible even if your speed is much lower than freeway traffic', 'Stop at the end of the lane until traffic is completely clear', 'Adjust to a speed close to the flow of traffic and find a safe gap to merge'], explanation: 'The acceleration lane is used to match freeway traffic speed and find a safe opening to merge.' },
  'ca2-rules-020': { question: 'Traffic is moving slowly and you need to cross railroad tracks, but there is not enough room for your vehicle on the far side. What should you do?', choices: ['Drive onto the tracks and wait for traffic ahead to move', 'Wait before the tracks until you can cross them completely in one movement', 'Follow the vehicle ahead closely to minimize time stopped on the tracks'], explanation: 'Do not enter railroad tracks unless you can completely clear them without stopping.' },
  'ca2-rules-021': { question: 'At a railroad crossing without gates, you see a train approaching but think you might have enough time to cross. What is the safest and correct choice?', choices: ['Stop and wait until the train has completely passed', 'Follow immediately if the vehicle ahead crosses', 'Cross if you do not hear the train horn'], explanation: 'Trains need a very long distance to stop. Never try to beat an approaching train across the tracks.' },
  'ca2-rules-022': { question: 'A school bus ahead begins flashing yellow warning lights. What does this usually mean?', choices: ['The bus is preparing to stop, so slow down and prepare to stop', 'The bus is allowing vehicles behind it to pass', 'Only oncoming traffic needs to slow down'], explanation: 'Flashing yellow lights warn that the school bus is preparing to stop for students.' },
  'ca2-rules-023': { question: 'A school bus ahead is stopped with flashing red lights. How should you decide whether you may continue?', choices: ['Drive past slowly if you do not see any students', 'Follow the applicable California school-bus stopping rule and wait until the red lights stop and it is safe', 'Proceed if a driver behind you honks'], explanation: 'Flashing red lights usually mean students may be boarding, leaving, or crossing, so obey the applicable stopping rule.' },
  'ca2-rules-028': { question: 'In a work zone, a flagger’s direction appears to conflict with temporary lane markings. What should you do first?', choices: ['Follow the flagger or traffic-control worker’s directions', 'Follow only the original pavement markings', 'Choose whichever lane looks emptiest'], explanation: 'Work-zone traffic-control personnel direct vehicles according to temporary conditions. Follow their instructions.' },
  'ca2-rules-030': { question: 'You enter dense fog and the vehicle ahead becomes difficult to see. What should you do?', choices: ['Turn on high beams and maintain speed', 'Slow down, increase following distance, and use appropriate low beams', 'Follow the taillights ahead closely so you stay in the lane'], explanation: 'In fog, reduce speed, increase following distance, and avoid high beams because reflected light can increase glare.' },
}
