import type { DmvQuestion } from './dmv-data'

export const californiaQuestions: DmvQuestion[] = [
  {
    id: 'ca-rules-001', category: 'rules',
    question: '在加州进入高速公路时，最安全的做法是什么？',
    choices: ['在加速车道尽量加速到接近主路车流速度后安全汇入', '在加速车道末端停车等待', '始终以远低于车流的速度并入'],
    answerIndex: 0,
    explanation: 'California DMV 样题强调，进入高速公路时应以达到或接近车流速度的方式安全汇入。',
  },
  {
    id: 'ca-rules-002', category: 'rules',
    question: '在加州，什么时候可以驶离铺装路面去超越前车？',
    choices: ['前车左转时可以', '任何情况下都不应为了超车驶离道路', '只有白天可以'],
    answerIndex: 1,
    explanation: 'California DMV 官方样题明确：不能通过驶离道路的方式超越另一辆车。',
  },
  {
    id: 'ca-rules-003', category: 'rules',
    question: '在加州平行停车时，通常应怎样进入路边停车位？',
    choices: ['停在车位前方车辆旁边，再倒车进入车位', '直接向前开入车位', '停在车位后方车辆旁边再向前进入'],
    answerIndex: 0,
    explanation: 'California DMV 官方样题采用先与前方车辆并排，再倒入停车位的标准平行停车方法。',
  },
  {
    id: 'ca-rules-004', category: 'rules',
    question: '在无管制铁路道口附近，如果视线受阻，驾驶人应该怎么做？',
    choices: ['保持原速快速通过', '减速并准备停车，确认没有火车后再通过', '只鸣笛即可'],
    answerIndex: 1,
    explanation: '铁路道口视线受阻时，应降低速度、观察并在必要时停车。',
  },
  {
    id: 'ca-rules-005', category: 'rules',
    question: '加州道路上看到红灯时，右转前最重要的动作是什么？',
    choices: ['先完全停车并确认允许且安全再右转', '直接慢速右转', '鸣笛后右转'],
    answerIndex: 0,
    explanation: '红灯右转并不是无条件通行；必须先完全停车，并确认没有禁止右转标志且交通安全。',
  },
  {
    id: 'ca-rules-006', category: 'rules',
    question: '红色箭头信号亮起时，应该怎么做？',
    choices: ['按箭头方向缓慢转弯', '停车，不得按箭头方向转弯，直到信号允许', '只要没有行人就可以转'],
    answerIndex: 1,
    explanation: '红色箭头表示必须停车，并等待允许该方向通行的信号。',
  },
  {
    id: 'ca-rules-007', category: 'rules',
    question: '准备左转时，对向车辆正在接近，你应该怎么做？',
    choices: ['抢在对向车前完成左转', '让有危险接近的对向车辆先行', '停在对向车道中央等待'],
    answerIndex: 1,
    explanation: '左转车辆应让对向直行车辆以及行人先行。',
  },
  {
    id: 'ca-rules-008', category: 'rules',
    question: '驶入环岛前应该优先让谁？',
    choices: ['已经在环岛中的车辆', '准备进入环岛的车辆', '环岛外右侧车辆'],
    answerIndex: 0,
    explanation: '进入环岛前应减速，并让已经在环岛内的车辆和行人先行。',
  },
  {
    id: 'ca-rules-009', category: 'rules',
    question: '道路中央有双黄实线时，通常意味着什么？',
    choices: ['可以随时跨线超车', '分隔相反方向车流，通常不得跨线超车', '道路为单行道'],
    answerIndex: 1,
    explanation: '双黄实线用于分隔相反方向交通，通常禁止跨线超车。',
  },
  {
    id: 'ca-rules-010', category: 'rules',
    question: '单条断续黄线位于你这一侧时，什么时候可以超车？',
    choices: ['任何时候', '确认前方视线和对向交通安全且法律允许时', '只有夜间'],
    answerIndex: 1,
    explanation: '断续黄线可能允许超车，但驾驶人必须先确认视线、距离和对向交通安全。',
  },
  {
    id: 'ca-rules-011', category: 'rules',
    question: '白色车道线通常分隔什么交通？',
    choices: ['同方向行驶的车流', '相反方向车流', '铁路与道路'],
    answerIndex: 0,
    explanation: '白线一般用于分隔同方向交通；黄线通常用于分隔相反方向交通。',
  },
  {
    id: 'ca-rules-012', category: 'rules',
    question: '准备变更车道时，仅看后视镜够不够？',
    choices: ['够', '不够，还应打转向灯并检查盲区', '只在高速公路上需要检查盲区'],
    answerIndex: 1,
    explanation: '车辆和摩托车可能位于后视镜看不到的盲区，变道前应转头检查。',
  },
  {
    id: 'ca-rules-013', category: 'rules',
    question: '在路口准备右转时，为什么要特别注意自行车道？',
    choices: ['自行车永远必须停车', '可能有自行车从车辆右侧直行通过', '自行车道可以当右转专用道使用'],
    answerIndex: 1,
    explanation: '右转前应观察自行车和盲区，避免与直行自行车发生冲突。',
  },
  {
    id: 'ca-rules-014', category: 'rules',
    question: '看到行人使用白手杖或导盲犬准备过街时，应该怎么做？',
    choices: ['鸣笛提醒', '停车并给予充分优先权', '从行人前方快速通过'],
    answerIndex: 1,
    explanation: '盲人行人需要特别保护，驾驶人应停车并让行。',
  },
  {
    id: 'ca-rules-015', category: 'rules',
    question: '经过学校区域时，正确做法是什么？',
    choices: ['按现场标志和儿童活动情况降低速度并提高警觉', '保持高速公路速度', '只在看到警察时减速'],
    answerIndex: 0,
    explanation: '学校区域应严格遵守现场限速标志，并随时准备为儿童和校车停车。',
  },
  {
    id: 'ca-rules-016', category: 'rules',
    question: '遇到校车闪烁红灯并停车上下学生时，驾驶人应该怎样处理？',
    choices: ['按适用道路规则停车等待', '慢速绕过校车', '鸣笛后通过'],
    answerIndex: 0,
    explanation: '校车红灯意味着学生可能正在上下车，应按加州校车规则停车等待。',
  },
  {
    id: 'ca-rules-017', category: 'rules',
    question: '遇到警车、消防车或救护车从后方接近并使用警灯警笛时，应怎么做？',
    choices: ['加速甩开', '安全靠右并停车让其通过', '停在交叉路口中央'],
    answerIndex: 1,
    explanation: '紧急车辆需要优先通行，应在安全情况下靠右停车。',
  },
  {
    id: 'ca-rules-018', category: 'rules',
    question: '进入交叉路口前发现前方交通堵塞，可能无法完全通过路口，应怎么办？',
    choices: ['进入路口等待', '留在停止线后，直到前方有足够空间', '鸣笛要求前车移动'],
    answerIndex: 1,
    explanation: '不要阻塞交叉路口，应等前方有足够空间再进入。',
  },
  {
    id: 'ca-rules-019', category: 'rules',
    question: '在坡道停车时，除了使用驻车制动，还应注意什么？',
    choices: ['根据上坡、下坡和是否有路缘正确转动车轮', '把方向盘保持完全直线即可', '关闭发动机后任何方向都一样'],
    answerIndex: 0,
    explanation: '坡道停车时应正确转动车轮，使车辆即使滑动也尽量远离交通流。',
  },
  {
    id: 'ca-rules-020', category: 'rules',
    question: '倒车离开停车位时，最安全的观察方式是什么？',
    choices: ['只看倒车影像', '转身向后观察，同时使用后视镜和摄像头辅助', '只看左侧后视镜'],
    answerIndex: 1,
    explanation: '摄像头是辅助工具，驾驶人仍应直接观察车辆后方和周围。',
  },
  {
    id: 'ca-safety-001', category: 'safety',
    question: '雨天刚开始时为什么路面可能特别滑？',
    choices: ['雨水与路面油污混合会降低抓地力', '轮胎会自动变硬', '交通信号会变慢'],
    answerIndex: 0,
    explanation: '初雨会使积在路面的油污浮起，因此应减速并增加跟车距离。',
  },
  {
    id: 'ca-safety-002', category: 'safety',
    question: '车辆发生水滑时，最合适的第一反应是什么？',
    choices: ['猛踩刹车', '逐渐松开油门并保持方向稳定', '猛打方向'],
    answerIndex: 1,
    explanation: '水滑时应避免突然制动或转向，逐步减速并恢复轮胎抓地力。',
  },
  {
    id: 'ca-safety-003', category: 'safety',
    question: '与大型卡车并排行驶时为什么不能长时间停留在其侧面？',
    choices: ['卡车驾驶人可能有较大的盲区', '卡车一定会突然停车', '法律禁止小车在卡车旁边行驶'],
    answerIndex: 0,
    explanation: '大型车辆前后和两侧存在较大盲区，应尽快安全通过或保持在其可见位置。',
  },
  {
    id: 'ca-safety-004', category: 'safety',
    question: '为什么不能突然切入大型卡车前方？',
    choices: ['大型车辆需要更长制动距离', '卡车不能使用刹车', '卡车只能在左车道行驶'],
    answerIndex: 0,
    explanation: '大型车辆更重，通常需要比小客车更长的停车距离。',
  },
  {
    id: 'ca-safety-005', category: 'safety',
    question: '摩托车与普通汽车相比，驾驶人应特别注意什么？',
    choices: ['摩托车体积小，更容易进入盲区', '摩托车不需要遵守交通法规', '摩托车总是比汽车慢'],
    answerIndex: 0,
    explanation: '摩托车轮廓小，距离和速度更难判断，变道和转弯时必须仔细检查。',
  },
  {
    id: 'ca-safety-006', category: 'safety',
    question: '驾驶时感到困倦，最安全的做法是什么？',
    choices: ['开大音乐继续开', '在安全地点停车休息', '喝水后立即高速行驶'],
    answerIndex: 1,
    explanation: '疲劳会降低反应与判断能力，真正有效的措施是停止驾驶并休息。',
  },
  {
    id: 'ca-safety-007', category: 'safety',
    question: '服用可能引起嗜睡的药物后，应该怎么做？',
    choices: ['只要是处方药就可以驾驶', '确认药物影响和警告，可能影响驾驶时不要开车', '只在白天可以驾驶'],
    answerIndex: 1,
    explanation: '处方药和非处方药都可能影响安全驾驶，应阅读警告并遵循医生或药师建议。',
  },
  {
    id: 'ca-safety-008', category: 'safety',
    question: '酒后感觉自己“很清醒”，是否就适合驾驶？',
    choices: ['是', '不是，酒精仍可能损害判断、协调和反应', '只有夜间不适合'],
    answerIndex: 1,
    explanation: '主观感觉不能可靠判断驾驶能力，酒精会降低多项驾驶能力。',
  },
  {
    id: 'ca-safety-009', category: 'safety',
    question: '发生爆胎时，应该怎样控制车辆？',
    choices: ['立即猛踩刹车', '稳住方向盘，逐渐松油门并在安全处停车', '迅速向路肩猛打方向'],
    answerIndex: 1,
    explanation: '爆胎时保持车辆稳定最重要，避免急刹和突然转向。',
  },
  {
    id: 'ca-safety-010', category: 'safety',
    question: '刹车突然失效时，首先应考虑什么？',
    choices: ['继续加速', '尝试降低挡位、使用适当制动方式并寻找安全停车区域', '立即关闭方向盘锁'],
    answerIndex: 1,
    explanation: '应尽量降低车速、保持方向控制，并寻找安全区域停车。',
  },
  {
    id: 'ca-safety-011', category: 'safety',
    question: '前方车辆遮挡视线时，为什么要增加跟车距离？',
    choices: ['为了让后车超车', '为了获得更多观察和反应时间', '为了节省油'],
    answerIndex: 1,
    explanation: '视线越受限制，越需要更多空间来发现危险并安全停车。',
  },
  {
    id: 'ca-safety-012', category: 'safety',
    question: '夜间驾驶时应怎样调整速度？',
    choices: ['速度应保证能在车灯照明范围内安全停车', '必须比白天更快', '只要开远光灯就无需调整速度'],
    answerIndex: 0,
    explanation: '夜间可见距离有限，应控制速度，使停车距离不超过可见范围。',
  },
  {
    id: 'ca-safety-013', category: 'safety',
    question: '接近对向车辆时，应怎样使用远光灯？',
    choices: ['一直保持远光灯', '及时切换为近光灯，避免影响对方视线', '快速闪灯直到对方停车'],
    answerIndex: 1,
    explanation: '强光会使对向驾驶人眩目，应按规定切换到近光灯。',
  },
  {
    id: 'ca-safety-014', category: 'safety',
    question: '雾天最合适的车灯通常是什么？',
    choices: ['近光灯', '远光灯', '只开日间行车灯'],
    answerIndex: 0,
    explanation: '远光灯会被雾反射并加剧眩光，雾天通常应使用近光灯。',
  },
  {
    id: 'ca-safety-015', category: 'safety',
    question: '车辆开始打滑时，最应该避免什么？',
    choices: ['平稳修正方向', '突然猛刹或猛打方向', '看向希望车辆前进的方向'],
    answerIndex: 1,
    explanation: '突然操作会加重失控，应保持冷静并平稳恢复车辆控制。',
  },
  {
    id: 'ca-signs-001', category: 'signs',
    question: '红色八角形标志表示什么？',
    choices: ['STOP 停止', 'YIELD 让行', '禁止停车'],
    answerIndex: 0,
    explanation: '八角形红色标志只用于 STOP，驾驶人必须完全停车。',
  },
  {
    id: 'ca-signs-002', category: 'signs',
    question: '倒三角形红白标志表示什么？',
    choices: ['让路', '停车', '单行道'],
    answerIndex: 0,
    explanation: '倒三角形是 YIELD，让有优先权的交通先行。',
  },
  {
    id: 'ca-signs-003', category: 'signs',
    question: '黄色菱形标志通常用于什么？',
    choices: ['警告前方道路或交通状况变化', '停车收费', '车辆登记'],
    answerIndex: 0,
    explanation: '黄色菱形一般是警告标志，如弯道、交叉路口、合流等。',
  },
  {
    id: 'ca-signs-004', category: 'signs',
    question: '橙色菱形标志通常意味着什么？',
    choices: ['施工或维护区域警告', '医院', '学校'],
    answerIndex: 0,
    explanation: '橙色用于施工和临时交通控制信息。',
  },
  {
    id: 'ca-signs-005', category: 'signs',
    question: '五边形学校标志通常提醒什么？',
    choices: ['学校区域或学生过街', '高速公路入口', '铁路道口'],
    answerIndex: 0,
    explanation: '学校区域常用五边形标志提醒驾驶人注意儿童和过街活动。',
  },
  {
    id: 'ca-signs-006', category: 'signs',
    question: '圆形黄色铁路预告标志表示什么？',
    choices: ['前方有铁路道口', '前方有环岛', '禁止掉头'],
    answerIndex: 0,
    explanation: '圆形铁路警告标志提示驾驶人前方接近铁路交叉口。',
  },
  {
    id: 'ca-signs-007', category: 'signs',
    question: '白底黑字的矩形限速标志属于哪类？',
    choices: ['法规标志', '旅游标志', '施工标志'],
    answerIndex: 0,
    explanation: '白底黑字的速度限制属于法规性交通标志。',
  },
  {
    id: 'ca-signs-008', category: 'signs',
    question: '绿色道路标志通常提供什么？',
    choices: ['方向、出口和距离信息', '危险警告', '停车禁令'],
    answerIndex: 0,
    explanation: '绿色常用于路线、目的地、出口和距离指引。',
  },
  {
    id: 'ca-signs-009', category: 'signs',
    question: '蓝色道路标志通常提供什么？',
    choices: ['服务设施信息', '道路施工信息', '停止命令'],
    answerIndex: 0,
    explanation: '蓝色常用于医院、加油、餐饮、休息区等驾驶服务信息。',
  },
  {
    id: 'ca-signs-010', category: 'signs',
    question: '棕色道路标志通常与什么有关？',
    choices: ['休闲、历史或文化景点', '限速', '铁路道口'],
    answerIndex: 0,
    explanation: '棕色标志通常指向公园、休闲设施、历史或文化地点。',
  },
  {
    id: 'ca-documents-001', category: 'documents',
    question: '申请加州 instruction permit 前，最可靠的要求来源是什么？',
    choices: ['California DMV 官方申请页面', '社交媒体评论', '朋友几年前的经验'],
    answerIndex: 0,
    explanation: '证件、费用和流程可能更新，应以 California DMV 官方页面为准。',
  },
  {
    id: 'ca-documents-002', category: 'documents',
    question: 'California Driver’s Handbook 是否有中文版本？',
    choices: ['有，California DMV 官方提供中文 PDF', '没有任何中文资料', '只有商业驾照有中文版本'],
    answerIndex: 0,
    explanation: 'California DMV 的 Driver’s Handbooks 页面提供 California Driver’s Handbook 中文 PDF。',
  },
  {
    id: 'ca-documents-003', category: 'documents',
    question: '准备加州知识考试，最重要的官方学习资料是什么？',
    choices: ['California Driver’s Handbook', '二手车广告', '地图应用评论'],
    answerIndex: 0,
    explanation: 'California DMV 官方明确建议知识考试前阅读 California Driver’s Handbook。',
  },
  {
    id: 'ca-documents-004', category: 'documents',
    question: '加州 DMV 是否提供官方 Class C 样题？',
    choices: ['提供，包括中文样题页面', '完全不提供', '只提供摩托车题'],
    answerIndex: 0,
    explanation: 'California DMV 官方 Sample Driver’s License Knowledge Tests 页面提供多套 Class C 样题，并有中文版本。',
  },
  {
    id: 'ca-documents-005', category: 'documents',
    question: '未满 18 岁申请加州 instruction permit，年龄要求之一是什么？',
    choices: ['至少 15 岁半', '至少 14 岁', '必须满 18 岁'],
    answerIndex: 0,
    explanation: 'California Driver’s Handbook 说明，未满 18 岁申请人须至少 15½ 岁，并满足额外的驾驶教育等要求。',
  },
]
