import type { DmvQuestion } from './dmv-data'

// 加州专属扩展题。题目依据 California DMV Driver's Handbook 与官方 Class C 样题覆盖范围改写，
// 用于学习辅助，不复制官方题目原文；正式考试与最新规则以 California DMV 为准。
export const californiaExpandedQuestions: DmvQuestion[] = [
  { id: 'ca2-rules-001', category: 'rules', question: '接近没有信号灯的人行横道时，看到行人准备过街，应该怎么做？', choices: ['减速并准备让行', '加速抢先通过', '鸣笛要求行人等待'], answerIndex: 0, explanation: '加州驾驶规则要求驾驶人对行人保持高度警觉，并在需要时减速或停车让其安全通过。' },
  { id: 'ca2-rules-002', category: 'rules', question: '前车在人行横道前停车时，后车最安全的做法是什么？', choices: ['从旁边直接超车', '也停车并确认是否有行人', '鸣笛让前车走'], answerIndex: 1, explanation: '前车可能是在给行人让路，不应贸然从旁边超越。' },
  { id: 'ca2-rules-003', category: 'rules', question: '在加州道路上准备左转时，除了看对向车辆，还应重点观察什么？', choices: ['行人与自行车', '只有路牌颜色', '只有后车'], answerIndex: 0, explanation: '左转时应同时确认对向交通、行人和自行车是否安全。' },
  { id: 'ca2-rules-004', category: 'rules', question: '驶近黄色信号灯时，正确理解是什么？', choices: ['红灯即将出现，应在能安全停车时停车', '一定要加速通过', '可以忽略'], answerIndex: 0, explanation: '黄灯表示信号即将变红，驾驶人应根据距离和安全条件决定是否停车。' },
  { id: 'ca2-rules-005', category: 'rules', question: '绿灯亮起后马上起步前，为什么仍要观察路口？', choices: ['可能仍有行人或车辆尚未清空路口', '绿灯后无需观察', '只需要看后视镜'], answerIndex: 0, explanation: '拥有通行信号并不代表路口一定完全无风险。' },
  { id: 'ca2-rules-006', category: 'rules', question: '遇到闪烁红灯时，应当怎样处理？', choices: ['像 STOP 标志一样完全停车后再安全通行', '直接通过', '只减速不停车'], answerIndex: 0, explanation: '闪烁红灯通常按停车标志处理。' },
  { id: 'ca2-rules-007', category: 'rules', question: '遇到闪烁黄灯时，正确做法是什么？', choices: ['减速并谨慎通过', '必须原地等待到变绿', '加速通过'], answerIndex: 0, explanation: '闪黄灯表示需要减速、提高警觉并谨慎通行。' },
  { id: 'ca2-rules-008', category: 'rules', question: '四向 STOP 路口，你比其他车辆先到并完全停车，通常谁先走？', choices: ['你在确认安全后先行', '最后到的车先走', '体积最大的车先走'], answerIndex: 0, explanation: '一般遵循先到先行；同时到达时再结合让右原则判断。' },
  { id: 'ca2-rules-009', category: 'rules', question: '两辆车几乎同时到达四向 STOP 路口时，通常应让谁先行？', choices: ['右侧车辆', '左侧车辆', '速度快的车辆'], answerIndex: 0, explanation: '同时到达时通常让右侧车辆先行。' },
  { id: 'ca2-rules-010', category: 'rules', question: '进入主路前有 YIELD 标志时，你应该怎样做？', choices: ['减速并让有优先权的交通先行', '必须无条件停车很久', '直接并入'], answerIndex: 0, explanation: 'YIELD 要求减速并在必要时停车，让有优先权的交通先行。' },
  { id: 'ca2-rules-011', category: 'rules', question: '在加州高速公路上错过出口后，最安全做法是什么？', choices: ['继续到下一个出口', '倒车回出口', '立即横跨多条车道'], answerIndex: 0, explanation: '错过出口后应继续前行，避免倒车或突然跨越车道。' },
  { id: 'ca2-rules-012', category: 'rules', question: '高速公路出口前应什么时候开始变道？', choices: ['提前观察、打灯并逐步进入合适车道', '到出口口才突然变道', '停车后再变道'], answerIndex: 0, explanation: '提前规划车道能减少突然变线造成的风险。' },
  { id: 'ca2-rules-013', category: 'rules', question: '进入高速公路时，加速车道的主要作用是什么？', choices: ['把速度调整到接近主车流并寻找安全空隙', '停车等待绿灯', '低速慢慢挤入'], answerIndex: 0, explanation: '加速车道用于匹配车流速度并寻找安全汇入机会。' },
  { id: 'ca2-rules-014', category: 'rules', question: '高速公路上有人紧跟你的车，较安全的处理方式是什么？', choices: ['条件允许时变到右侧车道让其通过', '突然急刹', '加速与其竞驶'], answerIndex: 0, explanation: '避免与尾随车辆对抗，可在安全时让行并增加前方缓冲空间。' },
  { id: 'ca2-rules-015', category: 'rules', question: '在多车道道路上，如果你明显比其他车辆慢，通常应在哪侧行驶？', choices: ['较右侧车道', '最左侧车道', '任意占用快车道'], answerIndex: 0, explanation: '较慢车辆通常应靠右行驶，以减少阻碍正常交通流。' },
  { id: 'ca2-rules-016', category: 'rules', question: '准备超越自行车时，首先应该做什么？', choices: ['确认对向和侧方空间足够并安全通过', '贴近自行车快速通过', '持续鸣笛逼其靠边'], answerIndex: 0, explanation: '超越自行车应预留足够横向空间并确认前方与对向交通安全。' },
  { id: 'ca2-rules-017', category: 'rules', question: '右转前需要穿过自行车道时，应该怎么做？', choices: ['先检查自行车并在合法位置安全并入后转弯', '完全无视自行车道', '高速切入'], answerIndex: 0, explanation: '右转前要特别检查自行车，避免与直行骑行者冲突。' },
  { id: 'ca2-rules-018', category: 'rules', question: '看到自行车骑行者在车道内行驶时，应该怎样理解？', choices: ['自行车在许多情况下有权使用道路', '自行车永远不能在车道内', '汽车可以强行挤过'], answerIndex: 0, explanation: '驾驶人应把自行车视作道路使用者并安全共享道路。' },
  { id: 'ca2-rules-019', category: 'rules', question: '遇到轻轨车辆时，为什么要特别谨慎？', choices: ['轻轨不能快速转向避开汽车', '轻轨可以随时倒车', '轻轨没有路权'], answerIndex: 0, explanation: '轻轨受轨道限制，驾驶人必须避免抢行和停在轨道上。' },
  { id: 'ca2-rules-020', category: 'rules', question: '交通拥堵时，前方没有足够空间完全越过铁路轨道，应该怎么办？', choices: ['在轨道前等待', '开到轨道上等待', '跟着前车挤过去'], answerIndex: 0, explanation: '绝不能把车辆停在铁路轨道上，应等对面有足够空间再通过。' },
  { id: 'ca2-rules-021', category: 'rules', question: '没有闸门的铁路道口，看到火车接近时应怎样做？', choices: ['停车等待火车通过', '抢先通过', '只鸣笛即可'], answerIndex: 0, explanation: '火车无法快速停车，发现火车接近必须等待。' },
  { id: 'ca2-rules-022', category: 'rules', question: '学校附近看到校车黄灯闪烁时，通常意味着什么？', choices: ['校车准备停车，应减速并准备停车', '可以立即超车', '校车发生机械故障'], answerIndex: 0, explanation: '黄灯表示校车即将停车上下学生，驾驶人应降低速度并做好停车准备。' },
  { id: 'ca2-rules-023', category: 'rules', question: '校车红灯闪烁时，最重要的原则是什么？', choices: ['按加州规则停车等待，直到安全并且红灯停止', '从右侧慢慢绕过', '鸣笛后通过'], answerIndex: 0, explanation: '红灯表示学生正在上下车或过街，必须遵守校车停车规则。' },
  { id: 'ca2-rules-024', category: 'rules', question: '在学校附近儿童出现时，应如何控制车速？', choices: ['遵守学校区域限速并准备随时停车', '保持高速公路车速', '只看后车速度'], answerIndex: 0, explanation: '学校区域需要更低速度和更高警觉。' },
  { id: 'ca2-rules-025', category: 'rules', question: '在有儿童活动的学校附近，加州常见学校区域限速是多少？', choices: ['25 mph，部分区域可能更低', '55 mph', '65 mph'], answerIndex: 0, explanation: 'California DMV 手册说明，在学校 500 英尺范围且儿童在外或过街时，通常为 25 mph，部分区域可低至 15 mph。' },
  { id: 'ca2-rules-026', category: 'rules', question: '在安全区旁停靠的公交或有轨电车附近通行时，应怎样做？', choices: ['低速谨慎通过并注意行人', '高速通过', '驶入安全区'], answerIndex: 0, explanation: '公交与有轨电车停靠区域常有行人上下车，应严格减速并观察。' },
  { id: 'ca2-rules-027', category: 'rules', question: '加州道路上的“安全区”主要给谁使用？', choices: ['等待公交、有轨电车的行人', '超车车辆', '大型卡车'], answerIndex: 0, explanation: '安全区是为等待公共交通的行人设置的区域，车辆不得随意驶入。' },
  { id: 'ca2-rules-028', category: 'rules', question: '看到道路施工人员或旗手指挥交通时，应怎样做？', choices: ['服从其指示并降低速度', '只听交通信号不听人员', '快速绕开'], answerIndex: 0, explanation: '施工区人员的交通指挥关系到现场安全，应严格遵守。' },
  { id: 'ca2-rules-029', category: 'rules', question: '施工区车道变窄时，应该怎么做？', choices: ['提前观察标志并平稳合流', '突然抢道', '停在车道中间'], answerIndex: 0, explanation: '施工区应提前减速、观察临时标志并平稳合流。' },
  { id: 'ca2-rules-030', category: 'rules', question: '进入雾区时，最合适的驾驶方式是什么？', choices: ['减速并使用合适灯光', '开启远光灯高速行驶', '紧跟前车'], answerIndex: 0, explanation: '雾天能见度差，应减速、扩大跟车距离并使用合适灯光。' },
  { id: 'ca2-rules-031', category: 'rules', question: '夜间会车时，为什么要适时切换近光灯？', choices: ['避免眩目对向驾驶人', '让自己更快', '减少油耗'], answerIndex: 0, explanation: '远光灯可能使对向驾驶人短暂失去清晰视野。' },
  { id: 'ca2-rules-032', category: 'rules', question: '夜间跟车过近并开远光灯有什么问题？', choices: ['可能通过后视镜使前车驾驶人眩目', '可以提醒前车加速', '完全没有影响'], answerIndex: 0, explanation: '跟车时应避免远光灯影响前车驾驶人的视线。' },
  { id: 'ca2-rules-033', category: 'rules', question: '准备从路边停车位驶入车流时，应该先做什么？', choices: ['打灯并检查镜子、盲区和来车', '直接驶出', '只看前方'], answerIndex: 0, explanation: '从停车位驶出也属于并入交通，需要观察并让正常车流先行。' },
  { id: 'ca2-rules-034', category: 'rules', question: '在山路狭窄道路上会车时，最重要的是什么？', choices: ['控制速度并给对方留出安全空间', '抢占道路中央', '关闭灯光'], answerIndex: 0, explanation: '山路视野和路宽有限，应降低速度并避免占用对向车道。' },
  { id: 'ca2-rules-035', category: 'rules', question: '下长坡时只靠持续踩刹车有什么风险？', choices: ['刹车可能过热、制动效果下降', '轮胎会自动充气', '方向盘会变轻'], answerIndex: 0, explanation: '长下坡应合理利用低挡等方式控制速度，避免刹车持续过热。' },
  { id: 'ca2-rules-036', category: 'rules', question: '准备 U-turn 前最重要的判断是什么？', choices: ['该地点是否合法且视线、交通条件足够安全', '只要方向盘能打满就行', '后车是否鸣笛'], answerIndex: 0, explanation: '掉头受地点、标志、视距和交通情况限制，必须先确认合法与安全。' },
  { id: 'ca2-rules-037', category: 'rules', question: '在消防站出入口附近停车时，为什么要特别留意限制？', choices: ['必须保持紧急车辆出入口畅通', '消防车不会使用该出口', '那里通常允许长期停车'], answerIndex: 0, explanation: '消防和其他紧急车辆出入口必须保持畅通。' },
  { id: 'ca2-rules-038', category: 'rules', question: '看到路面上写有 ONLY 的转向车道，应怎样使用？', choices: ['按照箭头或标线指定方向行驶', '可以任意直行', '可以停车休息'], answerIndex: 0, explanation: '专用转向车道必须按照车道箭头和标志使用。' },
  { id: 'ca2-rules-039', category: 'rules', question: '双白实线通常说明什么？', choices: ['不应跨越或变道穿过', '可以随时变道', '表示双向交通'], answerIndex: 0, explanation: '双白实线常用于限制同方向车道之间的变道。' },
  { id: 'ca2-rules-040', category: 'rules', question: '中央左转车道的主要用途是什么？', choices: ['供车辆准备左转使用，而不是长距离行驶', '作为高速超车道', '作为停车区'], answerIndex: 0, explanation: '中央左转车道用于短距离进入并完成左转，不应作为普通行驶车道。' },

  { id: 'ca2-safety-001', category: 'safety', question: '驾驶中最有效的防御性驾驶习惯是什么？', choices: ['不断扫描前方、侧方和后方交通', '只盯着前车', '只看导航'], answerIndex: 0, explanation: '持续扫描能更早发现风险并留出反应时间。' },
  { id: 'ca2-safety-002', category: 'safety', question: '跟车距离过近最主要的危险是什么？', choices: ['前车急停时没有足够反应和制动空间', '会增加油箱容量', '会让红灯变快'], answerIndex: 0, explanation: '安全跟车距离是避免追尾的重要缓冲。' },
  { id: 'ca2-safety-003', category: 'safety', question: '雨天为什么应增加跟车距离？', choices: ['湿滑路面会增加停车距离', '雨天车辆一定更快', '雨天不需要刹车'], answerIndex: 0, explanation: '湿滑路面抓地力下降，制动距离通常会变长。' },
  { id: 'ca2-safety-004', category: 'safety', question: '轮胎花纹严重磨损会增加什么风险？', choices: ['湿滑路面失去抓地力和水滑风险', '发动机过热', '方向灯失灵'], answerIndex: 0, explanation: '轮胎状态直接影响制动和湿地抓地力。' },
  { id: 'ca2-safety-005', category: 'safety', question: '如果车辆开始水滑，为什么不应猛踩刹车？', choices: ['可能进一步失去控制', '会让雨停下来', '会自动关闭发动机'], answerIndex: 0, explanation: '水滑时应平稳减速并避免突然操作。' },
  { id: 'ca2-safety-006', category: 'safety', question: '车辆爆胎时，第一反应应该是什么？', choices: ['稳住方向盘并逐渐减速', '猛打方向靠边', '立即猛踩刹车'], answerIndex: 0, explanation: '爆胎时突然转向或急刹容易使车辆失控。' },
  { id: 'ca2-safety-007', category: 'safety', question: '刹车失灵时，驾驶人应优先做什么？', choices: ['保持控制、尝试降挡和安全减速并寻找停车位置', '关闭方向控制', '高速冲向路肩'], answerIndex: 0, explanation: '制动故障时应保持冷静，逐步降低速度并寻找安全位置。' },
  { id: 'ca2-safety-008', category: 'safety', question: '车辆发生侧滑时，最危险的动作是什么？', choices: ['突然猛刹和猛打方向', '平稳修正方向', '松开油门'], answerIndex: 0, explanation: '突然操作会使侧滑进一步恶化。' },
  { id: 'ca2-safety-009', category: 'safety', question: '驾驶人情绪非常愤怒时继续开车有什么风险？', choices: ['判断和决策可能变差', '反应一定更快', '视力自动增强'], answerIndex: 0, explanation: '强烈情绪会影响判断、耐心和风险控制。' },
  { id: 'ca2-safety-010', category: 'safety', question: '疲劳驾驶最可靠的解决办法是什么？', choices: ['安全停车并休息', '把音乐调大', '打开车窗继续开'], answerIndex: 0, explanation: '疲劳会显著降低注意力，真正有效的方法是休息。' },
  { id: 'ca2-safety-011', category: 'safety', question: '驾驶中查看手机消息为什么危险？', choices: ['会分散视觉、手部和认知注意力', '只会影响手机电量', '只在夜间危险'], answerIndex: 0, explanation: '分心驾驶会大幅减少对道路变化的反应时间。' },
  { id: 'ca2-safety-012', category: 'safety', question: '需要操作导航时，较安全的做法是什么？', choices: ['出发前设置或在安全停车后操作', '高速行驶中长时间输入', '低头边开边输'], answerIndex: 0, explanation: '减少驾驶中的手动操作可以降低分心风险。' },
  { id: 'ca2-safety-013', category: 'safety', question: '酒精会如何影响驾驶？', choices: ['降低判断、协调和反应能力', '提高夜间视力', '只影响新手'], answerIndex: 0, explanation: '酒精会损害多项安全驾驶能力。' },
  { id: 'ca2-safety-014', category: 'safety', question: '服用可能引起嗜睡的药物后准备开车，应该怎么做？', choices: ['先确认药物警示并避免在受影响时驾驶', '喝咖啡就一定安全', '只要白天就没问题'], answerIndex: 0, explanation: '处方药和非处方药都可能影响反应能力，应遵守药品警示。' },
  { id: 'ca2-safety-015', category: 'safety', question: '大型卡车右转时，为什么不要从它右侧挤过去？', choices: ['卡车可能需要较大转弯空间且存在盲区', '卡车一定会停车', '右侧永远是停车区'], answerIndex: 0, explanation: '大型车辆转弯半径大，右侧区域可能进入其转弯路径。' },
  { id: 'ca2-safety-016', category: 'safety', question: '跟在大型卡车后面时，应该比跟小客车怎样？', choices: ['留更大的跟车距离', '贴得更近', '保持一个车身长度'], answerIndex: 0, explanation: '较大的距离可改善视野，也为卡车可能的制动和道路情况留出空间。' },
  { id: 'ca2-safety-017', category: 'safety', question: '为什么不要长时间处于卡车侧方盲区？', choices: ['卡车驾驶人可能看不到你', '会影响你的收音机', '卡车不能转弯'], answerIndex: 0, explanation: '大型车辆盲区较大，驾驶人应尽量处于其可见位置。' },
  { id: 'ca2-safety-018', category: 'safety', question: '摩托车突然减速时为什么可能不易察觉？', choices: ['摩托车有时通过降挡减速，刹车灯未必明显提示', '摩托车没有刹车', '摩托车只能高速行驶'], answerIndex: 0, explanation: '与摩托车保持足够距离可以给自己更多反应时间。' },
  { id: 'ca2-safety-019', category: 'safety', question: '与摩托车共享车道是否合适？', choices: ['不合适，应给摩托车完整车道空间', '任何时候都可以并排', '只有夜间可以'], answerIndex: 0, explanation: '摩托车需要完整车道空间来避让路面危险。' },
  { id: 'ca2-safety-020', category: 'safety', question: '遇到骑自行车的人绕过停放车辆时，应该怎样做？', choices: ['预留空间并准备其向车道内移动', '贴近通过', '持续鸣笛'], answerIndex: 0, explanation: '骑行者可能为避开车门或障碍而进入车道。' },
  { id: 'ca2-safety-021', category: 'safety', question: '路边停放车辆旁骑行者最担心的危险之一是什么？', choices: ['车门突然打开', '车辆颜色', '路牌字体'], answerIndex: 0, explanation: '驾驶人与乘客开门前也应检查自行车和其他交通。' },
  { id: 'ca2-safety-022', category: 'safety', question: '看到儿童靠近街边玩耍时，应如何驾驶？', choices: ['减速并准备随时停车', '保持原速', '鸣笛后加速'], answerIndex: 0, explanation: '儿童行为可能突然变化，应提前降低速度并扩大安全余量。' },
  { id: 'ca2-safety-023', category: 'safety', question: '看到动物进入道路时，最安全的原则是什么？', choices: ['控制车速并避免突然危险转向', '猛打方向进入对向车道', '闭眼急刹'], answerIndex: 0, explanation: '应优先保持车辆可控，避免为躲避动物引发更严重碰撞。' },
  { id: 'ca2-safety-024', category: 'safety', question: '发生轻微碰撞后，把车停在危险车道中央是否理想？', choices: ['不理想，应在法律和安全允许时减少对交通的危险', '必须永远停在原车道', '应立即离开现场不交换信息'], answerIndex: 0, explanation: '事故现场首先要防止二次碰撞，同时依法完成停车、信息交换和报告义务。' },
  { id: 'ca2-safety-025', category: 'safety', question: '夜间驾驶时车速为什么要与可视距离匹配？', choices: ['必须能在看得见的范围内留出反应与停车空间', '夜间可以更快', '路灯会自动控制车辆'], answerIndex: 0, explanation: '夜间可视距离缩短，过快会造成来不及处理障碍。' },
  { id: 'ca2-safety-026', category: 'safety', question: '太阳低角度直射造成眩光时，应该怎么做？', choices: ['减速、使用遮阳板并保持更大距离', '闭眼几秒', '立即加速'], answerIndex: 0, explanation: '眩光会暂时降低视野，应增加安全余量。' },
  { id: 'ca2-safety-027', category: 'safety', question: '在拥堵车流中频繁变道通常有什么问题？', choices: ['增加碰撞风险且未必明显更快', '一定节省大量时间', '能改善所有车辆通行'], answerIndex: 0, explanation: '稳定、可预测的驾驶通常更安全。' },
  { id: 'ca2-safety-028', category: 'safety', question: '后视镜调好以后，为什么仍需要转头检查盲区？', choices: ['镜子无法覆盖所有区域', '后视镜只在停车时有用', '转头只是考试动作'], answerIndex: 0, explanation: '车辆、摩托车或自行车可能位于镜子覆盖不到的位置。' },

  { id: 'ca2-signs-001', category: 'signs', question: '八角形红色标志表示什么？', choices: ['STOP，必须完全停车', 'YIELD', '限速'], answerIndex: 0, explanation: '八角形红色标志专门表示 STOP。' },
  { id: 'ca2-signs-002', category: 'signs', question: '倒三角红白标志表示什么？', choices: ['让路', '停车', '施工'], answerIndex: 0, explanation: '倒三角形是 YIELD，让有优先权的交通先行。' },
  { id: 'ca2-signs-003', category: 'signs', question: '黄色菱形标志通常属于哪一类？', choices: ['警告标志', '停车许可', '服务设施'], answerIndex: 0, explanation: '黄色菱形通常提示前方弯道、路口、行人等潜在危险。' },
  { id: 'ca2-signs-004', category: 'signs', question: '橙色菱形标志最常见于什么区域？', choices: ['道路施工或维护区域', '医院区', '停车场'], answerIndex: 0, explanation: '橙色通常用于临时施工和道路作业警告。' },
  { id: 'ca2-signs-005', category: 'signs', question: '白底黑字矩形标志通常表示什么？', choices: ['法规或限制', '景点', '施工'], answerIndex: 0, explanation: '例如限速、转向限制等通常属于法规标志。' },
  { id: 'ca2-signs-006', category: 'signs', question: '绿色道路标志通常提供什么？', choices: ['方向、出口和距离信息', '禁止行为', '施工警告'], answerIndex: 0, explanation: '绿色标志常用于导航和目的地信息。' },
  { id: 'ca2-signs-007', category: 'signs', question: '蓝色道路标志通常提供什么？', choices: ['驾驶人服务设施信息', '铁路警告', '禁止停车'], answerIndex: 0, explanation: '蓝色常用于医院、加油、休息区等服务信息。' },
  { id: 'ca2-signs-008', category: 'signs', question: '棕色道路标志通常与什么有关？', choices: ['休闲、历史或文化地点', '限速', '施工'], answerIndex: 0, explanation: '棕色常用于公园、历史景点和休闲区域。' },
  { id: 'ca2-signs-009', category: 'signs', question: '五边形黄色标志通常提醒什么？', choices: ['学校或学童区域', '医院', '铁路'], answerIndex: 0, explanation: '学校区域常使用五边形警告标志。' },
  { id: 'ca2-signs-010', category: 'signs', question: '圆形黄色铁路预警标志表示什么？', choices: ['前方铁路道口', '前方加油站', '前方禁止掉头'], answerIndex: 0, explanation: '圆形铁路预警标志提醒驾驶人提前减速观察。' },
  { id: 'ca2-signs-011', category: 'signs', question: '铁路道口的交叉形 Crossbuck 标志提醒什么？', choices: ['注意火车并按规定让行', '高速通过', '只能左转'], answerIndex: 0, explanation: 'Crossbuck 用于标识铁路平交道。' },
  { id: 'ca2-signs-012', category: 'signs', question: '红色路缘通常表示什么？', choices: ['禁止停车或停靠', '短时上下客', '装卸区'], answerIndex: 0, explanation: '红色路缘一般表示禁止停车、停靠或泊车。' },
  { id: 'ca2-signs-013', category: 'signs', question: '白色路缘通常与什么用途有关？', choices: ['按当地标志规定短时上下乘客', '长期停车', '货车长期装卸'], answerIndex: 0, explanation: '白色路缘常用于短时上下客，具体以现场标志为准。' },
  { id: 'ca2-signs-014', category: 'signs', question: '蓝色路缘停车位通常保留给谁？', choices: ['持有效残障停车许可的人员', '任何车辆', '出租车'], answerIndex: 0, explanation: '蓝色路缘或标识通常用于残障人士专用停车。' },
  { id: 'ca2-signs-015', category: 'signs', question: '道路上白色箭头配合 ONLY 文字意味着什么？', choices: ['该车道必须按箭头指定方向行驶', '可以任意方向', '只能停车'], answerIndex: 0, explanation: '车道箭头和 ONLY 表示专用行驶方向。' },
  { id: 'ca2-signs-016', category: 'signs', question: '黄色实线和黄色虚线主要用于区分什么？', choices: ['相反方向车流及是否允许在安全条件下超车', '停车区域颜色', '公交线路'], answerIndex: 0, explanation: '黄线通常分隔相反方向车流，线型决定某些超车限制。' },
  { id: 'ca2-signs-017', category: 'signs', question: '道路中央两组相隔较宽的双黄线通常表示什么？', choices: ['视作道路分隔带或障碍，不应跨越', '普通可变车道', '自行车道'], answerIndex: 0, explanation: 'California DMV 样题涉及两组相隔较宽双黄线，应视作分隔障碍。' },
  { id: 'ca2-signs-018', category: 'signs', question: '“DO NOT ENTER” 标志表示什么？', choices: ['不得从该方向进入', '前方可掉头', '可以停车'], answerIndex: 0, explanation: '该标志用于阻止车辆从错误方向进入道路或坡道。' },
  { id: 'ca2-signs-019', category: 'signs', question: '“WRONG WAY” 标志出现时最可能说明什么？', choices: ['你可能正朝错误方向行驶', '前方是休息区', '前方学校'], answerIndex: 0, explanation: '看到 WRONG WAY 应立即安全纠正方向，避免逆行。' },
  { id: 'ca2-signs-020', category: 'signs', question: '弯道警告标志出现时，应该怎么做？', choices: ['提前降低到适合弯道和现场条件的速度', '到弯道中间再急刹', '加速进入'], answerIndex: 0, explanation: '警告标志帮助驾驶人提前调整车速和位置。' },

  { id: 'ca2-documents-001', category: 'documents', question: '准备加州知识考试时，最权威的学习资料是什么？', choices: ['California Driver’s Handbook 与 California DMV 官方资料', '论坛留言', '短视频评论'], answerIndex: 0, explanation: 'California DMV 官方明确建议考生阅读 Driver’s Handbook。' },
  { id: 'ca2-documents-002', category: 'documents', question: 'California DMV 是否提供中文 Driver’s Handbook？', choices: ['提供中文 PDF', '完全没有', '只提供西班牙语'], answerIndex: 0, explanation: 'California DMV Driver’s Handbooks 页面列有中文版本。' },
  { id: 'ca2-documents-003', category: 'documents', question: 'California DMV 是否提供中文 Class C 知识考试样题？', choices: ['提供多套中文样题', '不提供任何样题', '只提供商业驾照样题'], answerIndex: 0, explanation: 'California DMV 官方 Sample Tests 页面提供中文 Class C 样题。' },
  { id: 'ca2-documents-004', category: 'documents', question: '如果本站练习题与 California DMV 官方手册不一致，应以哪个为准？', choices: ['California DMV 官方资料', '本站练习题', '朋友经验'], answerIndex: 0, explanation: '本站是学习辅助，正式规则必须以官方最新资料为准。' },
  { id: 'ca2-documents-005', category: 'documents', question: '申请 instruction permit 前为什么要重新核对 DMV 官方页面？', choices: ['证件、费用和流程可能更新', '因为练习题会自动失效', '因为驾照每天都要换'], answerIndex: 0, explanation: '申请要求可能更新，办理前应检查最新官方要求。' },
  { id: 'ca2-documents-006', category: 'documents', question: '知识考试主要用于确认申请人理解什么？', choices: ['交通法规与安全驾驶知识', '车辆售价', '保险公司排名'], answerIndex: 0, explanation: '知识考试重点是道路规则、标志与安全驾驶。' },
  { id: 'ca2-documents-007', category: 'documents', question: '第一次申请驾照时，是否应只准备考试而忽略身份证明材料？', choices: ['不应，考试和申请材料都要按官方要求准备', '可以完全忽略材料', '只带银行卡即可'], answerIndex: 0, explanation: '驾照申请不仅包括考试，还包括身份、居住等申请要求。' },
  { id: 'ca2-documents-008', category: 'documents', question: '参加路考前，为什么要确认考试车辆状态？', choices: ['车辆需要满足安全和合法上路要求', '只为了保持干净', '只为了省油'], answerIndex: 0, explanation: '路考车辆的灯光、刹车、登记和保险等应符合官方要求。' },
  { id: 'ca2-documents-009', category: 'documents', question: '搬家后，驾照地址相关要求应去哪里确认？', choices: ['California DMV 官方网站', '社交媒体投票', '二手交易网站'], answerIndex: 0, explanation: '地址更新期限和方式应以 DMV 官方要求为准。' },
  { id: 'ca2-documents-010', category: 'documents', question: '发生符合报告条件的交通事故后，应如何了解 DMV 报告义务？', choices: ['查看 California DMV 官方事故报告要求', '听朋友猜测', '完全不处理'], answerIndex: 0, explanation: '事故是否需要向 DMV 报告取决于官方规定的条件。' },
  { id: 'ca2-documents-011', category: 'documents', question: 'California DMV 官方样题的主要价值是什么？', choices: ['熟悉题型和知识范围，而不是保证正式考试出现同题', '保证正式考试原题不变', '可以代替所有官方手册'], answerIndex: 0, explanation: '官方样题适合了解题型，但正式考试题库会变化。' },
  { id: 'ca2-documents-012', category: 'documents', question: '为什么不建议只背答案而不理解规则？', choices: ['正式题目可能换表达，理解规则才能应对变化', '因为考试没有选择题', '因为所有答案都一样'], answerIndex: 0, explanation: '理解规则比机械记忆更能应对不同表述和真实驾驶场景。' },
  { id: 'ca2-documents-013', category: 'documents', question: 'California DMV 官方指出，准备知识考试时应该怎样读题？', choices: ['仔细阅读，每题判断唯一正确答案', '只看第一个词', '凭感觉快速点选'], answerIndex: 0, explanation: 'DMV 的备考建议强调仔细阅读问题和所有选项。' },
  { id: 'ca2-documents-014', category: 'documents', question: '如果你准备的是摩托车或商业驾照，是否应该只使用 Class C 题库？', choices: ['不应，应使用对应驾照类别的官方手册和考试资料', '可以，所有驾照完全一样', '只需要看路标'], answerIndex: 0, explanation: '不同驾照类别有不同知识范围，应选择对应官方材料。' },
]
