import type { DmvQuestion } from './dmv-data'

type FlQuestion = DmvQuestion & { en: { question: string; choices: string[]; explanation: string } }

export const floridaQuestions: FlQuestion[] = [
  { id:'fl-speed-001', category:'rules', question:'佛州 School Zone 的标准限速通常是多少？', choices:['15 mph','20 mph','25 mph','30 mph'], answerIndex:1, explanation:'Florida Driver License Handbook 将 school zone 标准限速列为 20 mph，除非现场另有规定。', en:{question:'What is the standard speed limit in a Florida school zone?',choices:['15 mph','20 mph','25 mph','30 mph'],explanation:'The Florida Driver License Handbook lists 20 mph as the standard school-zone speed limit unless otherwise posted.'}},
  { id:'fl-speed-002', category:'rules', question:'佛州市区、商业区或住宅区的标准限速通常是多少？', choices:['20 mph','25 mph','30 mph','35 mph'], answerIndex:2, explanation:'Florida Handbook 通常列为 30 mph，除非另有标志。', en:{question:'What is the usual standard speed limit in a Florida municipal, business, or residential area?',choices:['20 mph','25 mph','30 mph','35 mph'],explanation:'The Florida handbook generally lists 30 mph unless otherwise posted.'}},
  { id:'fl-speed-003', category:'rules', question:'佛州一般 Streets and Highways 的标准限速通常是多少？', choices:['45 mph','50 mph','55 mph','60 mph'], answerIndex:2, explanation:'Florida Handbook 通常列为 55 mph，除非另有标志。', en:{question:'What is the usual standard speed limit on Florida streets and highways?',choices:['45 mph','50 mph','55 mph','60 mph'],explanation:'The Florida handbook generally lists 55 mph unless otherwise posted.'}},
  { id:'fl-speed-004', category:'rules', question:'佛州 Limited Access Highways 的标准最高限速通常是多少？', choices:['55 mph','60 mph','65 mph','70 mph'], answerIndex:3, explanation:'Florida Handbook 通常列为 70 mph。', en:{question:'What is the usual maximum speed limit on Florida limited-access highways?',choices:['55 mph','60 mph','65 mph','70 mph'],explanation:'The Florida handbook generally lists 70 mph.'}},
  { id:'fl-speed-005', category:'rules', question:'在佛州限速 70 mph 的高速公路上，最低限速通常是多少？', choices:['40 mph','45 mph','50 mph','55 mph'], answerIndex:2, explanation:'Florida Handbook 指出，在公布限速 70 mph 的高速公路上，最低限速通常为 50 mph。', en:{question:'On a Florida highway posted at 70 mph, what is the usual minimum speed limit?',choices:['40 mph','45 mph','50 mph','55 mph'],explanation:'The Florida handbook states that the minimum speed is generally 50 mph on highways posted at 70 mph.'}},
  { id:'fl-follow-001', category:'safety', question:'Florida Handbook 建议一般至少保持多少秒跟车距离？', choices:['1–2秒','2–3秒','3–4秒','5–6秒'], answerIndex:2, explanation:'佛州手册建议至少保持约 3–4 秒跟车距离。', en:{question:'What minimum following interval does the Florida handbook generally recommend?',choices:['1–2 seconds','2–3 seconds','3–4 seconds','5–6 seconds'],explanation:'The Florida handbook generally recommends at least a 3–4 second following distance.'}},
  { id:'fl-turn-001', category:'rules', question:'在佛州转弯前，通常应至少提前多少英尺打转向灯？', choices:['50 ft','75 ft','100 ft','200 ft'], answerIndex:2, explanation:'Florida Handbook 说明，转弯前最后 100 英尺应使用转向信号。', en:{question:'In Florida, how far before a turn should you normally signal?',choices:['50 ft','75 ft','100 ft','200 ft'],explanation:'The Florida handbook says to signal during the last 100 feet before turning.'}},
  { id:'fl-learner-001', category:'rules', question:'佛州 Learner’s License 通常最低多少岁可以申请？', choices:['14岁','15岁','16岁','17岁'], answerIndex:1, explanation:'Florida Learner’s License 通常最低年龄为 15 岁。', en:{question:'What is the usual minimum age for a Florida Learner’s License?',choices:['14','15','16','17'],explanation:'A Florida Learner’s License is generally available starting at age 15.'}},
  { id:'fl-learner-002', category:'rules', question:'佛州 learner driver 驾驶时，陪同驾驶人通常至少要多少岁？', choices:['18岁','20岁','21岁','25岁'], answerIndex:2, explanation:'Learner’s License 持有人必须由至少 21 岁的持照驾驶人陪同。', en:{question:'How old must the accompanying licensed driver normally be for a Florida learner driver?',choices:['18','20','21','25'],explanation:'A Florida learner driver must be accompanied by a licensed driver age 21 or older.'}},
  { id:'fl-learner-003', category:'rules', question:'取得佛州 Learner’s License 后前3个月，通常何时可以驾驶？', choices:['任何时间','只在白天','到晚上10点','到午夜'], answerIndex:1, explanation:'前3个月通常只能在白天驾驶。', en:{question:'During the first three months after getting a Florida Learner’s License, when may you normally drive?',choices:['Any time','Daylight hours only','Until 10 p.m.','Until midnight'],explanation:'During the first three months, learner drivers are generally limited to daylight driving.'}},
  { id:'fl-learner-004', category:'rules', question:'佛州 Learner’s License 持有满3个月后，通常最晚可开到几点？', choices:['8 p.m.','9 p.m.','10 p.m.','12 a.m.'], answerIndex:2, explanation:'满3个月后通常可以驾驶到晚上 10 点。', en:{question:'After holding a Florida Learner’s License for three months, how late may you normally drive?',choices:['8 p.m.','9 p.m.','10 p.m.','12 a.m.'],explanation:'After three months, learner drivers may generally drive until 10 p.m.'}},
  { id:'fl-teen-001', category:'rules', question:'佛州未满18岁申请正式驾照前，通常需要至少多少小时监督驾驶？', choices:['30小时','40小时','50小时','60小时'], answerIndex:2, explanation:'通常需要至少 50 小时监督驾驶。', en:{question:'How many supervised driving hours are generally required before a Florida driver under 18 applies for a full license?',choices:['30','40','50','60'],explanation:'Florida generally requires at least 50 hours of supervised driving.'}},
  { id:'fl-teen-002', category:'rules', question:'佛州未满18岁的 50 小时监督驾驶中，至少多少小时应在夜间完成？', choices:['5小时','10小时','15小时','20小时'], answerIndex:1, explanation:'至少 10 小时需要在夜间完成。', en:{question:'Of the 50 supervised driving hours required for a Florida teen, how many must be at night?',choices:['5','10','15','20'],explanation:'At least 10 of the 50 hours must be completed at night.'}},
  { id:'fl-curfew-001', category:'rules', question:'佛州16岁持正式驾照的驾驶人，通常在哪个时间段限制驾驶？', choices:['10 p.m.–5 a.m.','11 p.m.–6 a.m.','12 a.m.–5 a.m.','1 a.m.–6 a.m.'], answerIndex:1, explanation:'16岁驾驶人通常不得在晚上11点到早上6点驾驶，工作或由21岁以上持照驾驶人陪同等情况除外。', en:{question:'What nighttime restriction generally applies to a 16-year-old licensed driver in Florida?',choices:['10 p.m.–5 a.m.','11 p.m.–6 a.m.','12 a.m.–5 a.m.','1 a.m.–6 a.m.'],explanation:'A 16-year-old driver is generally restricted from 11 p.m. to 6 a.m., with exceptions such as work or qualified adult accompaniment.'}},
  { id:'fl-curfew-002', category:'rules', question:'佛州17岁持正式驾照的驾驶人，通常在哪个时间段限制驾驶？', choices:['11 p.m.–5 a.m.','12 a.m.–5 a.m.','1 a.m.–5 a.m.','2 a.m.–6 a.m.'], answerIndex:2, explanation:'17岁驾驶人通常不得在凌晨1点到5点驾驶，工作或由21岁以上持照驾驶人陪同等情况除外。', en:{question:'What nighttime restriction generally applies to a 17-year-old licensed driver in Florida?',choices:['11 p.m.–5 a.m.','12 a.m.–5 a.m.','1 a.m.–5 a.m.','2 a.m.–6 a.m.'],explanation:'A 17-year-old driver is generally restricted from 1 a.m. to 5 a.m., with exceptions such as work or qualified adult accompaniment.'}},
  { id:'fl-dui-001', category:'safety', question:'佛州一般驾驶人的违法酒精浓度标准是多少？', choices:['0.02','0.05','0.08','0.10'], answerIndex:2, explanation:'BAL 0.08 或以上是佛州 DUI 法律标准之一。', en:{question:'What is Florida’s general unlawful blood or breath alcohol level for drivers?',choices:['0.02','0.05','0.08','0.10'],explanation:'A blood or breath alcohol level of 0.08 or above is one Florida DUI legal threshold.'}},
  { id:'fl-dui-002', category:'safety', question:'在佛州拒绝依法要求的酒精/药物测试可能导致什么？', choices:['没有后果','驾照行政处罚或吊销','只罚停车费','只口头警告'], answerIndex:1, explanation:'佛州实行 implied consent，拒绝测试可能导致驾驶资格行政处罚。', en:{question:'What can happen in Florida if you refuse a lawfully requested alcohol or drug test?',choices:['Nothing','Administrative driver-license consequences or suspension','Only a parking fine','A verbal warning only'],explanation:'Florida has implied-consent rules, and refusal can lead to administrative driver-license consequences.'}},
  { id:'fl-bus-001', category:'rules', question:'在佛州普通双向道路上遇到校车停靠并展示 stop signal 时，应怎样做？', choices:['只有同方向停车','双向车辆都停车','只减速','鸣笛后通过'], answerIndex:1, explanation:'在普通双向道路上，两个方向的车辆通常都必须停车。', en:{question:'On a normal two-way Florida road, what must drivers do for a stopped school bus displaying its stop signal?',choices:['Only same-direction traffic stops','Traffic in both directions stops','Only slow down','Honk and pass'],explanation:'On a normal two-way road, traffic in both directions must generally stop.'}},
  { id:'fl-bus-002', category:'rules', question:'在佛州有未铺装5英尺以上中间带、实体 median 或 barrier 的分隔道路上，校车对向车辆通常怎么办？', choices:['也必须停车','可谨慎继续','必须掉头','必须驶入路肩'], answerIndex:1, explanation:'在真正物理分隔的道路上，对向车辆通常可谨慎继续；与校车同方向车辆仍须停车。', en:{question:'On a Florida divided highway separated by an unpaved space at least 5 feet wide, a raised median, or physical barrier, what may opposing traffic normally do for a stopped school bus?',choices:['Must also stop','May continue with caution','Must make a U-turn','Must pull onto the shoulder'],explanation:'On a physically divided roadway, opposing traffic may generally continue with caution, while traffic traveling with the bus must stop.'}},
  { id:'fl-bus-003', category:'rules', question:'佛州仅有 painted lines 或 pavement markings 的道路，是否算实体分隔道路从而让对向车辆免于校车停车？', choices:['算','不算','只有白天算','只有高速公路算'], answerIndex:1, explanation:'仅有油漆线或路面标记不算 physical barrier。', en:{question:'In Florida, do painted lines or pavement markings alone count as a physical divider for the school-bus stopping exception?',choices:['Yes','No','Only during daylight','Only on freeways'],explanation:'Painted lines or pavement markings alone are not considered a physical barrier.'}},
  { id:'fl-bike-001', category:'rules', question:'在佛州，自行车在公共道路上的法律地位通常是什么？', choices:['不算车辆','通常享有与机动车类似的道路权利与责任','只能走人行道','只能夜间行驶'], answerIndex:1, explanation:'佛州将自行车视为车辆，骑行者在公共道路上通常具有相应权利和责任。', en:{question:'How is a bicycle generally treated under Florida road law?',choices:['It is not a vehicle','It generally has roadway rights and responsibilities similar to a motor vehicle','It may use sidewalks only','It may be ridden only at night'],explanation:'Florida generally treats bicycles as vehicles with corresponding roadway rights and responsibilities.'}},
  { id:'fl-moto-001', category:'safety', question:'驾驶汽车与摩托车并排行驶时，正确做法是什么？', choices:['共享同一车道','让摩托车拥有完整车道','挤到其旁边','持续鸣笛'], answerIndex:1, explanation:'摩托车有权使用完整车道，不应与其强行共享车道。', en:{question:'What is the correct way to drive beside a motorcycle in Florida?',choices:['Share the same lane','Allow the motorcycle the full lane','Crowd beside it','Honk continuously'],explanation:'A motorcyclist is entitled to the full lane; do not try to share the lane.'}},
  { id:'fl-moto-002', category:'safety', question:'Florida 安全建议与摩托车保持至少多长时间缓冲？', choices:['1秒','2秒','3秒','4秒'], answerIndex:3, explanation:'FLHSMV 建议与摩托车保持约4秒缓冲，并在恶劣天气下增加。', en:{question:'What minimum buffer does FLHSMV recommend when following a motorcycle?',choices:['1 second','2 seconds','3 seconds','4 seconds'],explanation:'FLHSMV recommends about a four-second buffer behind a motorcycle, with more space in poor conditions.'}},
  { id:'fl-sign-001', category:'signs', question:'红色八角形 STOP 标志要求什么？', choices:['减速','完全停车','鸣笛','只让行'], answerIndex:1, explanation:'必须在停止线或横道前完全停车。', en:{question:'What does a red octagonal STOP sign require?',choices:['Slow down','Come to a complete stop','Honk','Yield only'],explanation:'You must come to a complete stop at the stop line or before the crosswalk.'}},
  { id:'fl-sign-002', category:'signs', question:'红白倒三角 YIELD 标志要求什么？', choices:['加速','减速并让有优先权的交通先行','完全停车5秒','禁止进入'], answerIndex:1, explanation:'YIELD 表示减速、准备停车并在需要时让行。', en:{question:'What does a red-and-white triangular YIELD sign require?',choices:['Speed up','Slow down and yield to traffic with the right-of-way','Stop for five seconds','Do not enter'],explanation:'YIELD means slow down, be ready to stop, and give the right-of-way when required.'}},
  { id:'fl-sign-003', category:'signs', question:'橙色道路标志通常表示什么？', choices:['施工或临时交通控制','医院','学校','休息区'], answerIndex:0, explanation:'橙色通常用于施工和临时交通控制。', en:{question:'What do orange road signs generally indicate?',choices:['Construction or temporary traffic control','Hospital','School','Rest area'],explanation:'Orange signs generally indicate construction or temporary traffic control.'}},
  { id:'fl-sign-004', category:'signs', question:'黄色菱形标志通常表示什么？', choices:['警告前方状况','停车许可','服务设施','车辆登记'], answerIndex:0, explanation:'黄色菱形通常是 warning sign。', en:{question:'What does a yellow diamond-shaped sign generally mean?',choices:['Warning of conditions ahead','Parking permit','Service facility','Vehicle registration'],explanation:'Yellow diamond-shaped signs are generally warning signs.'}},
]
