import type { DmvQuestion } from './dmv-data'

type FlQuestion = DmvQuestion & { en: { question: string; choices: string[]; explanation: string } }

export const floridaSupplementQuestions: FlQuestion[] = [
  { id:'fl-park-001', category:'rules', question:'在佛州，距离消防栓多少英尺以内禁止停车？', choices:['10 ft','15 ft','20 ft','30 ft'], answerIndex:1, explanation:'Florida Driver License Handbook 规定，消防栓 15 英尺以内禁止停车。', en:{question:'In Florida, how close to a fire hydrant is parking prohibited?',choices:['10 ft','15 ft','20 ft','30 ft'],explanation:'The Florida Driver License Handbook prohibits parking within 15 feet of a fire hydrant.'}},
  { id:'fl-park-002', category:'rules', question:'在佛州，距离路口多少英尺以内通常禁止停车？', choices:['10 ft','15 ft','20 ft','30 ft'], answerIndex:2, explanation:'手册列明，距离 intersection 20 英尺以内禁止停车。', en:{question:'In Florida, parking is generally prohibited within how many feet of an intersection?',choices:['10 ft','15 ft','20 ft','30 ft'],explanation:'The handbook lists 20 feet as the no-parking distance from an intersection.'}},
  { id:'fl-park-003', category:'rules', question:'在佛州，距离 flashing signal、STOP sign 或 traffic signal 多少英尺以内禁止停车？', choices:['15 ft','20 ft','30 ft','50 ft'], answerIndex:2, explanation:'手册规定这些交通控制设施 30 英尺以内禁止停车。', en:{question:'In Florida, parking is prohibited within how many feet of a flashing signal, STOP sign, or traffic signal?',choices:['15 ft','20 ft','30 ft','50 ft'],explanation:'The handbook prohibits parking within 30 feet of these traffic-control devices.'}},
  { id:'fl-park-004', category:'rules', question:'在佛州，距离 railroad crossing 多少英尺以内禁止停车？', choices:['20 ft','30 ft','40 ft','50 ft'], answerIndex:3, explanation:'手册规定铁路道口 50 英尺以内禁止停车。', en:{question:'In Florida, parking is prohibited within how many feet of a railroad crossing?',choices:['20 ft','30 ft','40 ft','50 ft'],explanation:'The handbook prohibits parking within 50 feet of a railroad crossing.'}},
  { id:'fl-bike-002', category:'safety', question:'佛州机动车超越自行车时，通常至少要留多少侧向空间？', choices:['2 ft','3 ft','4 ft','5 ft'], answerIndex:1, explanation:'FLHSMV 明确要求机动车在并行或超越自行车时至少保持 3 英尺距离。', en:{question:'How much lateral clearance must a Florida motorist generally give when passing a bicyclist?',choices:['2 ft','3 ft','4 ft','5 ft'],explanation:'FLHSMV states that motorists must provide at least three feet of clearance.'}},
  { id:'fl-bike-003', category:'safety', question:'佛州未满多少岁的骑车人和乘客依法必须佩戴自行车头盔？', choices:['12岁','14岁','16岁','18岁'], answerIndex:2, explanation:'佛州要求未满 16 岁的 bicyclist 和 passenger 佩戴头盔。', en:{question:'Florida law requires bicycle helmets for riders and passengers under what age?',choices:['12','14','16','18'],explanation:'Florida requires bicycle helmets for riders and passengers under age 16.'}},
  { id:'fl-bike-004', category:'rules', question:'佛州自行车从日落到日出骑行时，前方白灯至少应在多远可见？', choices:['300 ft','400 ft','500 ft','600 ft'], answerIndex:2, explanation:'FLHSMV 要求前白灯至少在 500 英尺外可见。', en:{question:'In Florida, a bicycle ridden between sunset and sunrise must have a front white light visible from at least how far away?',choices:['300 ft','400 ft','500 ft','600 ft'],explanation:'FLHSMV requires a front white light visible from at least 500 feet.'}},
  { id:'fl-bike-005', category:'rules', question:'佛州自行车夜间后方红灯通常至少应在多远可见？', choices:['300 ft','400 ft','500 ft','600 ft'], answerIndex:3, explanation:'FLHSMV 要求后方红灯至少在 600 英尺外可见。', en:{question:'In Florida, a bicycle rear red light used at night should generally be visible from at least how far away?',choices:['300 ft','400 ft','500 ft','600 ft'],explanation:'FLHSMV requires the rear red light to be visible from at least 600 feet.'}},
  { id:'fl-bike-006', category:'rules', question:'在佛州，自行车在人行道或人行横道上骑行时，应怎样对待行人？', choices:['自行车永远优先','应让行人先行','只能鸣笛提醒','必须下车推行'], answerIndex:1, explanation:'在人行道或人行横道骑行时，自行车具有行人相关权利和义务，同时必须让行行人。', en:{question:'In Florida, when riding a bicycle on a sidewalk or crosswalk, what must the bicyclist do regarding pedestrians?',choices:['The bicyclist always has priority','Yield the right-of-way to pedestrians','Only honk a warning','Always dismount and walk'],explanation:'A bicyclist on a sidewalk or crosswalk must yield the right-of-way to pedestrians.'}},
  { id:'fl-bike-007', category:'rules', question:'佛州车辆准备右转，同时正在超越同方向自行车时，应在自行车距离路口至少多少英尺时才完成超越并右转？', choices:['10 ft','15 ft','20 ft','30 ft'], answerIndex:2, explanation:'FLHSMV 说明，右转车辆在超越同方向自行车时，只有当自行车距离路口至少 20 英尺才可安全完成相应动作。', en:{question:'In Florida, when a motorist is overtaking a bicycle before making a right turn, the bicycle must be at least how far from the intersection?',choices:['10 ft','15 ft','20 ft','30 ft'],explanation:'FLHSMV notes a 20-foot minimum distance from the intersection for this situation.'}},
  { id:'fl-moto-003', category:'safety', question:'跟随摩托车时，FLHSMV 建议通常保持至少多久的缓冲距离？', choices:['2秒','3秒','4秒','5秒'], answerIndex:2, explanation:'FLHSMV 建议与摩托车保持至少 4 秒缓冲，天气恶劣时进一步增加。', en:{question:'When following a motorcycle, what minimum buffer does FLHSMV recommend?',choices:['2 seconds','3 seconds','4 seconds','5 seconds'],explanation:'FLHSMV recommends at least a four-second buffer behind a motorcycle.'}},
  { id:'fl-moto-004', category:'rules', question:'在佛州，汽车是否可以与摩托车共享同一车道并排行驶？', choices:['可以，只要速度低','可以，只限白天','不可以，摩托车有权使用完整车道','只在市区可以'], answerIndex:2, explanation:'FLHSMV 明确提醒，不要与摩托车共享车道；摩托车有权使用完整车道。', en:{question:'May a Florida motorist share a lane side-by-side with a motorcycle?',choices:['Yes, if traveling slowly','Yes, during daylight only','No, the motorcycle is entitled to the full lane','Only in cities'],explanation:'FLHSMV states that motorists should not share a lane with a motorcycle; the motorcyclist is entitled to the full lane.'}},
  { id:'fl-ped-001', category:'safety', question:'在人行道不可用时，佛州行人通常应怎样行走？', choices:['背向车流走在路中间','面向车流并尽量远离车辆','只走自行车道','必须顺着车流'], answerIndex:1, explanation:'FLHSMV 建议没有 sidewalk 时，行人应面向车流并尽可能远离交通。', en:{question:'When no sidewalk is available in Florida, how should pedestrians generally walk?',choices:['With their backs to traffic in the roadway center','Facing traffic and as far from traffic as possible','Only in the bike lane','Always with traffic'],explanation:'FLHSMV advises pedestrians to walk facing traffic and as far from traffic as possible when no sidewalk is available.'}},
  { id:'fl-ped-002', category:'rules', question:'佛州行人在非路口、非人行横道处横穿道路时，通常应怎样处理机动车路权？', choices:['行人永远优先','必须让道路上的车辆先行','只要挥手就可先走','夜间才需要让行'], answerIndex:1, explanation:'在 mid-block 横穿且没有适用人行横道保护时，行人必须让行道路车辆。', en:{question:'In Florida, when crossing mid-block away from a crosswalk, what must a pedestrian generally do?',choices:['The pedestrian always has priority','Yield the right-of-way to vehicles on the roadway','Wave and proceed first','Yield only at night'],explanation:'A pedestrian crossing mid-block must generally yield the right-of-way to vehicles on the roadway.'}},
  { id:'fl-rail-001', category:'rules', question:'接近铁路道口且确认火车正在接近时，最安全的做法是什么？', choices:['加速抢在火车前通过','停车并等待火车通过','绕过放下的栏杆','跟前车紧贴通过'], answerIndex:1, explanation:'看到火车接近或道口信号要求停车时，必须停车等待，不能绕过栏杆抢行。', en:{question:'What is the safest action when approaching a railroad crossing and a train is clearly approaching?',choices:['Speed up to beat the train','Stop and wait for the train to pass','Drive around a lowered gate','Follow the vehicle ahead closely'],explanation:'You must stop and wait when a train is approaching or crossing controls require a stop.'}},
  { id:'fl-rail-002', category:'rules', question:'交通拥堵时，铁路道口另一侧没有足够空间容纳整辆车，应该怎么办？', choices:['先开到轨道上等待','停在轨道前，等到能完全通过再进入','跟紧前车','打开双闪后进入'], answerIndex:1, explanation:'不能把车辆停在铁路轨道上，必须先确认有足够空间一次完全通过。', en:{question:'If traffic is backed up and there is not enough room beyond a railroad crossing for your whole vehicle, what should you do?',choices:['Drive onto the tracks and wait','Stop before the tracks until you can clear them completely','Follow the vehicle ahead closely','Enter with hazard lights on'],explanation:'Never stop on railroad tracks; wait until there is enough room to clear them completely.'}},
  { id:'fl-safe-001', category:'safety', question:'佛州手册建议一般车辆至少保持多长跟车距离？', choices:['1–2秒','2秒','3–4秒','6秒'], answerIndex:2, explanation:'Florida Driver License Handbook 建议至少保持 3–4 秒跟车距离。', en:{question:'What minimum following distance does the Florida Driver License Handbook generally recommend?',choices:['1–2 seconds','2 seconds','3–4 seconds','6 seconds'],explanation:'The Florida Driver License Handbook generally recommends a minimum following distance of three to four seconds.'}},
  { id:'fl-turn-002', category:'rules', question:'佛州驾驶人在转弯前最后多少英尺应持续发出转向信号？', choices:['50 ft','75 ft','100 ft','150 ft'], answerIndex:2, explanation:'Florida Handbook 规定应在转弯前最后 100 英尺使用转向信号。', en:{question:'In Florida, during the last how many feet before a turn should a driver signal?',choices:['50 ft','75 ft','100 ft','150 ft'],explanation:'The Florida handbook says to signal during the last 100 feet before turning.'}},
  { id:'fl-sign-005', category:'signs', question:'白底黑字的 SPEED LIMIT 标志属于什么类型？', choices:['Warning','Regulatory','Guide','Service'], answerIndex:1, explanation:'SPEED LIMIT 是法规性 regulatory sign，驾驶人必须遵守。', en:{question:'What type of sign is a black-on-white SPEED LIMIT sign?',choices:['Warning','Regulatory','Guide','Service'],explanation:'A SPEED LIMIT sign is a regulatory sign and must be obeyed.'}},
  { id:'fl-sign-006', category:'signs', question:'绿色道路标志通常提供哪类信息？', choices:['方向、目的地、出口或距离','施工警告','禁止行为','医院急救'], answerIndex:0, explanation:'绿色标志通常用于方向、路线、出口和距离等 guide information。', en:{question:'What information do green road signs generally provide?',choices:['Directions, destinations, exits, or distances','Construction warnings','Prohibited actions','Emergency medical warnings'],explanation:'Green signs generally provide guide information such as routes, directions, exits, and distances.'}},
]
