import type { DmvQuestion } from './dmv-data'

type MaQuestion = DmvQuestion & { en: { question: string; choices: string[]; explanation: string } }

export const massachusettsQuestions: MaQuestion[] = [
  { id:'ma-permit-001', category:'rules', question:'在麻州，申请 Class D learner’s permit 的最低年龄通常是多少？', choices:['15岁','15岁半','16岁','17岁'], answerIndex:2, explanation:'Massachusetts RMV 要求申请 Class D learner’s permit 至少 16 岁。', en:{question:'What is the usual minimum age to apply for a Massachusetts Class D learner’s permit?',choices:['15','15½','16','17'],explanation:'The Massachusetts RMV requires an applicant for a Class D learner’s permit to be at least 16.'}},
  { id:'ma-jol-001', category:'rules', question:'麻州 18 岁以下申请人在参加路考前，通常必须连续持有 learner’s permit 多久？', choices:['30天','3个月','6个月','12个月'], answerIndex:2, explanation:'18 岁以下申请人通常必须连续持有有效 learner’s permit 至少 6 个月。', en:{question:'Before taking the road test, how long must a Massachusetts applicant under 18 normally hold a valid learner’s permit?',choices:['30 days','3 months','6 months','12 months'],explanation:'An applicant under 18 normally must hold a valid learner’s permit for at least 6 consecutive months.'}},
  { id:'ma-jol-002', category:'rules', question:'麻州 18 岁以下申请人通常还需要完成多少小时额外的家长或监护人监督驾驶？', choices:['20小时','30小时','40小时','50小时'], answerIndex:2, explanation:'JOL 要求通常包括至少 40 小时额外的监督驾驶。', en:{question:'How many additional hours of parent- or guardian-supervised driving are normally required for a Massachusetts applicant under 18?',choices:['20 hours','30 hours','40 hours','50 hours'],explanation:'JOL requirements normally include at least 40 additional hours of supervised driving.'}},
  { id:'ma-jol-003', category:'rules', question:'麻州 18 岁以下申请人在路考前，驾驶记录通常需要保持清洁多长时间？', choices:['30天','3个月','6个月','1年'], answerIndex:2, explanation:'JOL 规则要求通常在路考前连续 6 个月保持清洁驾驶记录。', en:{question:'How long must a Massachusetts applicant under 18 normally maintain a clean driving record before the road test?',choices:['30 days','3 months','6 months','1 year'],explanation:'JOL rules normally require a clean driving record for 6 consecutive months before the road test.'}},
  { id:'ma-jol-004', category:'rules', question:'麻州 18 岁以下 Class D 申请人是否必须完成经认可的 Driver Education？', choices:['是','否','只在波士顿需要','只有发生事故后需要'], answerIndex:0, explanation:'所有 18 岁以下 Class D 或 M 驾照申请人都需要完成规定的驾驶教育课程。', en:{question:'Must a Massachusetts Class D applicant under 18 complete an approved driver education program?',choices:['Yes','No','Only in Boston','Only after a crash'],explanation:'All Class D or M license applicants under 18 must complete the required driver education program.'}},
  { id:'ma-jol-005', category:'rules', question:'如果麻州未满 18 岁的 permit holder 在 6 个月等待期内被暂停驾驶资格，通常会怎样？', choices:['等待期不受影响','恢复后 6 个月等待期重新开始','只增加 7 天','自动获得驾照'], answerIndex:1, explanation:'暂停会使原来的连续 6 个月要求失效，恢复后通常重新计算。', en:{question:'What normally happens to the six-month permit holding period if a Massachusetts permit holder under 18 is suspended during that period?',choices:['Nothing changes','The six-month period restarts after the suspension ends','Only seven days are added','The driver automatically receives a license'],explanation:'A suspension breaks the required consecutive period, so the six-month period normally restarts after the suspension ends.'}},

  { id:'ma-phone-001', category:'safety', question:'麻州 18 岁及以上驾驶人使用手机时，通常必须采用什么方式？', choices:['手持使用','Hands-free 免提方式','红灯时手持','低速时手持'], answerIndex:1, explanation:'Massachusetts Hands-Free Law 要求 18 岁及以上驾驶人使用电子设备时采用免提方式。', en:{question:'How may a Massachusetts driver age 18 or older normally use a phone while driving?',choices:['Handheld','Hands-free','Handheld at red lights','Handheld at low speed'],explanation:'Massachusetts law generally requires drivers age 18 or older to use electronic devices only in hands-free mode.'}},
  { id:'ma-phone-002', category:'safety', question:'麻州未满 18 岁的驾驶人是否可以在开车时使用 hands-free 手机？', choices:['可以','不可以','只有高速公路可以','只有白天可以'], answerIndex:1, explanation:'未满 18 岁驾驶人开车时不得使用电子设备，包括 hands-free。', en:{question:'May a Massachusetts driver under 18 use a hands-free phone while driving?',choices:['Yes','No','Only on highways','Only during daylight'],explanation:'Drivers under 18 may not use electronic devices while driving, including in hands-free mode.'}},
  { id:'ma-phone-003', category:'safety', question:'在麻州，车辆停在红灯时，驾驶人可以手持手机操作吗？', choices:['可以','不可以','只可发短信','只可看视频'], answerIndex:1, explanation:'Hands-Free Law 明确禁止在红灯或 STOP 标志处手持使用设备。', en:{question:'In Massachusetts, may a driver hold and use a phone while stopped at a red light?',choices:['Yes','No','Only for texting','Only for video'],explanation:'The Hands-Free Law prohibits handheld device use at red lights or stop signs.'}},
  { id:'ma-phone-004', category:'safety', question:'麻州 18 岁及以上驾驶人何时可以触碰已正确固定的设备？', choices:['随时浏览网页','只为启动 hands-free 模式等允许操作','随时打字','观看视频时'], answerIndex:1, explanation:'设备正确固定后，只允许有限触碰，例如启动 hands-free 功能；不能用于短信、邮件、App、视频或上网。', en:{question:'When may a Massachusetts driver age 18 or older touch a properly mounted device?',choices:['Any time to browse the internet','Only for limited allowed actions such as activating hands-free mode','Any time to type','While watching video'],explanation:'A properly mounted device may only be touched for limited allowed actions such as activating hands-free mode, not for texting, email, apps, video, or internet use.'}},
  { id:'ma-phone-005', category:'safety', question:'麻州驾驶人在真正紧急情况下是否可以用手机拨打 911？', choices:['可以','不可以','只有乘客可以','只有停车场可以'], answerIndex:0, explanation:'法律允许为报告紧急情况拨打 911；如可行，应先安全靠边停车。', en:{question:'May a Massachusetts driver use a phone to call 911 in a genuine emergency?',choices:['Yes','No','Only a passenger may call','Only in a parking lot'],explanation:'The law allows a call to 911 to report an emergency; if possible, pull over safely first.'}},

  { id:'ma-bus-001', category:'rules', question:'在麻州跟随校车行驶时，通常至少应保持多少距离？', choices:['25英尺','50英尺','75英尺','100英尺'], answerIndex:3, explanation:'Massachusetts 法律要求不得在校车后方 100 英尺以内跟随。', en:{question:'When following a school bus in Massachusetts, what minimum distance should you normally maintain?',choices:['25 feet','50 feet','75 feet','100 feet'],explanation:'Massachusetts law requires drivers to remain at least 100 feet behind a school bus.'}},
  { id:'ma-bus-002', category:'rules', question:'麻州校车停车并闪烁红灯时，接近的驾驶人通常应该怎么做？', choices:['减速通过','停车','鸣笛后通过','只让后方车辆停车'], answerIndex:1, explanation:'校车红灯闪烁时，接近车辆必须停车并等待。', en:{question:'What should a Massachusetts driver normally do when approaching a stopped school bus with red lights flashing?',choices:['Slow and pass','Stop','Honk and pass','Only vehicles behind the bus must stop'],explanation:'Drivers approaching a stopped school bus with flashing red lights must stop.'}},
  { id:'ma-bus-003', category:'rules', question:'麻州校车闪红灯时，对向车辆通常也要停车；哪种情况是主要例外？', choices:['夜间','下雨','中间有实体隔离带的 divided highway','车速低于20 mph'], answerIndex:2, explanation:'对向车辆在有实体隔离带分开的 divided highway 上通常属于例外。', en:{question:'In Massachusetts, opposing traffic normally must stop for a school bus with flashing red lights. What is the main exception?',choices:['At night','In rain','On a divided highway separated by a physical barrier','When traveling under 20 mph'],explanation:'Opposing traffic is generally excepted when a physical barrier separates the divided highway.'}},
  { id:'ma-bus-004', category:'rules', question:'麻州校车黄色/琥珀色灯开始闪烁时，驾驶人应该怎么做？', choices:['加速超过校车','减速并准备停车','立即掉头','保持原速'], answerIndex:1, explanation:'黄色/琥珀色灯表示校车准备停车上下乘客，应减速并准备停车。', en:{question:'What should you do when a Massachusetts school bus begins flashing yellow or amber lights?',choices:['Accelerate past it','Slow down and prepare to stop','Make an immediate U-turn','Maintain speed'],explanation:'Yellow or amber lights mean the bus is preparing to stop to load or unload passengers.'}},
  { id:'ma-bus-005', category:'rules', question:'校车红灯停止闪烁后，何时通常可以继续行驶？', choices:['红灯熄灭且 stop arm 收回后','立刻','30秒后','听到喇叭后'], answerIndex:0, explanation:'通常应等红灯关闭且 stop arm 完全收回，除非警察指示通行。', en:{question:'When may you normally proceed after stopping for a Massachusetts school bus?',choices:['After the red lights are off and the stop arm is fully retracted','Immediately','After 30 seconds','After hearing a horn'],explanation:'Normally remain stopped until the red lights are off and the stop arm is fully retracted, unless directed by police.'}},

  { id:'ma-bike-001', category:'safety', question:'麻州驾驶人超越自行车或其他 vulnerable road user 时，至少应留出多少安全距离？', choices:['2英尺','3英尺','4英尺','6英尺'], answerIndex:2, explanation:'Massachusetts 的安全超车规则要求至少 4 英尺间距。', en:{question:'How much space must a Massachusetts driver provide when passing a bicyclist or other vulnerable road user?',choices:['2 feet','3 feet','4 feet','6 feet'],explanation:'Massachusetts law requires a safe passing distance of at least 4 feet.'}},
  { id:'ma-bike-002', category:'safety', question:'为了给 vulnerable road user 留出至少 4 英尺距离，麻州驾驶人在安全且不超速时是否可以越过中心线？', choices:['可以','不可以','只有警车可以','只有夜间可以'], answerIndex:0, explanation:'在安全并遵守限速的前提下，法律允许使用相邻车道或越过中心线完成安全超越。', en:{question:'May a Massachusetts driver cross the centerline when necessary to give a vulnerable road user at least four feet, if it is safe and the speed limit is obeyed?',choices:['Yes','No','Only police vehicles may','Only at night'],explanation:'The law allows use of an adjacent lane or crossing the centerline when needed for a safe pass, if it is safe and the speed limit is obeyed.'}},
  { id:'ma-bike-003', category:'safety', question:'如果无法安全给自行车骑行者留出 4 英尺距离，最正确的做法是什么？', choices:['贴近快速通过','减速并在后方等待','鸣笛逼其靠边','驶上路肩超车'], answerIndex:1, explanation:'无法保持 4 英尺安全间距时，应减速并保持安全跟车距离等待机会。', en:{question:'What should you do if you cannot safely give a bicyclist four feet of space while passing?',choices:['Pass closely and quickly','Slow down and stay back','Honk to force the bicyclist aside','Pass on the shoulder'],explanation:'If the four-foot buffer cannot be provided safely, slow down and remain behind at a respectful distance.'}},
  { id:'ma-bike-004', category:'rules', question:'超越自行车后准备右转时，麻州驾驶人应该怎样做？', choices:['立刻切到自行车前右转','只有在与自行车保持安全距离且速度合理时再转','鸣笛后立即转','自行车必须停车让车'], answerIndex:1, explanation:'法律禁止在无法与被超越自行车保持安全距离时立即右转。', en:{question:'After passing a bicyclist in Massachusetts, when should a driver make a right turn?',choices:['Immediately cut in front of the bicyclist','Only when the turn can be made at a safe distance and reasonable speed','Immediately after honking','The bicyclist must stop first'],explanation:'A driver must not make a right turn after passing a bicyclist unless the turn can be made at a safe distance and reasonable speed.'}},
  { id:'ma-bike-005', category:'safety', question:'麻州驾驶人打开车门前，必须先确认什么？', choices:['车内空调已关闭','不会干扰自行车、行人或其他交通','后车在鸣笛','路边没有停车计时器'], answerIndex:1, explanation:'只有在不会妨碍包括自行车和行人在内的其他交通时才应开门。', en:{question:'Before opening a vehicle door in Massachusetts, what must a driver or passenger make sure of?',choices:['The air conditioning is off','It is reasonably safe and will not interfere with bicyclists, pedestrians, or other traffic','A vehicle behind is honking','There is no parking meter'],explanation:'A vehicle door should only be opened when it is reasonably safe and will not interfere with other traffic, including bicyclists and pedestrians.'}},

  { id:'ma-blind-001', category:'rules', question:'在麻州遇到使用白手杖或导盲犬的视障行人过街时，驾驶人必须怎么做？', choices:['减速但继续','完全停车让其安全通过','鸣笛提醒','绕到其前方'], answerIndex:1, explanation:'White Cane Law 要求驾驶人完全停车，并等待视障行人安全通过。', en:{question:'What must a Massachusetts driver do when a visually impaired pedestrian using a white cane or guide dog is crossing?',choices:['Slow but continue','Come to a complete stop and allow the person to cross safely','Honk as a warning','Drive around in front'],explanation:'The White Cane Law requires a complete stop and safe passage for a visually impaired pedestrian.'}},
  { id:'ma-blind-002', category:'rules', question:'视障行人正在过街时，麻州驾驶人应该鸣笛或挥手示意其通过吗？', choices:['应该','不应该','只有白天可以','只有路口可以'], answerIndex:1, explanation:'官方 Driver’s Manual 明确建议不要鸣笛或挥手催促视障行人。', en:{question:'Should a Massachusetts driver honk or wave a visually impaired pedestrian across the street?',choices:['Yes','No','Only during daylight','Only at intersections'],explanation:'The Massachusetts Driver’s Manual says not to honk or wave a visually impaired pedestrian on.'}},
  { id:'ma-ped-001', category:'rules', question:'麻州驾驶人看到行人位于道路同一半幅，或距离车辆路线约 10 英尺以内时，应怎么做？', choices:['加速通过','让行','鸣笛后继续','只在夜间让行'], answerIndex:1, explanation:'Massachusetts 行人规则要求在这些情况下让行。', en:{question:'What should a Massachusetts driver do when a pedestrian is on the same half of the roadway or within about 10 feet of the driver’s path?',choices:['Accelerate','Yield','Honk and continue','Yield only at night'],explanation:'Massachusetts pedestrian law requires the driver to yield in these circumstances.'}},
  { id:'ma-ped-002', category:'rules', question:'前车因人行横道上的行人停车时，后车可以超越吗？', choices:['可以','不可以','只有右侧可以','只有没有警察时可以'], answerIndex:1, explanation:'不得超越因让行人而在人行横道前停车的车辆。', en:{question:'May you pass a vehicle that has stopped at a marked crosswalk to allow a pedestrian to cross?',choices:['Yes','No','Only on the right','Only when no police are present'],explanation:'A driver must not pass another vehicle that has stopped at a marked crosswalk for a pedestrian.'}},

  { id:'ma-intersection-001', category:'rules', question:'麻州无信号、无标志路口，两车几乎同时到达时，左侧车辆通常应怎样做？', choices:['抢先通过','让右侧车辆先行','鸣笛后通过','倒车'], answerIndex:1, explanation:'Massachusetts 规则要求左侧车辆通常让右侧车辆先行。', en:{question:'At an uncontrolled Massachusetts intersection, when two vehicles arrive at about the same time, what should the vehicle on the left normally do?',choices:['Go first','Yield to the vehicle on the right','Honk and proceed','Back up'],explanation:'Massachusetts right-of-way rules generally require the vehicle on the left to yield to the vehicle on the right.'}},
  { id:'ma-intersection-002', category:'rules', question:'进入麻州未受信号控制的 rotary/环岛时，应让谁先行？', choices:['准备进入的车辆','已经在环岛内的车辆','大型车辆','鸣笛车辆'], answerIndex:1, explanation:'进入车辆必须让已经在 rotary 内行驶的车辆先行。', en:{question:'When entering an uncontrolled rotary in Massachusetts, who has the right-of-way?',choices:['Vehicles entering','Vehicles already in the rotary','Larger vehicles','Vehicles that honk'],explanation:'A driver entering a rotary must yield to vehicles already in the rotary.'}},
  { id:'ma-turn-001', category:'rules', question:'从私人道路、车道或未铺装道路驶入铺装主路时，麻州驾驶人首先应该做什么？', choices:['加速并线','停车，然后让行主路交通和行人/自行车','鸣笛','只看左边'], answerIndex:1, explanation:'进入铺装主路前应停车，并让行道路上的行人、自行车和车辆。', en:{question:'When entering a paved road from a private road, driveway, or unpaved road in Massachusetts, what should you do first?',choices:['Accelerate into traffic','Stop, then yield to pedestrians, bicyclists, and vehicles on the road','Honk','Look only left'],explanation:'You must stop before entering the paved thoroughfare and yield to traffic, pedestrians, and bicyclists.'}},
  { id:'ma-turn-002', category:'rules', question:'麻州驾驶人左转时，通常必须让哪些道路使用者先行？', choices:['只让大型卡车','对向车辆、交叉路径内行人和自行车','只让警车','只让右转车辆'], answerIndex:1, explanation:'左转必须让对向车辆以及穿越预定路径的行人和自行车。', en:{question:'When turning left in Massachusetts, whom must a driver normally yield to?',choices:['Only large trucks','Oncoming vehicles and pedestrians or bicyclists crossing the intended path','Only police vehicles','Only right-turning vehicles'],explanation:'A left-turning driver must yield to oncoming traffic and to pedestrians and bicyclists crossing the intended path.'}},

  { id:'ma-move-001', category:'safety', question:'在麻州接近路边停靠并闪烁警示灯的紧急或救援车辆时，驾驶人应首先怎么做？', choices:['加速通过','减速并提高警觉','停车在原车道','关闭车灯'], answerIndex:1, explanation:'Move Over 规则要求驾驶人减速并谨慎接近。', en:{question:'What should a Massachusetts driver first do when approaching a stopped emergency or recovery vehicle displaying warning lights?',choices:['Accelerate past','Slow down and use caution','Stop in the travel lane','Turn off headlights'],explanation:'Massachusetts Move Over rules require drivers to slow down and approach cautiously.'}},
  { id:'ma-move-002', category:'safety', question:'在多车道道路上接近麻州紧急响应区域时，如果安全可行，应怎样做？', choices:['驶入离响应区域更远的车道','保持相邻车道','停在响应车辆后','驶上路肩'], answerIndex:0, explanation:'如果安全可行，应移到不紧邻紧急响应区域的车道。', en:{question:'On a multilane road in Massachusetts, what should you do when approaching an emergency response area if it is safe to do so?',choices:['Move into a lane farther from the response area','Remain in the adjacent lane','Stop behind the response vehicle','Drive on the shoulder'],explanation:'When safe, move into a lane that is not adjacent to the emergency response area.'}},

  { id:'ma-alcohol-001', category:'safety', question:'酒精或药物影响驾驶能力时，最安全且合法的选择是什么？', choices:['慢一点继续开','不要驾驶，安排清醒驾驶人或其他交通方式','喝咖啡后开','开窗后开'], answerIndex:1, explanation:'麻州 Permit 考试明确覆盖酒精/药物驾驶后果；受影响时不应驾驶。', en:{question:'If alcohol or drugs impair your ability to drive, what is the safest and lawful choice?',choices:['Drive more slowly','Do not drive; use a sober driver or another form of transportation','Drink coffee and drive','Open a window and drive'],explanation:'The Massachusetts permit exam covers consequences of impaired driving; an impaired person should not drive.'}},
  { id:'ma-alcohol-002', category:'safety', question:'喝咖啡、洗冷水澡或开窗是否能快速消除酒精造成的驾驶能力下降？', choices:['能','不能','只对新手有效','只在白天有效'], answerIndex:1, explanation:'这些方法不能迅速清除体内酒精，也不能恢复安全驾驶能力。', en:{question:'Can coffee, a cold shower, or opening a window quickly eliminate alcohol-related driving impairment?',choices:['Yes','No','Only for new drivers','Only during daylight'],explanation:'These methods do not quickly remove alcohol from the body or restore safe driving ability.'}},

  { id:'ma-sign-001', category:'signs', question:'麻州道路上的八角形红色 STOP 标志要求什么？', choices:['仅减速','完全停车并确认安全后再行驶','加速通过','只让行人'], answerIndex:1, explanation:'STOP 标志要求在停车线或适当位置完全停车。', en:{question:'What does an octagonal red STOP sign require in Massachusetts?',choices:['Slow only','Come to a complete stop and proceed when safe','Accelerate through','Yield only to pedestrians'],explanation:'A STOP sign requires a complete stop at the stop line or proper stopping point before proceeding safely.'}},
  { id:'ma-sign-002', category:'signs', question:'倒三角形 YIELD 标志表示什么？', choices:['必须掉头','减速并让有优先权的交通先行','停车5分钟','道路封闭'], answerIndex:1, explanation:'YIELD 要求减速并在必要时停车，让有路权者先行。', en:{question:'What does a triangular YIELD sign mean?',choices:['Make a U-turn','Slow down and yield to traffic with the right-of-way','Stop for five minutes','Road closed'],explanation:'YIELD means slow down, be prepared to stop, and give the right-of-way when required.'}},
  { id:'ma-sign-003', category:'signs', question:'橙色道路标志通常表示什么？', choices:['施工或临时交通控制','医院','学校','铁路'], answerIndex:0, explanation:'橙色通常用于施工、维护和临时交通控制警告。', en:{question:'What do orange road signs generally indicate?',choices:['Construction or temporary traffic control','Hospital services','School area','Railroad'],explanation:'Orange signs generally warn of construction, maintenance, or temporary traffic control.'}},
  { id:'ma-sign-004', category:'signs', question:'黄色菱形标志通常属于哪一类？', choices:['警告标志','服务标志','停车许可','车辆登记'], answerIndex:0, explanation:'黄色菱形通常是警告标志，用于提醒前方道路状况。', en:{question:'What type of sign is usually a yellow diamond?',choices:['Warning sign','Service sign','Parking permit','Vehicle registration'],explanation:'Yellow diamond signs are generally warning signs for road conditions ahead.'}},

  { id:'ma-safety-001', category:'safety', question:'在湿滑或结冰路面驾驶时，正确做法是什么？', choices:['增加速度','减速并增加跟车距离','猛打方向','紧跟前车'], answerIndex:1, explanation:'低附着路面应降低速度并增加反应和制动空间。', en:{question:'What should you do when driving on wet or icy Massachusetts roads?',choices:['Increase speed','Slow down and increase following distance','Make sharp steering movements','Follow closely'],explanation:'Low-traction conditions require reduced speed and more space for reaction and braking.'}},
  { id:'ma-safety-002', category:'safety', question:'夜间会车时对向灯光刺眼，最安全的做法是什么？', choices:['直视灯光','看道路右侧边缘并降低速度','打开远光灯回照','闭眼'], answerIndex:1, explanation:'避免直视强光，参考道路右侧边缘并适当减速。', en:{question:'What is the safest response to glare from oncoming headlights at night?',choices:['Look directly at the lights','Look toward the right edge of the road and reduce speed','Turn on high beams at the other driver','Close your eyes'],explanation:'Avoid staring into glare; use the right edge of the roadway as a guide and reduce speed as needed.'}},
  { id:'ma-safety-003', category:'safety', question:'准备变更车道前，最重要的步骤是什么？', choices:['只看前方','打转向灯、查看后视镜并检查盲区','立即转向','先鸣笛'], answerIndex:1, explanation:'安全变道需要提前示意并确认后方及盲区安全。', en:{question:'What is most important before changing lanes?',choices:['Look only ahead','Signal, check mirrors, and check the blind spot','Turn immediately','Honk first'],explanation:'A safe lane change requires signaling and checking mirrors and blind spots before moving.'}},
  { id:'ma-safety-004', category:'safety', question:'接近被建筑物、树木或其他障碍遮挡视线的弯道或路口时，应怎么做？', choices:['加速','减速并保持靠右','驶到路中央','鸣笛后不减速'], answerIndex:1, explanation:'Massachusetts 法律要求在视线受阻的弯道、街角和路口减速并保持靠右。', en:{question:'What should you do when approaching a curve, corner, or intersection where your view is obstructed?',choices:['Accelerate','Slow down and keep to the right','Drive toward the center','Honk without slowing'],explanation:'Massachusetts law requires drivers to slow down and keep to the right when visibility is obstructed.'}},
]
