import type { DmvQuestion } from './dmv-data'

type MaQuestion = DmvQuestion & { en: { question: string; choices: string[]; explanation: string } }

export const massachusettsJolQuestions: MaQuestion[] = [
  { id:'ma-permit-002', category:'rules', question:'持麻州 learner’s permit 驾车时，陪同驾驶人通常至少要多少岁？', choices:['18岁','19岁','21岁','25岁'], answerIndex:2, explanation:'陪同驾驶人通常必须至少 21 岁、持有效驾照、至少有 1 年驾驶经验，并坐在 permit holder 旁边。', en:{question:'How old must the accompanying driver normally be when a Massachusetts learner’s permit holder is driving?',choices:['18','19','21','25'],explanation:'The accompanying driver normally must be at least 21, properly licensed, have at least one year of driving experience, and sit beside the permit holder.'}},
  { id:'ma-permit-003', category:'rules', question:'麻州 learner’s permit holder 的陪同驾驶人通常至少需要多少年驾驶经验？', choices:['6个月','1年','2年','5年'], answerIndex:1, explanation:'陪同驾驶人通常至少需要 1 年驾驶经验。', en:{question:'How much driving experience must the accompanying driver normally have for a Massachusetts learner’s permit holder?',choices:['6 months','1 year','2 years','5 years'],explanation:'The accompanying driver normally must have at least one year of driving experience.'}},
  { id:'ma-permit-004', category:'rules', question:'麻州未满 18 岁 permit holder 在午夜 12:00 到早上 5:00 之间通常何时可以驾驶？', choices:['任何时候','只有父母或法定监护人符合要求并坐在旁边时','只要有同龄朋友陪同','只在周末'], answerIndex:1, explanation:'未满 18 岁 permit holder 在 12:00 a.m.–5:00 a.m. 通常只能在符合资格的父母或法定监护人陪同下驾驶。', en:{question:'When may a Massachusetts learner’s permit holder under 18 normally drive between midnight and 5:00 a.m.?',choices:['At any time','Only when accompanied by a qualified parent or legal guardian seated beside the driver','With any friend of the same age','Only on weekends'],explanation:'A permit holder under 18 normally may drive from midnight to 5:00 a.m. only with a qualified parent or legal guardian.'}},
  { id:'ma-jol-006', category:'rules', question:'麻州 Junior Operator 取得 JOL 后最初 6 个月，通常能否搭载未满 18 岁的非直系家庭成员？', choices:['可以无限制搭载','通常不可以，除非有符合资格的21岁以上驾驶人坐在旁边','只要系安全带就可以','只在白天禁止'], answerIndex:1, explanation:'JOL 最初 6 个月通常限制搭载未满 18 岁的非直系家庭成员，除非有符合资格的 21 岁以上驾驶人陪同。', en:{question:'During the first six months after receiving a Massachusetts JOL, may a junior operator normally carry passengers under 18 who are not immediate family members?',choices:['Yes, without restriction','Generally no, unless a qualified driver age 21 or older is seated beside the junior operator','Yes, if everyone wears a seat belt','Only daytime passengers are prohibited'],explanation:'The first six months of a JOL generally restrict passengers under 18 who are not immediate family unless a qualified driver age 21 or older is seated beside the junior operator.'}},
  { id:'ma-jol-007', category:'rules', question:'麻州 Junior Operator 在未满 18 岁期间，通常禁止在哪个时间段单独驾驶？', choices:['晚上10点到午夜','凌晨12:30到5:00','凌晨1点到3点','早上5点到7点'], answerIndex:1, explanation:'JOL 持有人通常不得在 12:30 a.m.–5:00 a.m. 驾驶，除非有父母或法定监护人陪同。', en:{question:'During what hours is a Massachusetts Junior Operator normally prohibited from driving without a parent or legal guardian?',choices:['10:00 p.m. to midnight','12:30 a.m. to 5:00 a.m.','1:00 a.m. to 3:00 a.m.','5:00 a.m. to 7:00 a.m.'],explanation:'A JOL holder normally may not drive from 12:30 a.m. to 5:00 a.m. unless accompanied by a parent or legal guardian.'}},
  { id:'ma-jol-008', category:'rules', question:'麻州 JOL 乘客限制或夜间驾驶限制首次违规，通常可能导致多久驾照暂停？', choices:['7天','30天','60天','1年'], answerIndex:2, explanation:'JOL 乘客或夜间限制首次违规通常会导致 60 天暂停；后续违规处罚更重。', en:{question:'What is the typical license suspension for a first violation of Massachusetts JOL passenger or nighttime restrictions?',choices:['7 days','30 days','60 days','1 year'],explanation:'A first violation of the JOL passenger or nighttime restriction typically results in a 60-day suspension, with stronger penalties for later violations.'}},
]
