import type { DmvQuestion } from './dmv-data'

// Pennsylvania-specific exam material only. General guidance, application steps and
// non-tested informational copy belong on the Pennsylvania landing/guide pages.
export const pennsylvaniaQuestions: DmvQuestion[] = [
  { id:'pa-rules-001', category:'rules', question:'在宾州，接近一辆已停车、红灯闪烁且 STOP ARM 已伸出的校车时，你通常应在距离校车至少多远处停车？', choices:['5 英尺','10 英尺','15 英尺','25 英尺'], answerIndex:1, explanation:'宾州校车红灯闪烁并伸出停车臂时，驾驶人通常必须在距离校车至少 10 英尺处停车。' },
  { id:'pa-rules-002', category:'rules', question:'在宾州双向道路上，对向校车停车并闪烁红灯、伸出 STOP ARM，而道路中间没有物理隔离设施。你应怎么办？', choices:['继续行驶但降到 15 mph','停车等待','只要看不到儿童即可通过','鸣笛后慢速通过'], answerIndex:1, explanation:'没有物理隔离的道路上，接近闪烁红灯并伸出停车臂的校车时，对向车辆也必须停车。' },
  { id:'pa-rules-003', category:'rules', question:'在宾州，你与一辆闪烁红灯并伸出 STOP ARM 的校车位于分隔公路的相反方向，中间有实体隔离带。通常应如何处理？', choices:['仍必须停车','可以谨慎继续行驶','必须掉头','必须停到校车收起停车臂后再走'], answerIndex:1, explanation:'若对向车道由实体隔离设施分开，通常不要求为另一侧的校车停车。' },
  { id:'pa-rules-004', category:'rules', question:'宾州学校区域在限速标志规定的有效时间内，常见的法定限速是多少？', choices:['10 mph','15 mph','20 mph','25 mph'], answerIndex:1, explanation:'宾州 School Zone 在规定有效时间内通常限速 15 mph。' },
  { id:'pa-rules-005', category:'rules', question:'在宾州施工区驾驶时，关于车灯哪项正确？', choices:['白天永远不需要开灯','应按规定打开车辆前灯','只需打开停车灯','只需依靠日间行车灯'], answerIndex:1, explanation:'宾州要求在标示的施工区域按规定使用前灯；不能把日间行车灯当作完整前灯要求。' },
  { id:'pa-safety-001', category:'safety', question:'在宾州，因为天气导致挡风玻璃雨刷持续或间歇工作时，你还应做什么？', choices:['打开前灯','打开远光灯','打开危险警示灯并继续原速','关闭车灯以减少反光'], answerIndex:0, explanation:'宾州实行 wipers-on/headlights-on 要求，因天气使用雨刷时应打开前灯。' },
  { id:'pa-safety-002', category:'safety', question:'在宾州接近停有闪灯应急车辆的紧急响应区域，如果无法安全变到不相邻的车道，应怎样做？', choices:['保持限速不变','停车在原车道','减速到不超过公布限速低 20 mph，并谨慎通过','加速尽快离开'], answerIndex:2, explanation:'无法安全 Move Over 时，应按宾州规定显著减速，速度不应高于公布限速低 20 mph 的水平。' },
  { id:'pa-safety-003', category:'safety', question:'在宾州接近紧急响应区域，旁边有可安全使用的车道时，正确做法是什么？', choices:['驶离紧邻响应区域的车道','保持原车道并鸣笛','停车等待所有应急车辆离开','打开双闪后保持原车道速度'], answerIndex:0, explanation:'能够安全换道时，应驶离紧邻紧急响应区域的车道。' },
  { id:'pa-rules-006', category:'rules', question:'宾州驾驶记录累计到多少分时，PennDOT 的积分纠正程序会开始采取措施？', choices:['4 分','5 分','6 分','10 分'], answerIndex:2, explanation:'宾州 Point System 达到 6 points 时会触发相应的纠正措施。' },
  { id:'pa-rules-007', category:'rules', question:'宾州驾驶人连续 12 个月没有导致积分、停牌或吊销的违规时，驾驶记录通常可减少多少积分？', choices:['1 分','2 分','3 分','6 分'], answerIndex:2, explanation:'符合条件的连续 12 个月安全记录通常可从驾驶记录中减少 3 points。' },
  { id:'pa-rules-008', category:'rules', question:'在宾州，未满 18 岁驾驶人的驾驶记录达到 6 分时，可能发生什么？', choices:['不会有额外后果','可能受到额外的驾驶资格限制或停牌措施','自动获得正式驾照','只需支付停车罚款'], answerIndex:1, explanation:'宾州对未满 18 岁且达到 6 points 的驾驶人有更严格的处理规定。' },
  { id:'pa-rules-009', category:'rules', question:'在宾州申请普通非商业 learner’s permit，最低年龄通常是多少？', choices:['15 岁','15 岁半','16 岁','17 岁'], answerIndex:2, explanation:'宾州普通 learner’s permit 的最低申请年龄通常为 16 岁。' },
  { id:'pa-rules-010', category:'rules', question:'宾州未满 18 岁的 learner’s permit 持有人在参加路考前，通常需要累计至少多少小时监督驾驶？', choices:['30 小时','40 小时','50 小时','65 小时'], answerIndex:3, explanation:'未满 18 岁申请人通常需要至少 65 小时的监督驾驶经验。' },
  { id:'pa-rules-011', category:'rules', question:'宾州未满 18 岁驾驶人的 65 小时监督驾驶中，至少多少小时应为夜间驾驶？', choices:['5 小时','10 小时','15 小时','20 小时'], answerIndex:1, explanation:'65 小时监督驾驶中至少 10 小时应为夜间驾驶。' },
  { id:'pa-rules-012', category:'rules', question:'宾州未满 18 岁驾驶人的 65 小时监督驾驶中，至少多少小时应为恶劣天气驾驶？', choices:['5 小时','8 小时','10 小时','15 小时'], answerIndex:0, explanation:'65 小时监督驾驶中至少 5 小时应为恶劣天气驾驶。' },
  { id:'pa-rules-013', category:'rules', question:'宾州未满 18 岁的 learner’s permit 持有人通常必须持 permit 至少多久，才可以参加路考？', choices:['30 天','3 个月','6 个月','12 个月'], answerIndex:2, explanation:'未满 18 岁申请人通常需要持 learner’s permit 至少 6 个月并满足监督驾驶要求。' },
  { id:'pa-rules-014', category:'rules', question:'在宾州，校车黄色警示灯开始闪烁通常表示什么？', choices:['校车准备停车，应减速并准备停车','可以立即超越校车','只有对向车辆需要注意','校车已经结束上下学生'], answerIndex:0, explanation:'黄色校车警示灯表示校车正在准备停车，驾驶人应减速并做好停车准备。' },
  { id:'pa-rules-015', category:'rules', question:'宾州校车红灯停止闪烁、STOP ARM 收回后，在重新起步前最重要的是什么？', choices:['立即加速通过','确认儿童已经离开危险区域且道路安全','等待后车鸣笛','必须再等固定 5 分钟'], answerIndex:1, explanation:'校车信号结束后仍应确认儿童和道路状况安全再继续行驶。' },
  { id:'pa-rules-016', category:'rules', question:'在宾州路口附近遇到校车红灯闪烁并伸出 STOP ARM 时，哪项原则最安全且符合规则？', choices:['只与校车同一路段的车辆停车','接近该校车的车辆应按校车停车规则停车，除非适用实体隔离例外','只有校车后方车辆停车','只要你准备转弯就可继续'], answerIndex:1, explanation:'宾州校车停车规则适用于接近校车的交通，实体分隔道路的特定情形除外。' },
  { id:'pa-safety-004', category:'safety', question:'宾州 Move Over 规则下，看到道路旁有警灯闪烁的应急响应车辆时，首选做法是什么？', choices:['在安全情况下换到不相邻的车道','紧贴应急车辆通过','停车在应急车辆旁边','保持原车道并加速'], answerIndex:0, explanation:'首选是在安全可行时换到远离紧急响应区域的车道。' },
  { id:'pa-safety-005', category:'safety', question:'在宾州夜间驾驶时，什么时候应从远光灯切换到近光灯以避免影响其他驾驶人？', choices:['只有进入城市才需要','接近对向或前方车辆、远光可能造成眩目时','只有下雨时','永远不需要切换'], answerIndex:1, explanation:'远光灯不得妨碍其他驾驶人视线，接近其他车辆时应适时切换近光。' },
  { id:'pa-safety-006', category:'safety', question:'在宾州雨、雪、雾、烟或其他情况明显降低能见度时，正确的车灯做法是什么？', choices:['使用适当的前灯并降低速度','只打开停车灯','关闭灯避免反射','始终使用远光灯'], answerIndex:0, explanation:'低能见度环境应使用适当前灯并根据视距降低车速。' },
  { id:'pa-rules-017', category:'rules', question:'宾州驾驶人驶入有旗手控制的施工区域时，应怎么做？', choices:['服从旗手和临时交通控制指示','只遵守永久标线','如果没有施工车辆就忽略旗手','加速减少在施工区停留时间'], answerIndex:0, explanation:'施工区域必须遵守旗手和临时交通控制人员的指示。' },
  { id:'pa-rules-018', category:'rules', question:'在宾州施工区看到临时橙色交通标志时，它通常表示什么？', choices:['施工或维护相关的临时道路状况','医院服务','永久停车限制','州界'], answerIndex:0, explanation:'橙色标志通常用于道路施工、维护和临时交通控制警告。' },
  { id:'pa-rules-019', category:'rules', question:'在宾州学校区域看到黄色闪烁信号与 15 mph 标志正在生效时，你应怎么办？', choices:['降到不超过 15 mph','保持道路正常限速','只有看到儿童才减速','最低保持 20 mph'], answerIndex:0, explanation:'学校区域限速生效时应遵守 15 mph 的规定。' },
  { id:'pa-rules-020', category:'rules', question:'宾州驾驶人在学校区域违反正在生效的 15 mph 限速规定，可能会怎样？', choices:['不会计入驾驶记录','可能产生积分等处罚','只会收到口头警告','只影响商业驾照'], answerIndex:1, explanation:'学校区域超速属于交通违法，并可能产生驾驶记录积分等后果。' },
  { id:'pa-rules-021', category:'rules', question:'宾州驾驶人接近铁路道口，红灯闪烁或闸门正在下降时，应怎么办？', choices:['停车并等待信号结束且确认安全','绕过闸门','加速通过','只需鸣笛'], answerIndex:0, explanation:'铁路道口警示信号启动或闸门下降时必须停车等待。' },
  { id:'pa-rules-022', category:'rules', question:'宾州道路上看到八角形红色标志时，它表示什么？', choices:['STOP','YIELD','DO NOT ENTER','SCHOOL ZONE'], answerIndex:0, explanation:'八角形红色标志是 STOP 标志。' },
  { id:'pa-rules-023', category:'rules', question:'宾州道路上看到倒三角形标志时，它表示什么？', choices:['停车','让行','禁止超车','铁路道口'], answerIndex:1, explanation:'倒三角形是 YIELD 让行标志的独特形状。' },
  { id:'pa-rules-024', category:'rules', question:'宾州道路上黄色五边形标志通常提示什么？', choices:['学校区域或学校横道','医院','禁止驶入','州际公路出口'], answerIndex:0, explanation:'五边形学校标志用于提醒学校区域或学校横道。' },
  { id:'pa-rules-025', category:'rules', question:'宾州道路上黄色圆形、带黑色 X 和 RR 的标志表示什么？', choices:['前方铁路道口','前方环岛','禁止掉头','学校区域'], answerIndex:0, explanation:'圆形黄色 RR 标志是铁路道口提前警告标志。' },
  { id:'pa-rules-026', category:'rules', question:'宾州道路上看到黄色三角旗形 NO PASSING ZONE 标志时，应怎样做？', choices:['不要在该区域超车','只可从右侧超车','立即停车','仅卡车不得超车'], answerIndex:0, explanation:'三角旗形 NO PASSING ZONE 表示禁止超车区域。' },
  { id:'pa-safety-007', category:'safety', question:'在宾州湿滑道路上发生水滑现象时，较安全的处理方式是什么？', choices:['松开油门、保持方向稳定并避免急刹','立即猛踩刹车','快速左右转向','加速增加轮胎抓地'], answerIndex:0, explanation:'发生水滑时应平稳减速并避免突然制动或急转方向。' },
  { id:'pa-safety-008', category:'safety', question:'在宾州冬季道路可能结冰时，桥面和高架路段为什么需要特别谨慎？', choices:['它们通常比普通路面更早结冰','它们永远不会结冰','只有下雪时才会滑','桥面限速自动提高'], answerIndex:0, explanation:'桥梁和高架路面更容易、更早结冰，应提前降低速度。' },
  { id:'pa-safety-009', category:'safety', question:'宾州驾驶时车辆开始打滑，最重要的基本原则是什么？', choices:['避免突然制动和剧烈转向，平稳恢复控制','立即踩死刹车','迅速反复打方向','加速离开打滑区域'], answerIndex:0, explanation:'打滑时应避免突然操作，并平稳恢复车辆控制。' },
  { id:'pa-safety-010', category:'safety', question:'宾州山路下长坡时，为避免刹车过热，正确做法是什么？', choices:['使用较低挡位辅助控制车速','挂空挡滑行','一直轻踩油门','关闭发动机'], answerIndex:0, explanation:'长下坡使用较低挡位可利用发动机制动帮助控制速度，减少制动器过热风险。' },
  { id:'pa-rules-027', category:'rules', question:'在宾州，从私人车道驶入公共道路时，应让谁先行？', choices:['已经在公共道路上的车辆和行人','私人车道车辆永远优先','只让大型车辆','只让左侧车辆'], answerIndex:0, explanation:'从私人车道进入公共道路必须让道路上的交通和行人先行。' },
  { id:'pa-rules-028', category:'rules', question:'在宾州准备左转穿越对向车流时，应让谁先行？', choices:['对向直行车辆和行人','左转车辆永远优先','只让大型车辆','只让自行车'], answerIndex:0, explanation:'左转车辆应让对向直行交通以及相关行人先行。' },
  { id:'pa-rules-029', category:'rules', question:'宾州驾驶人在环岛入口准备进入时，应怎样做？', choices:['让已经在环岛内的交通先行','环岛外车辆优先','进入后停车让入口车辆','加速抢先进入'], answerIndex:0, explanation:'进入环岛前应减速，并让已经在环岛内的交通先行。' },
  { id:'pa-rules-030', category:'rules', question:'在宾州四向 STOP 路口，两车同时到达时通常应怎样处理？', choices:['让右侧车辆先行','让左侧车辆先行','两车同时进入','车辆较大者先行'], answerIndex:0, explanation:'同时到达停车路口时，一般应让右侧车辆先行。' },
  { id:'pa-rules-031', category:'rules', question:'在宾州超越自行车时，正确原则是什么？', choices:['留出安全空间，并只在条件允许时超越','紧贴自行车快速通过','鸣笛迫使骑车人离开道路','在弯道内立即超越'], answerIndex:0, explanation:'超越自行车必须留出安全空间并确认道路条件允许。' },
  { id:'pa-rules-032', category:'rules', question:'在宾州看到行人已经进入人行横道时，应怎么办？', choices:['减速或停车让行','从行人前方绕过','鸣笛让行人停下','保持速度通过'], answerIndex:0, explanation:'驾驶人必须注意并让正在合法使用人行横道的行人安全通过。' },
  { id:'pa-rules-033', category:'rules', question:'宾州驾驶人遇到使用白手杖或导盲犬的盲人行人时，应怎样做？', choices:['让行并准备停车','鸣笛后通过','从其前方快速通过','只有绿灯时才需要注意'], answerIndex:0, explanation:'遇到盲人行人应给予充分路权并准备停车。' },
  { id:'pa-safety-011', category:'safety', question:'宾州驾驶人在雾中行驶时应使用哪种灯光？', choices:['近光灯','远光灯','只开停车灯','不使用车灯'], answerIndex:0, explanation:'雾中远光容易反射造成眩光，应使用适当的近光灯。' },
  { id:'pa-safety-012', category:'safety', question:'宾州驾驶人在大雨中行驶时，跟车距离应该怎样变化？', choices:['增加','减少','保持完全不变','紧跟前车尾灯'], answerIndex:0, explanation:'湿滑和低能见度会增加停车距离，应扩大跟车空间。' },
  { id:'pa-safety-013', category:'safety', question:'在宾州驾驶时轮胎爆裂，较安全的第一反应是什么？', choices:['稳住方向盘并逐渐减速','立即猛踩刹车','快速驶向对向车道','马上关闭发动机'], answerIndex:0, explanation:'爆胎时应保持车辆方向稳定，避免突然制动并逐渐减速。' },
  { id:'pa-safety-014', category:'safety', question:'宾州驾驶时刹车突然失效，以下哪项较合理？', choices:['尝试降挡并逐步利用停车制动等方法降低车速','立即关闭方向盘锁','加速寻找上坡','跳车'], answerIndex:0, explanation:'制动失效时应保持控制，利用降挡和谨慎使用停车制动等方式逐步减速。' },
  { id:'pa-safety-015', category:'safety', question:'在宾州高速公路上错过出口时，正确做法是什么？', choices:['继续到下一个出口','在路肩倒车','停车等待空隙后倒回出口','突然跨越多条车道'], answerIndex:0, explanation:'错过出口后应继续前往下一个出口，不能倒车或突然横跨车道。' },
  { id:'pa-rules-034', category:'rules', question:'在宾州高速公路加速车道汇入主车流时，应怎样做？', choices:['调整到接近主车流速度并寻找安全空隙','在加速车道末端固定停车','以明显低于车流的速度直接并入','要求主车道车辆必须停车'], answerIndex:0, explanation:'加速车道用于匹配车流速度并安全汇入。' },
  { id:'pa-rules-035', category:'rules', question:'宾州驾驶人在铁路轨道另一侧没有足够空间容纳车辆时，应怎么办？', choices:['在轨道前等待','先开到轨道上等待','紧跟前车','鸣笛后驶上轨道'], answerIndex:0, explanation:'只有能够完全通过铁路轨道时才应进入道口。' },
  { id:'pa-rules-036', category:'rules', question:'在宾州看到交通警察指挥与交通信号灯不一致时，应服从什么？', choices:['交通警察的现场指挥','交通信号灯','前车的动作','导航软件'], answerIndex:0, explanation:'现场执法人员的交通指挥优先于普通交通信号。' },
  { id:'pa-safety-016', category:'safety', question:'宾州驾驶人在夜间被对向车辆远光灯影响视线时，较安全的做法是什么？', choices:['把视线适当移向道路右侧边缘并减速','直视对方车灯','关闭自己的车灯','加速尽快通过'], answerIndex:0, explanation:'避免直视眩光，并利用道路右侧作为方向参考，同时适当降低速度。' },
  { id:'pa-safety-017', category:'safety', question:'在宾州遇到鹿等动物突然进入道路时，最重要的原则是什么？', choices:['减速并保持车辆控制，避免危险的突然转向','高速从动物旁边绕过','关闭车灯','驶入对向车道躲避'], answerIndex:0, explanation:'应优先保持车辆控制并降低碰撞风险，避免可能造成更严重事故的突然转向。' },
  { id:'pa-safety-018', category:'safety', question:'宾州驾驶人在疲劳或困倦时，最安全的选择是什么？', choices:['在安全地点停车休息','打开车窗继续高速驾驶','提高音乐音量代替休息','喝水后立即继续长途驾驶'], answerIndex:0, explanation:'疲劳会明显降低反应能力，应在安全地点停车休息。' },
  { id:'pa-rules-037', category:'rules', question:'宾州驾驶人准备变更车道时，应按什么顺序完成安全检查？', choices:['观察镜子、打转向灯、检查盲区并确认安全后变道','先变道再打灯','只看后视镜','鸣笛后立即变道'], answerIndex:0, explanation:'安全变道需要观察交通、发出信号并检查盲区。' },
  { id:'pa-rules-038', category:'rules', question:'宾州驾驶人在没有足够空间完全通过前方路口时，应怎么办？', choices:['在进入路口前等待','驶入路口等待','紧跟前车','鸣笛要求前车移动'], answerIndex:0, explanation:'不能进入无法完全通过的路口，以免阻塞交叉交通。' },
  { id:'pa-safety-019', category:'safety', question:'宾州道路湿滑时，制动距离通常会怎样？', choices:['增加','减少','完全不变','只与车辆颜色有关'], answerIndex:0, explanation:'湿滑路面降低轮胎抓地力，通常需要更长的停车距离。' },
  { id:'pa-safety-020', category:'safety', question:'宾州驾驶人在结冰路面上需要转向或制动时，应怎样操作？', choices:['尽量平稳、渐进地操作','突然猛打方向','反复猛踩刹车','保持高速以防打滑'], answerIndex:0, explanation:'低附着路面应避免突然转向、加速或制动。' },
  { id:'pa-rules-039', category:'rules', question:'宾州道路上的白色车道线通常分隔什么交通？', choices:['同方向行驶的交通','相反方向交通','铁路轨道','人行横道'], answerIndex:0, explanation:'白色车道线通常分隔同方向交通。' },
  { id:'pa-rules-040', category:'rules', question:'宾州道路上的黄色中心线通常分隔什么交通？', choices:['相反方向行驶的交通','同方向交通','停车位','自行车与行人'], answerIndex:0, explanation:'黄色中心线通常用于分隔相反方向的交通。' },
  { id:'pa-rules-041', category:'rules', question:'宾州驾驶人看到红色闪烁交通信号时，应怎样处理？', choices:['像 STOP 标志一样完全停车后确认安全再通行','只减速','当作绿灯','加速通过'], answerIndex:0, explanation:'闪烁红灯按停车信号处理。' },
  { id:'pa-rules-042', category:'rules', question:'宾州驾驶人看到黄色闪烁交通信号时，应怎样处理？', choices:['减速并谨慎通过','必须完全停车','当作红灯','加速通过'], answerIndex:0, explanation:'闪烁黄灯要求减速并谨慎通行。' },
  { id:'pa-rules-043', category:'rules', question:'宾州驾驶人在绿灯亮起但路口仍被车辆堵住时，应怎么办？', choices:['等待直到有空间完全通过','驶入路口等待','鸣笛后进入','从路肩绕过'], answerIndex:0, explanation:'即使绿灯也不能进入无法完全通过的路口。' },
  { id:'pa-rules-044', category:'rules', question:'宾州驾驶人在 STOP 标志前应该在哪里停车？', choices:['在停止线、人行横道前或能安全观察交叉交通的位置完全停车','只要减速即可','驶入路口中央再停车','距离标志固定 50 英尺处'], answerIndex:0, explanation:'应在适当的停止位置完全停车，并确认安全后再通行。' },
  { id:'pa-rules-045', category:'rules', question:'宾州驾驶人从停车位倒车时，应怎样做？', choices:['观察后方和两侧、检查盲区并低速倒车','只依靠倒车摄像头','快速倒车','只看左侧后视镜'], answerIndex:0, explanation:'倒车时应直接观察周围环境并低速操作，不能只依赖摄像头。' },
  { id:'pa-safety-021', category:'safety', question:'宾州驾驶人在雨天进入积水区域前，应怎样做？', choices:['提前降低速度，避免突然制动或转向','加速冲过积水','在积水中猛踩刹车','紧跟大型车辆通过'], answerIndex:0, explanation:'积水可能造成水滑，应提前减速并保持平稳控制。' },
  { id:'pa-safety-022', category:'safety', question:'宾州驾驶人在雪天跟随除雪车时，应怎样做？', choices:['保持更大的安全距离并避免进入其盲区','紧跟以获得更干净的路面','立即从右侧路肩超越','关闭前灯避免反光'], answerIndex:0, explanation:'除雪车辆视野和操作范围有限，应保持额外空间。' },
  { id:'pa-rules-046', category:'rules', question:'宾州驾驶人在道路上听到并看到使用警灯和警报器的紧急车辆接近时，应怎样做？', choices:['安全让出通道并按规定靠边','加速跟随','停在路口中央','保持车速不变'], answerIndex:0, explanation:'应为执行任务的紧急车辆安全让出通道。' },
  { id:'pa-rules-047', category:'rules', question:'宾州驾驶人在红灯前准备右转时，应首先做什么？', choices:['完全停车，并确认没有禁止右转且可以安全让行后再转','直接慢速右转','鸣笛后右转','只看左侧车辆'], answerIndex:0, explanation:'红灯右转前必须先完全停车，并遵守标志及让行要求。' },
  { id:'pa-rules-048', category:'rules', question:'宾州驾驶人准备驶过没有信号灯的人行横道时看到行人正在过街，应怎么办？', choices:['停车或减速让行','从行人前方绕过','鸣笛让行人退回','保持速度'], answerIndex:0, explanation:'必须给予行人足够的安全通行空间。' },
  { id:'pa-safety-023', category:'safety', question:'宾州驾驶人在夜间发现前方可见距离缩短时，车速应怎样调整？', choices:['降低到能在可见范围内安全停车的速度','因为车少而提高速度','保持白天速度','只打开远光而不减速'], answerIndex:0, explanation:'夜间应根据可见距离控制车速，确保能在看得见的范围内停车。' },
  { id:'pa-safety-024', category:'safety', question:'宾州驾驶人在道路上发现前车突然减速时，保持足够跟车空间的主要作用是什么？', choices:['给自己留下反应和制动时间','防止其他车辆并线','减少使用转向灯','让自己更容易超速'], answerIndex:0, explanation:'足够跟车距离为观察、反应和制动提供时间。' },
  { id:'pa-rules-049', category:'rules', question:'宾州驾驶人看到道路施工人员给出 STOP/SLOW 指示牌时，应怎样做？', choices:['严格按指示停车或慢行','只看交通灯','如果没有警车就忽略','从路肩绕过'], answerIndex:0, explanation:'施工区旗手和交通控制人员的 STOP/SLOW 指示必须遵守。' },
  { id:'pa-rules-050', category:'rules', question:'宾州驾驶人在学校区域看到儿童靠近道路时，即使 15 mph 限速时段尚未开始，也应该怎样做？', choices:['提高警觉并根据情况减速准备停车','保持高速因为限速未生效','鸣笛要求儿童离开','驶到对向车道'], answerIndex:0, explanation:'接近儿童和学校区域应主动提高警觉并为突发情况留出反应空间。' },
  { id:'pa-safety-025', category:'safety', question:'宾州驾驶人在高速公路车辆发生故障并能安全离开行车道时，应怎么办？', choices:['尽量驶到安全位置并使用警示措施','停在行车道中央','立即站在车流一侧检查','在高速车道倒车'], answerIndex:0, explanation:'车辆故障时应尽量离开行车道，并提高自身及车辆可见性。' },
  { id:'pa-rules-051', category:'rules', question:'宾州驾驶人看到道路上的转向箭头时，应怎样使用所在车道？', choices:['按箭头所示方向使用车道','可以随意选择方向','箭头只适用于卡车','只有夜间需要遵守'], answerIndex:0, explanation:'车道箭头规定或提示该车道允许的行驶方向。' },
  { id:'pa-safety-026', category:'safety', question:'宾州驾驶人在结冰道路下坡时，最安全的速度控制方法是什么？', choices:['提前降低速度并平稳使用较低挡位和制动','下坡后再猛踩刹车','挂空挡滑行','加速保持车辆直线'], answerIndex:0, explanation:'冰雪下坡应提前控制速度，避免突然制动导致失控。' },
  { id:'pa-rules-052', category:'rules', question:'宾州驾驶人驶近 YIELD 标志时，应怎样做？', choices:['减速、准备停车并让有路权的交通先行','每次都必须完全停车','加速抢先进入','忽略横向行人'], answerIndex:0, explanation:'YIELD 要求让有路权的交通先行，必要时停车。' },
  { id:'pa-rules-053', category:'rules', question:'宾州驾驶人驶近 DO NOT ENTER 标志时，应怎样做？', choices:['不要驶入该道路或匝道','没车时可以进入','只在白天禁止进入','只限制卡车'], answerIndex:0, explanation:'DO NOT ENTER 表示禁止从该方向驶入。' },
  { id:'pa-rules-054', category:'rules', question:'宾州驾驶人看到 WRONG WAY 标志时，应怎样做？', choices:['安全停止并纠正行驶方向','继续到下一个出口','加速离开','停在原车道等待'], answerIndex:0, explanation:'WRONG WAY 表示车辆正朝错误方向行驶，应安全纠正。' },
  { id:'pa-safety-027', category:'safety', question:'宾州驾驶人在太阳眩光严重影响视线时，应怎样做？', choices:['减速、增加跟车距离并使用遮阳板等措施','闭一只眼保持速度','打开远光灯','紧跟前车'], answerIndex:0, explanation:'视线受眩光影响时应降低速度并增加安全空间。' },
  { id:'pa-safety-028', category:'safety', question:'宾州驾驶人在强降雨中发现前方车辆越来越难看清时，应怎样做？', choices:['降低速度并增加跟车距离','打开远光并保持速度','紧跟前车尾灯','加速离开雨区'], answerIndex:0, explanation:'强降雨会降低能见度和抓地力，应减速并增加距离。' },
  { id:'pa-rules-055', category:'rules', question:'宾州驾驶人准备在多车道路口左转时，哪项做法正确？', choices:['提前进入正确车道、打转向灯并让对向交通和行人','从任意车道突然左转','先进入对向车道等待','只有大型车辆需要打灯'], answerIndex:0, explanation:'左转应提前选择正确车道、发出信号并依法让行。' },
  { id:'pa-safety-029', category:'safety', question:'宾州驾驶人发现前方道路被洪水覆盖且无法判断水深时，应怎么办？', choices:['不要冒险驶入，选择安全路线绕行','低速试探通过','跟随大型卡车通过','加速冲过'], answerIndex:0, explanation:'无法判断积水深度和路况时，不应冒险驶入被洪水覆盖的道路。' },
  { id:'pa-safety-030', category:'safety', question:'宾州驾驶人在积雪道路起步时，怎样减少车轮打滑？', choices:['平稳、缓慢加速','猛踩油门','快速反复转向','关闭所有电子辅助并高速起步'], answerIndex:0, explanation:'低附着路面应平稳使用油门，避免突然增加驱动力。' },
]
