import type { DmvEnglishContent } from './dmv-language'

export const pennsylvaniaEnglishById: Record<string, DmvEnglishContent> = {
  'pa-bus-001': { question: 'In Pennsylvania, when a school bus is stopped with red lights flashing and the STOP ARM extended, how far away must you normally stop?', choices: ['5 feet','10 feet','15 feet','25 feet'], explanation: 'Pennsylvania normally requires drivers to stop at least 10 feet from a stopped school bus displaying flashing red lights and an extended stop arm.' },
  'pa-bus-002': { question: 'On a two-way road in Pennsylvania, an oncoming school bus is stopped with red lights flashing and the STOP ARM extended. There is no physical median. What must you do?', choices: ['Stop and wait','Slow to 15 mph and pass','Pass if no children are visible','Honk and pass'], explanation: 'Without a physical barrier, traffic approaching from either direction must stop for the school bus.' },
  'pa-bus-003': { question: 'In Pennsylvania, you are traveling in the opposite direction from a stopped school bus on a divided highway with a physical median. The bus has flashing red lights and an extended STOP ARM. What should you normally do?', choices: ['You must still stop','You may proceed cautiously','You must make a U-turn','You must stop for five minutes'], explanation: 'Opposing traffic normally does not have to stop when a physical barrier separates it from the school bus.' },
  'pa-bus-004': { question: 'What should a Pennsylvania driver do when a school bus begins flashing its yellow warning lights?', choices: ['Slow down and prepare to stop','Pass immediately','Maintain the same speed','Only opposing traffic must stop'], explanation: 'Yellow warning lights mean the school bus is preparing to stop, so drivers should slow down and be ready to stop.' },
  'pa-bus-005': { question: 'After a Pennsylvania school bus stops flashing red lights and retracts its STOP ARM, what should you still confirm before proceeding?', choices: ['Children have reached a safe location','The vehicle behind you has started moving','The bus driver has honked','A fixed 60 seconds has passed'], explanation: 'Drivers should make sure children have reached a safe location before proceeding.' },
  'pa-bus-006': { question: 'In Pennsylvania, when approaching an intersection where a school bus is stopped with flashing red lights and an extended STOP ARM, what should you do?', choices: ['Follow the school-bus stopping rule and stop','Only vehicles directly behind the bus must stop','Only right-turning vehicles must stop','Proceed if you have a green light'], explanation: 'Pennsylvania school-bus stopping rules also apply to drivers approaching an intersection where the bus is stopped.' },
  'pa-bus-007': { question: 'In Pennsylvania, what can happen if you illegally pass a stopped school bus displaying flashing red lights and an extended STOP ARM?', choices: ['Only a verbal warning','Points, a fine, and possible license suspension','Only higher insurance premiums','Only commercial drivers are affected'], explanation: 'Pennsylvania imposes serious penalties for illegally passing a stopped school bus, including points, fines, and possible suspension.' },

  'pa-school-001': { question: 'When a Pennsylvania school-zone speed limit is in effect, what is the usual maximum speed?', choices: ['10 mph','15 mph','20 mph','25 mph'], explanation: 'Pennsylvania school zones are generally limited to 15 mph when the school-zone restriction is in effect.' },
  'pa-school-002': { question: 'What should you do when Pennsylvania school-zone yellow lights are flashing?', choices: ['Obey the 15 mph school-zone limit','Keep the normal posted road speed','Slow only if children are visible','Maintain at least 20 mph'], explanation: 'When the school-zone warning lights are active, drivers must obey the 15 mph school-zone limit.' },
  'pa-school-003': { question: 'In Pennsylvania, speeding in an active school zone normally adds how many points to your driving record?', choices: ['1 point','2 points','3 points','5 points'], explanation: 'PennDOT states that speeding in a school zone results in 3 points.' },

  'pa-light-001': { question: 'In Pennsylvania, if your windshield wipers are operating continuously or intermittently because of weather, what else must you do?', choices: ['Turn on your headlights','Use parking lights only','Use high beams','Turn off the taillights'], explanation: 'Pennsylvania requires headlights to be on when windshield wipers are in use because of weather.' },
  'pa-light-002': { question: 'What type of headlights should you use in Pennsylvania during rain, snow, fog, smoke, hail, or other low-visibility conditions?', choices: ['Low beams','High beams','Parking lights only','No lights'], explanation: 'Use headlights in low-visibility weather, generally with low beams because high beams can reflect back and reduce visibility.' },
  'pa-light-003': { question: 'Which statement about headlights in a Pennsylvania work zone is correct?', choices: ['Headlights must be on','Headlights are never required during daytime','Daytime running lights alone are enough','Only hazard flashers are required'], explanation: 'Pennsylvania requires drivers to use headlights in posted work zones.' },
  'pa-light-004': { question: 'In Pennsylvania, headlights are required when you cannot clearly see people or vehicles how far ahead?', choices: ['500 feet','750 feet','1,000 feet','1,500 feet'], explanation: 'Pennsylvania law requires headlights when you cannot see people or vehicles at least 1,000 feet ahead.' },
  'pa-light-005': { question: 'In Pennsylvania, are daytime running lights alone enough to satisfy the headlight requirement in bad weather?', choices: ['Yes','No, because the taillights also need to be illuminated','Only during daytime','Only on highways'], explanation: 'PennDOT notes that daytime running lights are not enough because the full lighting system, including taillights, must be illuminated.' },

  'pa-move-001': { question: 'Under Pennsylvania Move Over law, what should you do when approaching an emergency response area and you can safely change lanes?', choices: ['Move into a lane not adjacent to the response area','Stay in the same lane at the same speed','Stop behind the emergency vehicle','Turn on hazard lights and stay in your lane'], explanation: 'When it is safe to do so, move into a lane farther away from the emergency response area.' },
  'pa-move-002': { question: 'In Pennsylvania, if you cannot safely move over when approaching an emergency response area, how should you control your speed?', choices: ['Drive no more than 20 mph below the posted limit and at a reasonable safe speed','Maintain the posted speed limit','Come to a complete stop','Slow by only 5 mph'], explanation: 'If you cannot safely move over, Pennsylvania requires a speed no more than 20 mph below the posted limit and otherwise reasonable for conditions.' },
  'pa-move-003': { question: 'In Pennsylvania, failing to move out of a lane next to an emergency response area can result in how many points?', choices: ['1 point','2 points','3 points','5 points'], explanation: 'Pennsylvania Move Over violations can result in 2 points.' },

  'pa-points-001': { question: 'At how many points does PennDOT begin taking corrective action under Pennsylvania\'s point system?', choices: ['4 points','5 points','6 points','8 points'], explanation: 'PennDOT begins corrective action when a driving record reaches 6 points.' },
  'pa-points-002': { question: 'In Pennsylvania, how many points are normally removed after 12 consecutive months without a violation that results in points, suspension, or revocation?', choices: ['1 point','2 points','3 points','6 points'], explanation: 'Three points are normally removed after each qualifying 12-month violation-free period.' },
  'pa-points-003': { question: 'When a Pennsylvania driver reaches 6 or more points for the first time, what may the driver be required to do?', choices: ['Take a Special Point Examination or attend Driver Improvement School','Retake the road test','Reapply for vehicle registration','Buy a new insurance policy'], explanation: 'A first-time 6-point driver may be directed to a Special Point Examination or Driver Improvement School.' },
  'pa-points-004': { question: 'What may happen to a Pennsylvania driver under age 18 who reaches 6 or more points?', choices: ['Driving privileges may be suspended','The record automatically drops to 3 points','Only a parking fine is issued','There is no additional consequence'], explanation: 'Pennsylvania has stricter suspension rules for drivers under 18 who reach 6 points.' },
  'pa-points-005': { question: 'What may happen to a Pennsylvania driver under age 18 who is convicted of driving 26 mph or more over the posted speed limit?', choices: ['Driving privileges may be suspended','Only a warning is issued','Only 1 point is added','The driver automatically receives an unrestricted license'], explanation: 'Pennsylvania provides for suspension consequences for drivers under 18 convicted of driving 26 mph or more over the posted limit.' },
  'pa-points-006': { question: 'For a Pennsylvania driver under age 18, how long is the first suspension normally imposed for reaching 6 points or triggering the serious-speeding rule?', choices: ['30 days','60 days','90 days','120 days'], explanation: 'The first suspension under this under-18 rule is normally 90 days.' },

  'pa-junior-001': { question: 'What is the usual minimum age to apply for a Pennsylvania non-commercial learner\'s permit?', choices: ['15','15½','16','17'], explanation: 'The usual minimum age for a Pennsylvania non-commercial learner\'s permit is 16.' },
  'pa-junior-002': { question: 'Before taking the road test, how many hours of supervised driving are normally required for a Pennsylvania applicant under age 18?', choices: ['40 hours','50 hours','60 hours','65 hours'], explanation: 'Pennsylvania normally requires at least 65 hours of supervised driving for applicants under 18.' },
  'pa-junior-003': { question: 'Of the supervised driving required for a Pennsylvania applicant under age 18, how many hours must normally be completed at night?', choices: ['5 hours','10 hours','15 hours','20 hours'], explanation: 'At least 10 hours of the 65 supervised-driving hours must be at night.' },
  'pa-junior-004': { question: 'Of the supervised driving required for a Pennsylvania applicant under age 18, how many hours must normally be completed in poor weather?', choices: ['5 hours','10 hours','15 hours','20 hours'], explanation: 'At least 5 hours of the 65 supervised-driving hours must be in poor weather.' },
  'pa-junior-005': { question: 'How long must a Pennsylvania learner\'s permit holder under age 18 normally hold the permit before taking the road test?', choices: ['30 days','3 months','6 months','12 months'], explanation: 'An applicant under 18 normally must hold the learner\'s permit for at least 6 months.' },

  'pa-park-001': { question: 'When parallel parking on a Pennsylvania street with a curb, how close should your vehicle normally be to the curb?', choices: ['Within 6 inches','Within 12 inches','Within 18 inches','Within 24 inches'], explanation: 'PennDOT advises parking as close as practical to the curb and no more than 12 inches away.' },
  'pa-park-002': { question: 'In Pennsylvania, how far away must you park from a fire hydrant?', choices: ['At least 10 feet','At least 15 feet','At least 20 feet','At least 30 feet'], explanation: 'Parking is prohibited within 15 feet of a fire hydrant.' },
  'pa-park-003': { question: 'In Pennsylvania, how far away must you park from a crosswalk at an intersection?', choices: ['At least 10 feet','At least 15 feet','At least 20 feet','At least 30 feet'], explanation: 'Parking is prohibited within 20 feet of a crosswalk at an intersection.' },
  'pa-park-004': { question: 'In Pennsylvania, how far away must you park from a STOP sign, YIELD sign, flashing signal, or other traffic-control device at the roadside?', choices: ['At least 15 feet','At least 20 feet','At least 30 feet','At least 50 feet'], explanation: 'Parking is prohibited within 30 feet of these traffic-control devices.' },
  'pa-park-005': { question: 'In Pennsylvania, how far away must you park from the nearest rail of a railroad crossing?', choices: ['At least 20 feet','At least 30 feet','At least 40 feet','At least 50 feet'], explanation: 'Parking is prohibited within 50 feet of the nearest rail of a railroad crossing.' },
  'pa-park-006': { question: 'When parking downhill in Pennsylvania, which way should the front wheels normally be turned?', choices: ['To the right','To the left','Straight ahead','Toward the center of the road'], explanation: 'PennDOT instructs drivers to turn the front wheels fully to the right when parking downhill.' },

  'pa-speed-001': { question: 'What is the highest posted speed limit that may be used on some Pennsylvania highways?', choices: ['55 mph','60 mph','65 mph','70 mph'], explanation: 'Some Pennsylvania highways may have a posted speed limit as high as 70 mph.' },
  'pa-speed-002': { question: 'In Pennsylvania, can you still be cited for driving too fast for conditions even if you are below the posted speed limit?', choices: ['Yes','No','Only on highways','Only in commercial vehicles'], explanation: 'PennDOT explains that a driver can be cited for traveling too fast for conditions even when below the posted limit.' },

  'pa-work-001': { question: 'In a Pennsylvania work zone, if a flagger\'s direction conflicts with existing pavement markings, what should you obey?', choices: ['The flagger or temporary traffic-control direction','The old pavement markings','Your navigation app','The vehicle in front of you'], explanation: 'Drivers must follow flaggers and temporary traffic-control directions in work zones.' },
  'pa-work-002': { question: 'What do orange traffic signs in Pennsylvania generally indicate?', choices: ['Road work, maintenance, or temporary traffic-control conditions','Hospital services','A school zone','An interstate highway number'], explanation: 'Orange signs are used for construction, maintenance, and temporary traffic-control warnings.' },
}
