import type { DmvQuestion } from './dmv-data'

type TxQuestion = DmvQuestion & { en: { question: string; choices: string[]; explanation: string }; keywords?: { term: string; zh: string }[] }

export const texasQuestions: TxQuestion[] = [
  { id:'tx-move-001', category:'safety', question:'在德州接近路边停靠并闪烁警示灯的紧急车辆时，如果道路有多条同向车道，最正确的做法是什么？', choices:['保持原车道原速通过','在安全可行时移到远离该车辆的车道','停车在该车辆后方','驶上路肩'], answerIndex:1, explanation:'Texas Move Over/Slow Down 规则要求在多车道道路上，安全可行时移到远离停靠应急车辆的车道。', en:{question:'When approaching a stopped emergency vehicle with warning lights in Texas on a multilane road, what should you do?',choices:['Stay in the same lane at the same speed','Move to a lane farther away when it is safe','Stop behind the vehicle','Drive on the shoulder'],explanation:'Texas Move Over/Slow Down law requires drivers to move to a lane farther away when it is safe to do so.'}, keywords:[{term:'move over',zh:'变道避让'}]},
  { id:'tx-move-002', category:'safety', question:'如果无法安全变道避让德州路边停靠的应急车辆，且限速为 55 mph，你通常应至少降到多少？', choices:['50 mph','45 mph','35 mph','25 mph'], answerIndex:2, explanation:'无法变道时通常应将车速降到限速以下 20 mph，因此 55 mph 路段应降至 35 mph 或更低。', en:{question:'If you cannot safely move over for a stopped emergency vehicle in Texas and the speed limit is 55 mph, to what speed should you slow?',choices:['50 mph','45 mph','35 mph','25 mph'],explanation:'If you cannot move over, Texas law generally requires slowing to 20 mph below the posted limit, so 35 mph or less here.'}, keywords:[{term:'posted speed limit',zh:'公布限速'}]},
  { id:'tx-move-003', category:'safety', question:'德州限速低于 25 mph 的道路上，无法变道避让停靠应急车辆时，通常应降到多少？', choices:['5 mph','10 mph','15 mph','20 mph'], answerIndex:0, explanation:'当限速低于 25 mph 时，Move Over/Slow Down 规则要求降到 5 mph。', en:{question:'On a Texas road with a speed limit below 25 mph, how slow should you go if you cannot move over for a stopped emergency vehicle?',choices:['5 mph','10 mph','15 mph','20 mph'],explanation:'When the posted speed is below 25 mph, Texas law requires slowing to 5 mph.'}},
  { id:'tx-bus-001', category:'rules', question:'德州校车停下并交替闪红灯时，接近车辆通常应该怎么做？', choices:['减速通过','停车等待','鸣笛通过','只在看到儿童时停车'], answerIndex:1, explanation:'校车交替闪红灯时，接近车辆必须停车，直到校车继续行驶、红灯停止或司机示意通行。', en:{question:'What should a driver normally do when approaching a stopped Texas school bus with alternating flashing red lights?',choices:['Slow and pass','Stop and wait','Honk and pass','Stop only if children are visible'],explanation:'Drivers must stop for a school bus displaying alternating flashing red lights and remain stopped until it is lawful and safe to proceed.'}},
  { id:'tx-bus-002', category:'rules', question:'德州道路中间只有一条双向左转中心车道时，对向车辆遇闪红灯校车可以不停吗？', choices:['可以','不可以','只有白天可以','只有限速低于30 mph可以'], answerIndex:1, explanation:'单独的 center left-turn lane 不构成实体分隔道路，对向车辆仍应停车。', en:{question:'In Texas, if a roadway is separated only by a center left-turn lane, may opposing traffic continue past a school bus with flashing red lights?',choices:['Yes','No','Only during daylight','Only below 30 mph'],explanation:'A center left-turn lane does not make the roadway physically divided, so opposing traffic must still stop.'}, keywords:[{term:'divided highway',zh:'分隔道路'}]},
  { id:'tx-bus-003', category:'rules', question:'德州哪种道路情况下，校车另一侧对向车辆通常可以不停车？', choices:['只有黄色中心线','道路有实体隔离带或明显物理分隔','只有中心转弯车道','夜间'], answerIndex:1, explanation:'只有道路由实体 barrier、median 或实际空间分隔时，对向交通通常才可继续。', en:{question:'In Texas, when may opposing traffic normally continue past a stopped school bus?',choices:['When there is only a yellow centerline','When the roadway is physically divided by a median, barrier, or separate roadway','When there is only a center turn lane','At night'],explanation:'Opposing traffic is generally excepted only when the roadway is physically divided.'}},
  { id:'tx-teen-001', category:'rules', question:'德州青少年通常最早多少岁可以取得 learner license？', choices:['14岁','15岁','16岁','17岁'], answerIndex:1, explanation:'Texas teen learner license 通常最低年龄为 15 岁，并需满足相应 Driver Education 要求。', en:{question:'What is the usual minimum age for a Texas teen learner license?',choices:['14','15','16','17'],explanation:'A Texas teen learner license is generally available starting at age 15, subject to driver education requirements.'}},
  { id:'tx-teen-002', category:'rules', question:'德州 learner license 持有人练习驾驶时，前排陪同驾驶人通常至少要多少岁？', choices:['18岁','20岁','21岁','25岁'], answerIndex:2, explanation:'陪同人通常必须至少 21 岁、持有效驾照，并有至少一年驾驶经验。', en:{question:'How old must the front-seat accompanying driver normally be for a Texas learner license holder?',choices:['18','20','21','25'],explanation:'The accompanying driver normally must be at least 21, properly licensed, and have at least one year of driving experience.'}},
  { id:'tx-teen-003', category:'rules', question:'德州 teen learner license 通常至少要持有多久，才能申请 provisional license？', choices:['30天','3个月','6个月','12个月'], answerIndex:2, explanation:'通常必须持有 learner license 至少 6 个月。', en:{question:'How long must a Texas teen normally hold a learner license before applying for a provisional license?',choices:['30 days','3 months','6 months','12 months'],explanation:'A Texas teen normally must hold the learner license for at least 6 months.'}},
  { id:'tx-teen-004', category:'rules', question:'德州青少年驾驶训练通常要求多少小时监督驾驶？', choices:['20小时','30小时','40小时','50小时'], answerIndex:1, explanation:'通常需要 30 小时监督驾驶，其中至少 10 小时在夜间完成。', en:{question:'How many hours of supervised driving are normally required for a Texas teen driver?',choices:['20','30','40','50'],explanation:'Texas teen driver education generally requires 30 hours of supervised driving, including at least 10 hours at night.'}},
  { id:'tx-teen-005', category:'rules', question:'德州青少年监督驾驶的 30 小时中，至少多少小时必须在夜间完成？', choices:['5小时','10小时','15小时','20小时'], answerIndex:1, explanation:'至少 10 小时需要在夜间完成。', en:{question:'Of the 30 supervised driving hours for a Texas teen, how many must be completed at night?',choices:['5','10','15','20'],explanation:'At least 10 of the 30 supervised driving hours must be completed at night.'}},
  { id:'tx-prov-001', category:'rules', question:'德州 provisional license 持有人通常最多可搭载几名未满21岁的非家庭成员？', choices:['0名','1名','2名','3名'], answerIndex:1, explanation:'通常最多允许 1 名未满 21 岁的非家庭成员乘客。', en:{question:'How many passengers under 21 who are not family members may a Texas provisional license holder normally carry?',choices:['0','1','2','3'],explanation:'A Texas provisional license holder is generally limited to one passenger under 21 who is not a family member.'}, keywords:[{term:'provisional license',zh:'阶段性/临时驾照'}]},
  { id:'tx-prov-002', category:'rules', question:'德州 provisional license 持有人通常在哪个时间段限制驾驶？', choices:['10 p.m.–4 a.m.','11 p.m.–5 a.m.','12 a.m.–5 a.m.','1 a.m.–6 a.m.'], answerIndex:2, explanation:'通常在午夜 12:00 到早上 5:00 限制驾驶，工作、学校活动或紧急情况等可有例外。', en:{question:'During what hours is a Texas provisional license holder normally restricted from driving?',choices:['10 p.m.–4 a.m.','11 p.m.–5 a.m.','12 a.m.–5 a.m.','1 a.m.–6 a.m.'],explanation:'Driving is generally restricted from midnight to 5 a.m., with exceptions such as work, school activities, or emergencies.'}},
  { id:'tx-phone-001', category:'safety', question:'德州 learner/provisional 青少年驾驶人能否在开车时使用 hands-free 手机？', choices:['可以','通常不可以，紧急情况除外','只有白天可以','只有导航可以'], answerIndex:1, explanation:'未满 18 岁驾驶人使用无线通信设备受到严格限制，包括 hands-free，紧急情况除外。', en:{question:'May a Texas learner or provisional teen driver use a hands-free phone while driving?',choices:['Yes','Generally no, except in an emergency','Only during daylight','Only for navigation'],explanation:'Drivers under 18 are subject to strict mobile-device restrictions, including hands-free use, except for emergencies.'}},
  { id:'tx-phone-002', category:'safety', question:'一般德州驾驶人在车辆仍处于行驶状态时发送或读取电子消息是否合法？', choices:['合法','通常不合法','只有高速公路不合法','只有夜间不合法'], answerIndex:1, explanation:'Texas law 禁止驾驶过程中读取、书写或发送电子消息，除非车辆已经停下。', en:{question:'Is it generally legal for a Texas driver to read, write, or send an electronic message while the vehicle is moving?',choices:['Yes','Generally no','Only illegal on freeways','Only illegal at night'],explanation:'Texas law prohibits reading, writing, or sending electronic messages while driving unless the vehicle is stopped.'}},
  { id:'tx-dui-001', category:'safety', question:'德州21岁以下驾驶人适用什么酒精政策？', choices:['0.08%标准','Zero Tolerance 零容忍','只要不醉就可以','0.05%标准'], answerIndex:1, explanation:'Texas 对未满21岁实行 Zero Tolerance，检测到任何酒精都可能触发 DUI by a Minor。', en:{question:'What alcohol policy applies to Texas drivers under age 21?',choices:['0.08% standard','Zero Tolerance','Any amount is allowed if not intoxicated','0.05% standard'],explanation:'Texas applies a Zero Tolerance policy to drivers under 21; any detectable alcohol can trigger DUI by a Minor consequences.'}, keywords:[{term:'zero tolerance',zh:'零容忍'}]},
  { id:'tx-dui-002', category:'safety', question:'德州21岁及以上驾驶人的一般 BAC 法律标准是多少？', choices:['0.02%','0.05%','0.08%','0.10%'], answerIndex:2, explanation:'21岁及以上驾驶人 BAC 0.08% 或更高通常构成法律上 intoxicated 的标准之一。', en:{question:'What is the general BAC legal threshold for a Texas driver age 21 or older?',choices:['0.02%','0.05%','0.08%','0.10%'],explanation:'A BAC of 0.08% or higher is one legal standard for intoxication for drivers age 21 or older in Texas.'}, keywords:[{term:'intoxicated',zh:'醉酒/受酒精影响'}]},
  { id:'tx-seat-001', category:'safety', question:'德州一般要求车辆中的乘员怎么做？', choices:['只有驾驶人系安全带','只有前排系安全带','按法律要求系安全带或使用合适儿童约束装置','短途无需约束'], answerIndex:2, explanation:'驾驶人和乘客应按德州法律使用安全带，儿童应使用符合年龄和身高要求的约束系统。', en:{question:'What does Texas generally require vehicle occupants to do?',choices:['Only the driver must buckle up','Only front-seat occupants must buckle up','Use seat belts or an appropriate child restraint as required by law','No restraint is needed for short trips'],explanation:'Drivers and passengers must use seat belts as required, and children must use appropriate child restraints.'}},
  { id:'tx-intersection-001', category:'rules', question:'德州无信号四向停车路口，两车同时到达时，通常谁先行？', choices:['左侧车辆','右侧车辆','大型车辆','速度快的车辆'], answerIndex:1, explanation:'同时到达时通常让右侧车辆先行。', en:{question:'At a Texas four-way stop, if two vehicles arrive at the same time, who normally goes first?',choices:['The vehicle on the left','The vehicle on the right','The larger vehicle','The faster vehicle'],explanation:'When vehicles arrive at the same time, the vehicle on the left generally yields to the vehicle on the right.'}},
  { id:'tx-rail-001', category:'rules', question:'铁路道口红灯闪烁或栏杆下降时，德州驾驶人应该怎么做？', choices:['加速通过','停车并等待','绕过栏杆','鸣笛后通过'], answerIndex:1, explanation:'红灯闪烁或栏杆下降时必须停车等待列车通过。', en:{question:'What should a Texas driver do when railroad crossing lights are flashing or gates are lowered?',choices:['Accelerate through','Stop and wait','Drive around the gate','Honk and proceed'],explanation:'Drivers must stop and wait when railroad crossing lights are flashing or gates are lowered.'}},
  { id:'tx-rail-002', category:'rules', question:'铁路道口前方拥堵、无法保证完全通过时，正确做法是什么？', choices:['先驶上铁轨等待','在铁轨前等待直到前方有足够空间','紧跟前车','驶到对向车道'], answerIndex:1, explanation:'绝不能停在铁轨上；只有确认能够完全通过时才进入道口。', en:{question:'What should you do if traffic is backed up beyond a railroad crossing and you cannot completely clear the tracks?',choices:['Enter the tracks and wait','Wait before the tracks until there is enough room to cross completely','Follow closely','Use the oncoming lane'],explanation:'Never stop on railroad tracks; enter only when there is enough room to clear the crossing.'}},
  { id:'tx-sign-001', category:'signs', question:'红色八角形 STOP 标志要求什么？', choices:['减速','完全停车','鸣笛','只让行'], answerIndex:1, explanation:'必须在停止线、横道前或安全观察位置完全停车。', en:{question:'What does a red octagonal STOP sign require?',choices:['Slow down','Come to a complete stop','Honk','Yield only'],explanation:'You must come to a complete stop at the stop line, before the crosswalk, or at a safe observation point.'}},
  { id:'tx-sign-002', category:'signs', question:'红白倒三角 YIELD 标志表示什么？', choices:['完全停车','减速并让有优先权的交通先行','禁止进入','施工区'], answerIndex:1, explanation:'YIELD 表示减速，必要时停车，并让有路权的车辆或行人先行。', en:{question:'What does a red-and-white triangular YIELD sign mean?',choices:['Come to a complete stop','Slow down and yield to traffic with the right-of-way','Do not enter','Construction zone'],explanation:'YIELD means slow down, be ready to stop, and give the right-of-way when required.'}},
  { id:'tx-sign-003', category:'signs', question:'橙色道路标志通常表示什么？', choices:['施工或临时交通控制','医院','学校','休息区'], answerIndex:0, explanation:'橙色通常用于施工、维护和临时交通控制。', en:{question:'What do orange road signs generally indicate?',choices:['Construction or temporary traffic control','Hospital','School','Rest area'],explanation:'Orange signs generally indicate construction, maintenance, or temporary traffic control.'}},
  { id:'tx-sign-004', category:'signs', question:'黄色菱形标志通常表示什么？', choices:['警告前方道路状况','停车许可','服务设施','车辆登记'], answerIndex:0, explanation:'黄色菱形通常是 warning sign。', en:{question:'What does a yellow diamond-shaped sign generally mean?',choices:['Warning of road conditions ahead','Parking permit','Service facility','Vehicle registration'],explanation:'Yellow diamond-shaped signs are generally warning signs.'}},
]
