import type { DmvQuestion } from './dmv-data'

type TxQuestion = DmvQuestion & { en: { question: string; choices: string[]; explanation: string } }

export const texasSpeedQuestions: TxQuestion[] = [
  { id:'tx-speed-001', category:'rules', question:'德州一般 urban district 的默认最高限速通常是多少？', choices:['20 mph','25 mph','30 mph','35 mph'], answerIndex:2, explanation:'Texas Driver Handbook 的速度表列出 urban district 通常为 30 mph，除非现场另有标志。', en:{question:'What is the usual default maximum speed limit in a Texas urban district?',choices:['20 mph','25 mph','30 mph','35 mph'],explanation:'The Texas Driver Handbook lists 30 mph for an urban district unless otherwise posted.'}},
  { id:'tx-speed-002', category:'rules', question:'德州 alley（巷道）的默认最高限速通常是多少？', choices:['10 mph','15 mph','20 mph','25 mph'], answerIndex:1, explanation:'Texas Driver Handbook 列出 alley 通常为 15 mph。', en:{question:'What is the usual maximum speed limit in a Texas alley?',choices:['10 mph','15 mph','20 mph','25 mph'],explanation:'The Texas Driver Handbook lists 15 mph for an alley.'}},
  { id:'tx-speed-003', category:'rules', question:'德州城市以外、由 Texas 或 U.S. 编号的公路，普通乘用车默认最高限速通常是多少？', choices:['55 mph','60 mph','65 mph','70 mph'], answerIndex:3, explanation:'Texas Driver Handbook 速度表列出这类道路通常为 70 mph，除非另有标志。', en:{question:'What is the usual maximum speed limit for a passenger car on a Texas- or U.S.-numbered highway outside an urban district?',choices:['55 mph','60 mph','65 mph','70 mph'],explanation:'The Texas Driver Handbook lists 70 mph for this type of roadway unless otherwise posted.'}},
  { id:'tx-speed-004', category:'rules', question:'德州城市以外、不是 Texas 或 U.S. 编号的公路，普通乘用车默认最高限速通常是多少？', choices:['50 mph','55 mph','60 mph','70 mph'], answerIndex:2, explanation:'Texas Driver Handbook 通常列为 60 mph，除非现场另有规定。', en:{question:'What is the usual maximum speed limit for a passenger car on a highway outside an urban district that is not numbered by Texas or the U.S.?',choices:['50 mph','55 mph','60 mph','70 mph'],explanation:'The Texas Driver Handbook generally lists 60 mph for this roadway type unless otherwise posted.'}},
  { id:'tx-follow-001', category:'safety', question:'在良好路况下以 30 mph 或更低速度行驶时，Texas Driver Handbook 建议至少保持多少秒跟车间隔？', choices:['1秒','2秒','3秒','4秒'], answerIndex:1, explanation:'30 mph 或更低时，良好路况下最低建议约 2 秒。', en:{question:'Under good road conditions at 30 mph or less, what minimum following interval does the Texas Driver Handbook recommend?',choices:['1 second','2 seconds','3 seconds','4 seconds'],explanation:'At 30 mph or less, the handbook recommends a minimum interval of about 2 seconds in good conditions.'}},
  { id:'tx-follow-002', category:'safety', question:'在良好路况下速度高于 30 mph 时，Texas Driver Handbook 建议保持多少秒跟车间隔？', choices:['2秒','3秒','4秒','6秒'], answerIndex:2, explanation:'超过 30 mph 时，良好路况下建议约 4 秒。', en:{question:'Under good road conditions above 30 mph, what following interval does the Texas Driver Handbook recommend?',choices:['2 seconds','3 seconds','4 seconds','6 seconds'],explanation:'Above 30 mph, the handbook recommends about a 4-second following interval in good conditions.'}},
  { id:'tx-follow-003', category:'safety', question:'路况差、下雨或能见度低时，跟车距离应该怎样调整？', choices:['缩短','保持不变','增加','只看限速'], answerIndex:2, explanation:'恶劣路况会增加停车距离，应增加跟车时间和空间。', en:{question:'How should following distance change in poor weather or low visibility?',choices:['Decrease it','Keep it the same','Increase it','Ignore it and watch only the speed limit'],explanation:'Poor conditions increase stopping distance, so drivers should allow more time and space.'}},
]
