import type { DmvQuestion } from './dmv-data'

type WaQuestion = DmvQuestion & { en: { question: string; choices: string[]; explanation: string } }

export const washingtonQuestions: WaQuestion[] = [
  { id:'wa-school-001', category:'rules', question:'华盛顿州 school zone 的常见限速是多少？', choices:['15 mph','20 mph','25 mph','30 mph'], answerIndex:1, explanation:'Washington Driver Guide 将 school zone 常见限速列为 20 mph。', en:{question:'What is the common speed limit in a Washington school zone?',choices:['15 mph','20 mph','25 mph','30 mph'],explanation:'The Washington Driver Guide identifies 20 mph as the common school-zone speed limit.'}},
  { id:'wa-bus-001', category:'rules', question:'华州校车停下并闪红灯、stop sign 展开时，同方向车辆应怎么做？', choices:['减速通过','停车等待','鸣笛后通过','从中心转弯车道通过'], answerIndex:1, explanation:'同方向车辆必须停车，直到红灯停止闪烁、stop sign 收回且安全。', en:{question:'What must traffic traveling in the same direction do when a Washington school bus stops with red lights flashing and its stop sign extended?',choices:['Slow and pass','Stop and wait','Honk and pass','Pass in the center turn lane'],explanation:'Traffic traveling in the same direction must stop until the red lights stop flashing, the stop sign retracts, and it is safe to proceed.'}},
  { id:'wa-bus-002', category:'rules', question:'华州驾驶人能否使用中心转弯车道绕过正在闪红灯的校车？', choices:['可以','不可以','只有低速时可以','只有夜间可以'], answerIndex:1, explanation:'Washington Driver Guide 明确禁止使用 center turn lane 绕过停靠并闪红灯的校车。', en:{question:'May a Washington driver use a center turn lane to pass a stopped school bus with red lights flashing?',choices:['Yes','No','Only at low speed','Only at night'],explanation:'The Washington Driver Guide says drivers may not use a center turn lane to pass a stopped school bus with flashing red lights.'}},
  { id:'wa-bus-003', category:'rules', question:'在华州两车道道路上，校车闪红灯时，对向车辆通常应怎样做？', choices:['继续行驶','停车','只减速','鸣笛通过'], answerIndex:1, explanation:'在两车道道路上，双向车辆通常都必须为闪红灯并展开 stop sign 的校车停车。', en:{question:'On a two-lane Washington road, what should opposing traffic normally do for a school bus with red lights flashing?',choices:['Continue','Stop','Only slow down','Honk and pass'],explanation:'On a two-lane road, traffic in both directions normally must stop for the school bus.'}},
  { id:'wa-bus-004', category:'rules', question:'在华州三条或更多车道的道路上，校车对向车辆通常是否必须停车？', choices:['始终必须','通常不必','只有白天不必','只有高速公路不必'], answerIndex:1, explanation:'华州规则对三条或更多车道的道路提供对向交通例外；同方向车辆仍必须停车。', en:{question:'On a Washington road with three or more lanes, must opposing traffic normally stop for a school bus?',choices:['Always','Usually no','Only not during daylight','Only not on freeways'],explanation:'Washington rules provide an opposing-traffic exception on roads with three or more lanes; traffic traveling with the bus must still stop.'}},
  { id:'wa-bus-005', category:'rules', question:'华州道路由 median 或实体 barrier 分隔时，校车另一侧的对向车辆通常应怎样做？', choices:['必须停车','通常可继续但应谨慎','必须倒车','必须驶入路肩'], answerIndex:1, explanation:'实体中央隔离带分开的道路，对向交通通常无需为另一侧校车停车，但仍应注意儿童和道路情况。', en:{question:'When a Washington roadway is divided by a median or physical barrier, what may opposing traffic on the other side normally do for a school bus?',choices:['Must stop','May generally continue with caution','Must back up','Must pull onto the shoulder'],explanation:'Opposing traffic separated by a physical median or barrier generally does not have to stop for a school bus on the other side.'}},
  { id:'wa-bus-006', category:'rules', question:'非法超越华州停靠并闪红灯的校车，罚款会怎样？', choices:['减半','通常加倍','没有罚款','只警告'], answerIndex:1, explanation:'Washington Driver Guide 明确说明非法超越停靠校车的罚款会加倍。', en:{question:'What happens to the fine for illegally passing a stopped school bus in Washington?',choices:['It is cut in half','It is generally doubled','There is no fine','Warning only'],explanation:'The Washington Driver Guide states that fines are doubled for illegally passing a stopped school bus.'}},

  { id:'wa-headlight-001', category:'safety', question:'华州法律要求从什么时候到什么时候必须开启 headlights？', choices:['日落到日出','日落后30分钟到日出前30分钟','只在午夜后','只在下雨时'], answerIndex:1, explanation:'华州法律要求从日落后半小时到日出前半小时开启 headlights。', en:{question:'When does Washington law require headlights to be on?',choices:['Sunset to sunrise','From 30 minutes after sunset until 30 minutes before sunrise','Only after midnight','Only when raining'],explanation:'Washington law requires headlights from one-half hour after sunset until one-half hour before sunrise.'}},
  { id:'wa-headlight-002', category:'safety', question:'夜间与对向车辆距离约多少英尺以内时，华州驾驶人应切换到近光灯？', choices:['200 ft','300 ft','500 ft','1000 ft'], answerIndex:2, explanation:'接近对向车辆 500 英尺以内应从 high beams 切换到 regular/low beams。', en:{question:'Within what distance of an oncoming vehicle should a Washington driver dim high beams?',choices:['200 ft','300 ft','500 ft','1000 ft'],explanation:'Drivers should switch from high beams to regular headlights within 500 feet of an oncoming vehicle.'}},
  { id:'wa-headlight-003', category:'safety', question:'夜间跟随前车距离约多少英尺以内时，应使用近光灯？', choices:['100 ft','200 ft','300 ft','500 ft'], answerIndex:2, explanation:'华州 Driver Guide 说明，在前车后方 300 英尺以内应使用 regular headlights。', en:{question:'Within what distance behind another vehicle should a Washington driver use regular/low beams?',choices:['100 ft','200 ft','300 ft','500 ft'],explanation:'The Washington Driver Guide says to use regular headlights when following within 300 feet.'}},
  { id:'wa-headlight-004', category:'safety', question:'白天行车灯 DRL 是否等同于完整 headlights？', choices:['是','不是，因为亮度和尾灯功能可能不同','只在夏天等同','只在城市等同'], answerIndex:1, explanation:'DRL 通常不如 headlights 亮，而且不会自动点亮尾灯。', en:{question:'Are daytime running lights the same as full headlights?',choices:['Yes','No, because brightness and taillight operation may differ','Only in summer','Only in cities'],explanation:'Daytime running lights are generally not as bright as headlights and may not activate the taillights.'}},

  { id:'wa-teen-001', category:'rules', question:'华州16–17岁首次申请驾照前，instruction permit 通常至少要持有多久？', choices:['30天','3个月','6个月','12个月'], answerIndex:2, explanation:'16–17岁首次拿证通常要求 permit 至少持有 6 个月。', en:{question:'How long must a Washington driver age 16–17 normally hold an instruction permit before getting a first license?',choices:['30 days','3 months','6 months','12 months'],explanation:'Washington normally requires 16–17-year-old first-time drivers to hold the permit for at least 6 months.'}},
  { id:'wa-teen-002', category:'rules', question:'华州16–17岁首次拿证前，至少需要完成多少小时白天监督驾驶？', choices:['20小时','30小时','40小时','50小时'], answerIndex:2, explanation:'要求至少 40 小时白天监督驾驶。', en:{question:'How many hours of supervised daytime driving are required for a Washington driver age 16–17 before first licensing?',choices:['20','30','40','50'],explanation:'At least 40 hours of supervised daytime driving are required.'}},
  { id:'wa-teen-003', category:'rules', question:'华州16–17岁首次拿证前，至少需要多少小时夜间监督驾驶？', choices:['5小时','10小时','15小时','20小时'], answerIndex:1, explanation:'要求至少 10 小时夜间监督驾驶。', en:{question:'How many hours of supervised nighttime driving are required for a Washington driver age 16–17?',choices:['5','10','15','20'],explanation:'At least 10 hours of supervised nighttime driving are required.'}},
  { id:'wa-teen-004', category:'rules', question:'华州16–17岁申请驾照前，最近多久通常不能有交通违规或定罪？', choices:['30天','3个月','6个月','1年'], answerIndex:2, explanation:'申请前通常要求连续 6 个月没有交通违规或定罪。', en:{question:'For how long before applying for a license must a Washington driver age 16–17 normally have no traffic violations or convictions?',choices:['30 days','3 months','6 months','1 year'],explanation:'Washington normally requires 6 months without traffic violations or convictions before licensing.'}},
  { id:'wa-idl-001', category:'rules', question:'华州 Intermediate Driver License 发证后前6个月，通常能否搭载未满20岁的非直系家庭成员？', choices:['可以无限制','通常不可以','最多5人','只在夜间禁止'], answerIndex:1, explanation:'前 6 个月通常不得搭载未满 20 岁的非直系家庭成员。', en:{question:'During the first six months of a Washington Intermediate Driver License, may the driver normally carry passengers under 20 who are not immediate family members?',choices:['Yes, without limit','Generally no','Up to five','Only prohibited at night'],explanation:'During the first six months, passengers under 20 are generally prohibited unless they are immediate family members.'}},
  { id:'wa-idl-002', category:'rules', question:'华州 Intermediate Driver License 前6个月，通常在哪个时间段禁止单独驾驶？', choices:['11 p.m.–4 a.m.','12 a.m.–5 a.m.','1 a.m.–5 a.m.','2 a.m.–6 a.m.'], answerIndex:2, explanation:'通常禁止凌晨 1:00–5:00 单独驾驶，除非由父母、监护人或至少25岁的合格驾驶人陪同。', en:{question:'During the first six months of a Washington Intermediate Driver License, what nighttime hours are normally restricted?',choices:['11 p.m.–4 a.m.','12 a.m.–5 a.m.','1 a.m.–5 a.m.','2 a.m.–6 a.m.'],explanation:'Driving is normally restricted from 1 a.m. to 5 a.m. unless accompanied by a parent, guardian, or qualified licensed driver age 25 or older.'}},
  { id:'wa-idl-003', category:'rules', question:'Intermediate License 持证满6个月后，到18岁或满1年之前，通常最多可搭载几名未满20岁的非家庭成员？', choices:['1名','2名','3名','无限制'], answerIndex:2, explanation:'第二阶段通常最多 3 名未满 20 岁的非直系家庭成员。', en:{question:'After six months, until age 18 or one year of licensing, how many passengers under 20 who are not immediate family may a Washington intermediate driver normally carry?',choices:['1','2','3','Unlimited'],explanation:'The second phase normally allows no more than three passengers under 20 who are not immediate family members.'}},
  { id:'wa-idl-004', category:'safety', question:'华州 Intermediate License 驾驶人开车时可以使用 hands-free 手机吗？', choices:['可以','不可以，除非报告紧急情况','只有白天可以','只有导航可以'], answerIndex:1, explanation:'Intermediate License 对手机限制更严格，即使 hands-free 也不能使用，除非报告紧急情况。', en:{question:'May a Washington Intermediate License driver use a hands-free phone while driving?',choices:['Yes','No, except to report an emergency','Only during daylight','Only for navigation'],explanation:'Intermediate License restrictions prohibit mobile-device use even hands-free, except to report an emergency.'}},

  { id:'wa-permit-001', category:'rules', question:'华州18岁以上 permit holder 练习驾驶时，陪同驾驶人通常至少需要多少年驾驶经验？', choices:['1年','3年','5年','10年'], answerIndex:2, explanation:'DOL learner permit 指南要求练习驾驶时由至少有 5 年驾驶经验的持照驾驶人陪同。', en:{question:'How much driving experience must the accompanying licensed driver normally have for a Washington permit holder age 18 or older?',choices:['1 year','3 years','5 years','10 years'],explanation:'Washington DOL guidance requires a licensed accompanying driver with at least 5 years of driving experience.'}},
  { id:'wa-permit-002', category:'safety', question:'持华州 instruction permit 驾驶时，能否使用手机？', choices:['可以自由使用','通常不可以，除非拨打911等紧急情况','只可发短信','只在红灯时可以'], answerIndex:1, explanation:'permit holder 驾驶时不得使用手机或移动电子设备，紧急情况除外。', en:{question:'May a Washington instruction permit holder use a phone while driving?',choices:['Yes, freely','Generally no, except for emergencies such as calling 911','Texting only','Only at red lights'],explanation:'A permit holder may not use a phone or mobile electronic device while driving except in an emergency.'}},

  { id:'wa-ped-001', category:'rules', question:'华州驾驶人在人行横道让行时，一般应等行人离开本车道以及什么范围后再继续？', choices:['只离开本车道即可','本车道外再多一条车道','离开整条道路','走到道路中心即可'], answerIndex:1, explanation:'华州规则强调行人应离开驾驶人所在车道以及额外一条车道后，驾驶人才可继续。', en:{question:'When yielding at a crosswalk in Washington, how far should a pedestrian generally clear before you proceed?',choices:['Only your lane','Your lane plus one additional lane','The entire roadway','Only to the road center'],explanation:'Washington guidance says the pedestrian should clear your lane plus one additional lane before you proceed.'}},
  { id:'wa-ped-002', category:'rules', question:'遇到使用轮椅、白手杖、导盲犬或 service animal 的行人过街时，应等到什么时候再继续？', choices:['离开本车道即可','完全过街后','走到中央线','挥手后'], answerIndex:1, explanation:'对这类行人应等其完全穿过道路后再继续行驶。', en:{question:'When a pedestrian using a wheelchair, white cane, guide dog, or service animal is crossing, when should a Washington driver proceed?',choices:['After they leave your lane','After they completely cross the roadway','After they reach the centerline','After waving'],explanation:'Drivers should wait until the person has completely crossed the roadway.'}},
  { id:'wa-ped-003', category:'rules', question:'前车因人行横道行人停车时，后车应怎样做？', choices:['从旁边超越','停车并等待','鸣笛后通过','驶上路肩'], answerIndex:1, explanation:'不能超越正在为行人停车让行的车辆。', en:{question:'What should you do when the vehicle ahead has stopped for a pedestrian at a crosswalk?',choices:['Pass it','Stop and wait','Honk and pass','Drive on the shoulder'],explanation:'Do not pass a vehicle that is stopped to yield to a pedestrian.'}},

  { id:'wa-transit-001', category:'rules', question:'华州同方向行驶的 transit bus 打转向灯准备重新驶入车流时，驾驶人应怎样做？', choices:['加速抢先','让公交车先行','鸣笛','必须停车5分钟'], answerIndex:1, explanation:'华州规则要求在安全情况下让正在重新进入车流的 transit bus。', en:{question:'What should a Washington driver do when a transit bus traveling in the same direction signals to re-enter traffic?',choices:['Accelerate past','Yield to the bus','Honk','Stop for five minutes'],explanation:'Washington drivers should yield when a transit bus signals to re-enter traffic, when safe to do so.'}},

  { id:'wa-dui-001', category:'safety', question:'华州21岁及以上驾驶人的 BAC 法定标准通常是多少？', choices:['0.02%','0.05%','0.08%','0.10%'], answerIndex:2, explanation:'21岁及以上驾驶人 BAC 0.08% 或更高可构成 DUI 法律标准之一。', en:{question:'What is the usual BAC legal threshold for a Washington driver age 21 or older?',choices:['0.02%','0.05%','0.08%','0.10%'],explanation:'A BAC of 0.08% or higher is one of Washington’s DUI legal thresholds for drivers age 21 or older.'}},
  { id:'wa-dui-002', category:'safety', question:'华州未满21岁驾驶人的 BAC 标准通常是多少？', choices:['0.00%','0.02%','0.05%','0.08%'], answerIndex:1, explanation:'未满 21 岁的驾驶人适用 0.02% BAC 标准。', en:{question:'What BAC threshold generally applies to a Washington driver under age 21?',choices:['0.00%','0.02%','0.05%','0.08%'],explanation:'Washington applies a 0.02% BAC threshold to drivers under age 21.'}},
  { id:'wa-dui-003', category:'safety', question:'华州21岁及以上驾驶人 THC 达到多少 ng/mL 是法定 DUI 标准之一？', choices:['1.00','2.50','5.00','10.00'], answerIndex:2, explanation:'21岁及以上驾驶人血液 THC 达到 5.00 ng/mL 是法定标准之一。', en:{question:'What THC level is one of Washington’s DUI legal thresholds for drivers age 21 or older?',choices:['1.00 ng/mL','2.50 ng/mL','5.00 ng/mL','10.00 ng/mL'],explanation:'A blood THC level of 5.00 ng/mL is one of Washington’s legal DUI thresholds for drivers age 21 or older.'}},
  { id:'wa-dui-004', category:'safety', question:'华州未满21岁驾驶人的 THC 法律标准通常是什么？', choices:['0','2.5 ng/mL','5 ng/mL','10 ng/mL'], answerIndex:0, explanation:'未满21岁驾驶人适用更严格的 THC 零容忍标准。', en:{question:'What THC standard generally applies to Washington drivers under age 21?',choices:['0','2.5 ng/mL','5 ng/mL','10 ng/mL'],explanation:'Washington applies a stricter zero-tolerance THC standard to drivers under age 21.'}},

  { id:'wa-phone-001', category:'safety', question:'华州一般驾驶人手持手机发短信或操作设备是否允许？', choices:['允许','不允许','只在低速时允许','只在高速公路允许'], answerIndex:1, explanation:'分心驾驶法律禁止驾驶中手持使用手机等电子设备。', en:{question:'May a Washington driver hold a phone to text or operate the device while driving?',choices:['Yes','No','Only at low speed','Only on freeways'],explanation:'Washington distracted-driving law prohibits handheld phone and electronic-device use while driving.'}},
  { id:'wa-phone-002', category:'safety', question:'如果必须处理手机事项，最安全的做法是什么？', choices:['边开边操作','驶离道路并安全停车后处理','红灯时快速操作','让方向盘自动保持'], answerIndex:1, explanation:'应先驶离行车道并在安全合法位置停车，再处理非紧急手机事项。', en:{question:'What is the safest way to handle a phone task while driving?',choices:['Use it while moving','Pull off the roadway and park safely first','Use it quickly at a red light','Let the steering wheel hold course'],explanation:'For non-emergency phone tasks, pull off the roadway and park safely and legally first.'}},

  { id:'wa-rail-001', category:'rules', question:'接近铁路道口时，如果红灯闪烁或栏杆下降，驾驶人应该怎样做？', choices:['加速通过','停车等待','绕过栏杆','鸣笛后通过'], answerIndex:1, explanation:'红灯闪烁或栏杆下降表示必须停车并等待列车通过。', en:{question:'What should a Washington driver do at a railroad crossing when red lights are flashing or gates are lowered?',choices:['Accelerate through','Stop and wait','Drive around the gate','Honk and proceed'],explanation:'Flashing red lights or lowered gates require drivers to stop and wait for the train to pass.'}},
  { id:'wa-rail-002', category:'rules', question:'铁路道口前方拥堵、无法保证完全通过时，应怎样做？', choices:['先驶上铁轨等待','在铁轨前等待直到有足够空间','紧跟前车','鸣笛'], answerIndex:1, explanation:'绝不能停在铁轨上；只有确认前方有足够空间完全通过时才进入道口。', en:{question:'What should you do if traffic is backed up beyond a railroad crossing and you cannot clear the tracks?',choices:['Enter the tracks and wait','Wait before the tracks until there is enough room to cross completely','Follow the vehicle ahead closely','Honk'],explanation:'Never stop on railroad tracks; enter only when there is enough space to clear the crossing completely.'}},

  { id:'wa-move-001', category:'safety', question:'接近路边停靠并显示警示灯的紧急或道路作业车辆时，应怎样做？', choices:['加速','减速并在安全时移开一个车道','贴近通过','关闭车灯'], answerIndex:1, explanation:'应减速，并在多车道道路上安全可行时移到远离作业或紧急车辆的车道。', en:{question:'What should a Washington driver do when approaching a stopped emergency or roadside work vehicle displaying warning lights?',choices:['Accelerate','Slow down and move over a lane when safe','Pass closely','Turn off headlights'],explanation:'Slow down and, on a multilane road, move to a lane farther away when it is safe to do so.'}},

  { id:'wa-safety-001', category:'safety', question:'雨雪、雾或烟雾影响能见度时，正确做法是什么？', choices:['提高速度','减速、增加跟车距离并开启合适车灯','只开停车灯','紧跟前车'], answerIndex:1, explanation:'能见度和抓地力下降时应降低速度、增加空间并确保车辆灯光可见。', en:{question:'What should a Washington driver do in rain, snow, fog, or smoke that reduces visibility?',choices:['Increase speed','Slow down, increase following distance, and use appropriate lights','Use parking lights only','Follow closely'],explanation:'When visibility or traction is reduced, slow down, increase space, and make sure proper vehicle lights are on.'}},
  { id:'wa-safety-002', category:'safety', question:'夜间驾驶速度应满足什么基本原则？', choices:['能在车灯照明范围内停车','必须达到限速上限','始终跟随前车','只看导航'], answerIndex:0, explanation:'夜间应控制速度，使车辆能够在 headlights 照亮的范围内安全停车。', en:{question:'What basic rule should guide your speed at night?',choices:['You should be able to stop within the distance illuminated by your headlights','Always drive at the maximum posted speed','Always follow another vehicle','Watch only navigation'],explanation:'At night, drive slowly enough to stop within the area illuminated by your headlights.'}},
  { id:'wa-safety-003', category:'safety', question:'夜间对向 headlights 很亮时，应怎样处理视线？', choices:['直视灯光','避免直视并继续扫描本车前方道路','闭眼','打开车内灯'], answerIndex:1, explanation:'不要盯着对向灯，应持续搜索前方道路并参考道路边缘。', en:{question:'How should you handle glare from oncoming headlights at night?',choices:['Look directly at the lights','Avoid staring at them and keep scanning the road ahead','Close your eyes','Turn on the interior light'],explanation:'Avoid looking directly into oncoming headlights and continue scanning the roadway ahead.'}},
  { id:'wa-safety-004', category:'safety', question:'华州驾驶时佩戴同时覆盖双耳、播放声音或降噪的耳机通常是否合法？', choices:['合法','通常不合法','只在高速公路合法','只在白天合法'], answerIndex:1, explanation:'Washington Driver Guide 说明驾驶时佩戴播放声音或降噪的耳塞、耳机、headset 属违法；符合规定的单耳 hands-free 设备可例外。', en:{question:'Is it generally legal in Washington to drive while wearing sound-playing or noise-canceling headphones over both ears?',choices:['Yes','Generally no','Only on freeways','Only during daylight'],explanation:'Washington guidance says driving with sound-playing or noise-canceling earbuds, earphones, headphones, or headsets is unlawful; a compliant hands-free device in one ear may be allowed.'}},

  { id:'wa-sign-001', category:'signs', question:'红色八角形 STOP 标志要求什么？', choices:['减速','完全停车','鸣笛','只让行'], answerIndex:1, explanation:'STOP 标志要求在停止线、横道前或可安全观察的位置完全停车。', en:{question:'What does a red octagonal STOP sign require?',choices:['Slow down','Come to a complete stop','Honk','Yield only'],explanation:'A STOP sign requires a complete stop at the stop line, before the crosswalk, or at a safe observation point.'}},
  { id:'wa-sign-002', category:'signs', question:'红白倒三角 YIELD 标志表示什么？', choices:['完全停车5秒','减速并让有优先权的交通先行','禁止进入','施工区'], answerIndex:1, explanation:'YIELD 要求减速、准备停车，并让有路权的车辆或行人先行。', en:{question:'What does a red-and-white triangular YIELD sign mean?',choices:['Stop for five seconds','Slow down and yield to traffic with the right-of-way','Do not enter','Construction zone'],explanation:'YIELD means slow down, be ready to stop, and give the right-of-way to traffic or pedestrians as required.'}},
  { id:'wa-sign-003', category:'signs', question:'橙色标志通常表示什么？', choices:['施工或临时交通控制','医院','学校','休息区'], answerIndex:0, explanation:'橙色通常用于施工、维护或临时交通控制。', en:{question:'What do orange signs generally indicate?',choices:['Construction or temporary traffic control','Hospital','School','Rest area'],explanation:'Orange signs generally indicate construction, maintenance, or temporary traffic control.'}},
  { id:'wa-sign-004', category:'signs', question:'黄色菱形标志通常表示什么？', choices:['警告前方道路状况','停车许可','服务设施','车辆登记'], answerIndex:0, explanation:'黄色菱形通常为 warning sign，提醒弯道、路口、行人等前方风险。', en:{question:'What does a yellow diamond-shaped sign generally mean?',choices:['Warning of road conditions ahead','Parking permit','Service facility','Vehicle registration'],explanation:'Yellow diamond-shaped signs are generally warning signs for hazards or roadway conditions ahead.'}},
]
